IBM/sarama

produce_request.go, producer.go
Per https://groups.google.com/d/msg/kafka-clients/4dR2FeN9GKE/_I3WRMoF8AsJ
Setting it to a value > 1 will raise an exception in 0.8.2.0 and later, so
update the godoc and log a warning when validating such a configuration.
@wvanbergen @snormore @drdee 
cc @mkobetic @yagnik
=> producer: add warning about RequiredAcks>1

client.go
Verify that we really got a leader back, even in the case where the error is not
LeaderNotAvailable. Might solve #245.
@nsd20463 does this fix your bug? If so I will merge it, but I would also suggest filing a ticket upstream that Kafka should really return `LeaderNotAvailable` if it's not going to send us a broker.
=> Don't fully trust kafka metadata errors

producer_test.go, simple_producer.go
Take a full ProducerConfig for more flexibility (covers #242) and permit
producing messages with different topics. Breaks the API, but we're not frozen
quite yet.
@yagnik @drdee 
cc @wvanbergen @mihasya
=> Make the simple producer API more powerful

client.go
Apparently my assumption in 1b465e78c274a76c0a522272cac25e39ddaa0d07 was false,
and `LeaderNotAvailable` can also appear at the topic level (not just the
partition level).
=> client: recognize full-topic leader election

producer.go
Otherwise requests are almost bound to fail - there's no good reason for this
config.
@wvanbergen @drdee
=> Require a non-zero timeout when WaitForAll

client.go
According to the logs, this was the cause of the kafka_sysv_mq_producer was not restarting during our testing. Apparently we already found that this caused issues when using LeaderNotAvailable (#144), and apparently ReplicaNotAvailable can happen to. We should handle them similarly
@Shopify/kafka
=> Handle ReplicaNotAvailable like LeaderNotAvailable when initializing a client

producer.go
If we don't do this we'll foist it off on the flusher, which is legit but means
we waste our retry. We can fail fast here and the resulting behaviour will be
better.
@wvanbergen
=> When we get a new leader, check it is connected

client.go
As per 1b465e78c274a76c0a522272cac25e39ddaa0d07, "I can't think of a case where
the stale data from the last "complete" update is somehow more useful than the
up-to-date partial data."
@wvanbergen
=> Process partition metadata in event of topic-level error

producer_test.go
This test failed randomly in an unrelated PR:
https://travis-ci.org/Shopify/sarama/jobs/50586636
Turns out we were relying on the go scheduler to end up batching 100 messages
into exactly two requests, which isn't guaranteed at all. Now that we can pass a
full config into the SimpleProducer, just set the FlushMsgCount and expect a
single request.
cc @wvanbergen @drdee @yagnik
=> Fix flaky SimpleProducer test

functional_test.go
=> Add a test to make sure connection to a cluster that is completely down will return an error

consumer.go, consumer_test.go, functional_test.go
- `Consumer` is now a much lighter "manager" that spawns `PartitionConsumer`s
instead. `PartitionConsumer`s behave and have an API almost exactly like the
old `Consumer`.
- Automatically groups and redispatches PartitionConsumers when leadership moves
in the cluster.
As with the producer-ng, this is effectively a rewrite and (with the exception of the changes to functional_test.go) should be reviewed wholesale rather than by diff.
@mkobetic @snormore @wvanbergen @yagnik @drdee and anyone else who cares, this is ready to be looked at whenever is convenient. Thoughts on the API? Thoughts on the TODOs still sprinkled about?
Fixes #140 
Fixes #200 
Fixes #225
=> Rewrite consumer to support multiple partitions

producer.go
This value should be at least the amount of time it takes for a non-responsive broker to be considered out of sync. The default value for that is 10 seconds. So I set it to 10 seconds, which matches the default setting of the JVM producer. Maybe we should set it a bit higher as a safety buffer?
@Shopify/kafka @mkobetic
=> Set default producer request timeout to 10 seconds

producer.go
Part of #270, this documents the equivalents of the producer. AFAICS the other settings do not have equivalents.
Besides documenting, maybe we can also fix some naming inconsistencies and ambiguities ?
@drdee @eapache
=> Document setting equivalents with JVM producer

producer.go
Per
https://mail-archives.apache.org/mod_mbox/kafka-users/201502.mbox/%3CCAHBV8WfeCqFqPsZVLbyaCNohLpDBXdZp_U6YnHaQoX20jcCG3g%40mail.gmail.com%3E
this is the upstream decision and I think it makes sense.
@Shopify/kafka
=> Retry timed-out messages in the producer.

client.go
Previously, if the cluster metadata was giving us back a broker which we
suspected was unavailable (since it was already in our 'dead' set) then we would
wait for the connection, and mark it as unavailable if the connection failed
(otherwise, we simply do what the cluster tells us and let the
producers/consumers deal with the connection errors). This was handy since it
let us back off nicely if a broker crashed and came back, retrying metadata
until the cluster had caught up and moved the leader to a broker that was up.
I'm now of the opinion this was more trouble than it's worth, so scrap it. Among
other things:
- it does network IO while holding an important mutex, which is a bad pattern
to begin with (fixes #263)
- it can mask real network errors behind "LeaderNotAvailable" (fixes …
=> Scrap the connection test in the client metadata update

producer.go
Doesn't ~~work~~ do anything really yet, but this is the first group of superficial changes necessary to support
multiple retries in the producer.
@Shopify/kafka
=> Move retries to its own field and make MaxRetries configurable

producer.go
Not just on flusher-triggered retries.
=> Producer: back off after failing to find a leader

simple_producer.go
Rather than storing a `map` from messages to expectations, store the
expectations in our handy new `Metadata` field. This is certainly simpler, and
is probably slightly more efficient.
Also call `AsyncClose` instead of `Close` when shutting down the underlying
Producer, to avoid the hypothetical race condition where `Close` swallows a
success or error and that call to `SendMessage` never returns.
@Shopify/kafka
=> Use Metadata field in SimpleProducer

mockbroker.go
I've been playing with writing more resiliency tests with mockbrokers and the
only thing missing was the ability to shut down a broker and then bring it back
on the same address - this PR adds that capability.
@Shopify/kafka @Sirupsen
=> Permit starting a mockbroker on a specific address

producer_test.go
With mockbrokers we control the relevant ordering of messages and broker
starts/stops so it isn't necessary, all it does is slow down the tests and give
room for time-dependent behaviour to creep in.
Also shaves 500ms off the test suite.
cc @Shopify/kafka @Sirupsen
=> Don't use a RetryBackoff in tests

client.go, client_test.go
For more information, see #286
=> Cache client partition results to save the repeated sort() calls

producer.go, producer_test.go
Implement multiple in-order retries in the producer.
The mental model here is a fairly straightforward expansion of the existing single-retry logic (where the messages go through the pipeline again, and the `leaderDispatcher` pauses un-retried messages until all the retries have happened in order to preserve ordering).
The new version just keeps track of the high-watermark retry in progress (aka how many times the most-retried in-flight message has been retried) and makes sure that all messages with a lower retry-count are paused until the chaser has been seen. 
Fixes #232
=> Retry more than once

producer.go, producer_test.go
Write a test, find a bug (well, not really).
Before multiple-retries were in place, I'd added this pre-emptive check for
leader connectedness in the leaderDispatcher so that if we got back stale
metadata we didn't bother going through the whole retry rigamarole and failing
anyways. Now that we have multiple-retries, this check is actually causing us to
short-circuit our retries in one case, which isn't nice. Since it isn't
necessary anymore, just remove it.
Discovered because the test I wrote for stale metadata tried to make more
metadata requests than I was expecting, and subsequently hung.
P.S. I will fix all the tests to be understandable in a following PR, I promise.
=> Don't pre-emptively test the leader connectedness

producer.go
Matches the default values of the JVM producer. Also updates godoc.
@Shopify/kafka
=> Update producer's MaxRetries and RetryBackoff default values

mockbroker.go
=> Add the possibility to introduce latency to the mock broker

consumer.go, consumer_metadata_response.go, consumer_metadata_response_test.go, errors.go, snappy.go
- Error strings should not end with a dot.
- No need for `else` when if clause has return statement.
- Exported constants should be documented.
- Some minor changes about variables.
The following glint suggestions have not been implemented.
- Document all methods, or do not export them.
- Error variables should start with Err.
@eapache
=> Address some golint suggestions

broker.go, client.go, client_test.go, consumer.go, consumer_metadata_response_test.go, consumer_test.go, crc32_field.go, encoder_decoder.go, errors.go, fetch_response_test.go, functional_test.go, length_field.go, message.go, message_set.go, metadata_response_test.go, offset_commit_response_test.go, offset_fetch_response_test.go, offset_response_test.go, prep_encoder.go, produce_response_test.go, producer.go, producer_test.go, real_decoder.go, response_header.go, sarama.go
- Prefix error variables (including `KError` instances) with `Err` (golint suggestion)
- Change `(Packet)EncodingError` to be a type like `(Packet)DecodingError`.
@Shopify/kafka
=> Error variables

consumer.go, consumer_test.go, functional_test.go
This is more in line with the producer. Also, it is really easy to forget checking for the `Err` field for every `ConsumerEvent`, which would lead to bugs.
@Shopify/kafka
=> Split consumer’s Events() channel into Messages() and Errors()

functional_test.go, producer.go, producer_test.go, simple_producer.go
- `MessageToSend` -> `ProducerMessage`
- `ProduceError` -> `ProducerError`
- `ProduceErrors` -> `ProducerErrors`
Also, `ProducerError` now implements the `error` interface like .
Matches the names in #303. Also a step towards #273.
@Shopify/kafka
=> Naming changes in the producer to be consistent with the consumer

broker_test.go, client_test.go, consumer_test.go, mockbroker.go, producer_test.go
Don't export MockBroker; it's internal only. This allows us to break its API without having to do a major release.
@Shopify/kafka
=> Unexport mockbroker.

broker.go, errors.go
The intent behind the design was so that the method was always safe to call e.g.
when a lock was held, by making it async, however there were still certain cases
where it could have blocked:
- if another thread had already called Open, subsequent calls would block until
that network io completed
- if the connection was already open *and* the pipeline was full
(MaxOpenRequests were in flight) then calling Open would block until at least
one response was received
This adds a simple atomic flag we can use to short-circuit appropriately, such
that Open should now have the following properties
- it *never* blocks on network IO
- it guarantees that the broker is connected or connecting when it returns
(modulo another thread calling Close in the interim)
AFAICT these are the properties it needs …
=> Make Broker.Open truly non-blocking

errors.go
Hi,
the KError enum is not complete for Kafka 0.8.2.0. This PR adds the missing errors.
=> Update the KError enum for Kafka 0.8.2.0

partitioner.go, partitioner_test.go
The only part the user needs to have access to is the set of constructors, so
make the types themselves private, which somewhat reduces our API surface.
Also remove the ConstantPartitioner. It is trivial, not particularly useful in
practice, and was only added for use in a long-since-defunct functional test.
@Shopify/kafka
=> Make partitioner implementations private

client.go, producer.go
Per the discussion on PR #313, there are a few changes needed to handle all the
errors that can be returned by kafka 0.8.2:
- adjust comments and error return in the client when faced with a blank topic,
to reflect the fact that this is now fixed upstream and to match upstream's
error message
- retry ErrNotEnoughReplicas and ErrNotEnoughReplicasAfterAppend in the producer
@Shopify/kafka @vrischmann
=> Handle new errors from kafka 0.8.2

.travis.yml, README.md
Should still work of course, but we don't care to test it anymore.
Part of #319 
@Shopify/kafka
=> Drop official support for go 1.2

broker.go, broker_test.go, client.go, client_test.go, config.go, config_test.go, consumer.go, consumer_test.go, functional_test.go, producer.go, producer_test.go, sync_producer.go
Unify configuration structures into `config.go` per discussion on #308.
Also take the opportunity to rename and reorganize some values, and to document
some equivalents with the JVM version, finishing up #270.
Open questions:
- I don't know what to do about the `addrs` parameter to `NewClient`. Karl suggested it should be moved to the constructor of the config object, but in hindsight that doesn't make sense because if you're constructing a config object *for* a broker, then you should not have to specify multiple addresses at all. It really should be a parameter of the constructor I think.
- Given that there are non-config parameters to the client constructor, how do we go about "hiding" the client from users of the producer/consumer? Just pass those parameters through?
I'm thinking …
=> Unify config

producer_test.go
=> Add an example for using the async producer with goroutines

partitioner.go, partitioner_test.go, producer.go
This allows you to create custom partitioning schemes, e.g. by using the Metadata field.
Example:
``` go
type PartitionMetadata interface {
Partition() int32
}
type myPartitioner struct {}
func (mp *myPartitioner) Partition(message *ProducerMessage, numPartitions int32) (int32, error) {
if pm, ok := message.Metadata.(PartitionMetadata); ok {
return pm.Partition(), nil
} else {
return 0, errors.New("You have to set the partition in the message's Metadata")
}
}
func (mp *myPartitioner) RequiresConsistency() {
return true 
}
myPartitionerConstructor := func()  {
return &myPartitioner{}
}
```
@Shopify/kafka
=> Partitioners operate on the entire ProducerMessage, not just the key

config.go, consumer.go, consumer_test.go, functional_test.go, mocks/producer.go, mocks/producer_test.go, producer.go, producer_test.go, sync_producer.go
- Make consumer retry backoff configurable, use 10s by default.
- Allow opting out of reading the Errors channel, by setting Consumer.AckErrors and/or Producer.AckErrors to false.
- Fix some documentation.
- The retry backoff for the JVM producer is 200ms, we use 10,000ms. :+1:/:-1:?
- I am kind of inclined to default `AckErrors` to `false`, at least for the consumer. The Errors channel is not very useful, because the consumer will retry anyway and keep on going. Figuring out in what scenario you should stop the consumer, because not all errors are created equal. Ideally we would have a way to detect whether somebody is consuming the channel, but I haven't figured out a way.
- I'd rather add a `Consumer.Timeout` setting, so you can make the consumer stop if no messages have been received …
=> Configuration tweaks

client.go, client_test.go
Instead of opening a connection to all brokers immediately upon receiving their
information in metadata, wait until we are asked for them either via a call to
`Leader` or a call to `any`.
It seems simple enough (simpler than I was expecting actually) but I'm a bit wary, since it changes the internal semantics so much. Strong opinions and careful review please.
@Shopify/kafka
=> Lazily connect to brokers in the client

consumer.go, producer.go
It is now only called from one place in the client. This looks simple but is
actually super-subtle, and depends on lazy broker connections (PR #309).
disconnectBroker does a whole bunch of different things:
- calls `Close` on the broker connection
- adds the address to the internal `deadBrokerAddrs` map even if the broker is
not a seed, which I think is wrong, since resurrectDeadBrokers will use it to
repopulate the seedBrokerAddrs list
- rotates seedBrokers (if the broker was a seed broker)
- removes it from the brokers map (otherwise)
In the producer and consumer where we used to call disconnectBroker:
- We now call `Close` directly on the broker.
- The broker we are dealing with is not a seed broker, so the seedBrokers do not
need rotating, and I don't think it's a problem that it no …
=> Remove external calls to disconnectBroker

client.go, consumer.go, producer.go
1 method to rule them all. @Shopify/kafka
=> Consilidate refresh metadata methods into one

client.go, client_test.go
- We don't need it internally.
- The data can be stale on the broker we are requesting this from; you should ask Zookeeper instead.
@Shopify/kafka
=> Drop ReplicasInSync from Client interface

client.go, client_test.go
- Remove the stale comment about how it sucks and shouldn't be public (it
isn't).
- Remove a useless bit of logging.
- Move the `broker.Close()` call up to the caller, and make it synchronous now
that it's not inside the lock.
- Remove a useless call to it inside tests.
- Add a comment explaining the next thing that should happen in order for it to
go away completely.
=> Cleanup disconnectBroker a bit

consumer_test.go
Since it now owns the client, we leave goroutines hanging around if we don't.
=> Close the consumer master in tests

async_producer.go, async_producer_test.go, errors.go, functional_test.go, mocks/async_producer.go, mocks/async_producer_test.go, partitioner.go, partitioner_test.go, sarama.go, sync_producer.go
Before we call a 1.0 on the API, I'd like to propose 3 final API changes for the Producer. I'm not 100% sure about any of these, but I would like to bring them up before it is too late.
1. **`Producer` -> `AsyncProducer`**: This is mostly to make it more clear that we have 2 different APIs available, and force people to make a decision. Right now, many people will use the async producer because it is called producer, even though it is more complicated to use. So I rather let people decide what suits their use case best. If we have to pick a default, I'd use the sync producer because it's easier to get started with.
2. **`Input() <- msg` -> `EnqueueMessage(msg)`**: This is more in line with the `SyncProducer`. Also several people have indicated that the API uses too many channels. The main …
=> Async Producer API changes

async_producer_test.go, mocks/sync_producer.go, mocks/sync_producer_test.go, sync_producer.go, sync_producer_test.go
Rationale:
- This is in line with the AsyncProducer.
- This makes it easier to switch between SyncProducer and AsyncProducer if the need arises.
- This allows you to use to `ManualPartioner`, because now you can set the Partition field.
@Shopify/kafka Last API change I promise :)
=> SyncProducer’s SendMessage accepts a sarama.ProducerMessage

async_producer.go, partitioner.go, partitioner_test.go
This permits custom constructors that return different types of partitioners for
different topics.
Not 100% sure this is necessary/useful, but I figured I'd throw it in the ring before 1.0.
@Shopify/kafka
=> Pass the topic to the partitioner constructor

CHANGELOG.md, async_producer.go, async_producer_test.go
In certain unusual circumstances, the producer could have added new references
to a flusher that was shutting down, preventing it from shutting down and
causing it to try to produce on a network connection that was already closed.
Track "current" and "active" flushers separately - remove flushers from the
"current" set immediately when they begin shutdown so that nothing else tries to
take a reference, but leave them in "active" so that they can be cleaned up
properly when their reference count hits 0.
Add a test which fails without this fix in place.
@Shopify/kafka
=> producer: bugfix for broker flushers getting stuck

Makefile
This wasn't failing CI, but it was effectively not running the expected step so misformatted code might have snuck in accidentally.
@Shopify/kafka
=> Fix go fmt makefile target

CHANGELOG.md, async_producer.go, async_producer_test.go
In circumstances where Flush.Messages and/or Flush.Bytes were set but
Flush.Frequency was not, the producer's aggregator could get stuck on a retry
because a metadata-only chaser message would not be enough on its own to trigger
a flush, and so it would sit in limbo forever.
Always trigger a flush in the aggregator when the message is a chaser. This has
the additional benefit of reducing retry latency when Flush.Frequency *is* set.
Add a test for this case.
@Shopify/kafka
=> producer: bugfix for aggregators getting stuck

CHANGELOG.md, consumer.go, consumer_test.go
Very similar to #367 (on the producer): the consumer could have added new
references to a brokerConsumer that was shutting down, leading it to spin with
an error unnecessarily.
Add a test for this case.
@Shopify/kafka
=> consumer: bugfix for broker workers getting stuck

tools/kafka-console-producer/.gitignore, tools/kafka-console-producer/README.md, tools/kafka-console-producer/kafka-console-producer.go
Nice as an example, and could be nice for shell scripting without the need of installing the JVM to use the one that ships with Kafka. E.g. this could be nice to ship a Kafka event on a deploy of an application.
@Shopify/kafka /cc @graemej
=> Add a kaka-console-producer application

CHANGELOG.md, async_producer.go
This prevents repeatedly broken topics (e.g. ones that don't even exist) from
choking throughput for other topics.
No tests because:
- the breaker itself is well-tested in https://github.com/eapache/go-resiliency/blob/master/breaker/breaker_test.go
- the change itself is stupidly simple
- I'm sick of writing complex producer tests
=> producer: wrap partitioning in a circuit-breaker

CHANGELOG.md, client.go, client_test.go, functional_test.go, metadata_response.go, sync_producer_test.go, vagrant/server.properties
If we set the partition cache, we end up return an empty list later on, which ends up causing a weird error message later on.
@Shopify/kafka for review
=> Do not use partition cache for unknown topics

client.go, client_test.go, config.go, functional_test.go
Now that some errors (e.g. UnknownTopicOrParition) set *both* a retry flag and
an error, we should handle retries first. This is sort-of non-idiomatic in that
`updateMetadata` now returns a non-nil error with a "valid" result, but I think
that's OK.
@Shopify/kafka follow-up to #372
=> client: given both retries and errors, prefer retries

README.md, tools/README.md, tools/kafka-console-partitionconsumer/.gitignore, tools/kafka-console-partitionconsumer/README.md, tools/kafka-console-partitionconsumer/kafka-console-partitionconsumer.go
A simple command line tool to consume a single partition of a topic on your Kafka cluster.
@Shopify/kafka
=> Add kafka-console-partitionconsumer tool

client.go, client_test.go, utils.go
Create all the Broker objects themselves right up front rather than storing the
addresses. Don't eagerly open the seed connection in the constructor, we open it
lazily in `any()` already. Never add non-seed brokers to the dead set.
Substantially simplify `resurrectDeadBrokers`. Don't try and close a broker that
isn't even connected.
The good bits as extracted from #380. Fixes #375.
@Shopify/kafka
=> Simplify how we manage seed brokers

consumer.go
=> Add better logs to the consumer

consumer.go
It didn't actually use the brokerConsumer at all anymore, so it makes more sense
here.
@Shopify/kafka
=> Put `handleResponse` method on partitionConsumer

async_producer.go
Previously the timer would tick every Flush.Frequency regardless of if a message
was actually queued. This meant that if no message arrived for Flush.Frequency
then the next message would be sent immediately, which is unexpected if not
*exactly* wrong.
With this change the timer is only started when the first message arrives, and
is cleared when a flush occurs. This should result in slightly better batching
for low-volume topics at the result of slightly higher latency (although the
delay will still never be more than Flush.Frequency).
@Shopify/kafka
=> producer: make Flush.Frequency behaviour better

offset_commit_request.go, offset_commit_request_test.go
Apparently the kafka protocol spec has been inconsistent for a while,
documenting v1 of this message but claiming it was still v0. Jun finally updated
it, so now we can properly implement *both* versions correctly.
@Shopify/kafka
=> Fix OffsetCommitRequest

vagrant/boot_cluster.sh, vagrant/create_topics.sh, vagrant/run_toxiproxy.sh
Hopefully this fixes the heisenbug where we try to set up the topics before the
cluster has actually booted.
Fixes #399 and shaves a good 20 seconds off of CI.
@Shopify/kafka
=> Instead of sleeping, poll for the socket to be ready

offset_commit_request.go, offset_commit_request_test.go, offset_fetch_request.go
This should bring us up to date.
Somebody should verify against https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-OffsetCommitRequest
=> The wiki of the offset API has been updated again

Vagrantfile
@Shopify/kafka otherwise non-vmware users get a useless 512MB by default.
=> Increase memory with vagrant virtualbox

async_producer.go
The old version just used a simple slice as a queue, using append and slice[1:].
This had correct (amortized O(1)) running time, but did not behave well with the
garbage collector. In particular:
- elements removed from the slice were still pointed to by the underlying array,
preventing them from being collected until the array was resized
- the array would only be resized when its current capacity was "full", even if
it had a substantial amount of free space it was wasting
Switch instead to my queue implementation (which I wrote a while ago to solve
these exact problems somewhere else). It uses a ringbuffer that is guaranteed to
stay with a factor of 2 size of the actual number of messages stored, it
generates a lot less garbage when the input and output rates are about the same,
and it …
=> Improve memory of producer retry queue

.travis.yml, functional_test.go, vagrant/create_topics.sh, vagrant/install_cluster.sh, vagrant/server.properties
@Shopify/kafka so I thought after the last one I was ready to actually write a test, but apparently not :)
This is a grab bag of changes to CI configuration in preparation for toxiproxy tests:
- Always run CI with `DEBUG=true`, it's just useful and it doesn't cost us
anything.
- Initialize the logger first thing in `init()` when `DEBUG=true` so it can be used
by other parts of the init.
- Seed the random number generator (and permit overriding the seed via an
environment variable), this will be used for toxiproxy tests.
- Bump toxiproxy to 1.0.1 to fix a bug resetting proxies.
- Create a topic with 32 partitions for testing multiple partitions per broker.
- Lower the zookeeper timeouts so that we don't have to wait forever for a node
to die when we use toxiproxy to kill its zookeeper …
=> More test prep for toxiproxy

client.go, client_test.go
Which is: refresh the metadata and retry once, in case e.g. our connection or
metadata is stale.
Also add a test for it.
@Shopify/kafka
=> Add retry logic to GetOffset() just like Leader()

consumer_metadata_response.go, consumer_metadata_response_test.go
The three deprecated fields can go away whenever we decide to do 2.0.
=> Automatically construct a broker from the ConsumerMetadataResponse

client.go, client_test.go, consumer_metadata_response.go, functional_client_test.go
This is the first step towards consumer group offset management, and later full consumer group management in Kafka 0.8.3.
Careful review of the 2 locks would be appreciated. Do we need to locks or can be just use the single lock for everything?
Extracted from #379.
@Shopify/kafka
=> Add Client.Coordinator() to retrieve the coordinating broker for a consumer group

client.go
We have this in place for most of the methods on Client, but not all of them.
@Shopify/kafka
=> Consistently return ErrClosedClient when calling an exported function on a closed client

offset_commit_request_test.go
Previously, running the offset commit request test caused these warnings:
```
[sarama] 2015/04/11 08:15:53 Non-zero ConsumerGroupGeneration specified for OffsetCommitRequest v0, it will be ignored
[sarama] 2015/04/11 08:15:53 Non-empty ConsumerID specified for OffsetCommitRequest v0, it will be ignored
[sarama] 2015/04/11 08:15:53 Non-zero RetentionTime specified for OffsetCommitRequest version <2, it will be ignored
[sarama] 2015/04/11 08:15:53 Non-zero timestamp specified for OffsetCommitRequest not v1, it will be ignored
[sarama] 2015/04/11 08:15:53 Non-zero ConsumerGroupGeneration specified for OffsetCommitRequest v0, it will be ignored
[sarama] 2015/04/11 08:15:53 Non-empty ConsumerID specified for OffsetCommitRequest v0, it will be ignored
[sarama] 2015/04/11 08:15:53 Non-zero …
```
=> Refactor offset commit request tests so they don't cause warnings

client.go, client_test.go
Otherwise, in the rare case where a background metadata refresh coincided
exactly with a call to `Client.Close()` there was a race where we might have
potentially tried to write to a nil map. Also add a test for this.
Fixes #422.
@Shopify/kafka @epsniff
=> client: stop the background thread before closing

consumer.go, consumer_test.go, functional_consumer_test.go, mockbroker_test.go
When calling ConsumePartition, always check whether the offset is within the offset range. This means we now have to do two OffsetRequests for every ConsumePartition call, even if the offset is provided. The good news is that the method will immediately return an error and never start a goroutine, instead of starting the goroutine and returning an error in the Errors() channel which you can easily ignore.
This replaces #378. It now uses two OffsetRequests instead of changing OffsetRequests to allow obtaiing multiple offsets for a single partition.
=> Consumer: check offset before returning ConsumePartition.

consumer.go, consumer_test.go
The old behaviour was to redispatch it (so it would go to another broker if
necessary) and then retry with the same offset, which was a rather useless thing
to do unless the offset had somehow ended up slightly ahead of the available
messages (which is unlikely - it is far more likely to fall behind).
Instead, simply shut down the PartitionConsumer so the user gets an error (if
they're subscribed) and their messages channel closes. They then get to choose
whether to give up and switch to a different offset, yell for a human, or
whatever.
@Shopify/kafka make sense?
=> consumer: shut down on OffsetOutOfRange

prep_encoder.go, real_decoder.go, real_encoder.go
My recent playing with benchmarks led me down the slippery slop into profiling,
where I found this oddity. Calling `binary.Size()` actually involves reflection
on the argument which is expensive (of course). There was really no reason not
to hardcode these other than vague hand-waving towards portability (really).
Saves us about 2.5% of profiled time in the producer benchmarks.
@Shopify/kafka
=> Hardcode integer sizes

async_producer.go
- in leaderDispatcher, make the topic/partition part of the initial log slug for
convenience and consistency
- don't log on every switch from normal to flushing in the loop, just the first,
since 99% of the time we burn right through them all and we only need one line
to indicate that, not 5 or 10
- similarly, don't log on every switch from flushing to normal, just do so if
the highWatermark is 0 and it breaks the loop - in combination with the
previous change we end up with just an entry and exit log for the loop, rather
than two logs per iteration
- in messageAggregator, make the broker ID part of the slug (it wasn't even
logged before)
@Shopify/kafka
=> Producer logging tweaks

consumer.go, mocks/consumer.go, mocks/consumer_test.go
This will allow you to implement most consumer use cases without a `Client` instance, and make them easier to test by adding them to the Consumer mock and allowing to stub values.
As discussed in #430, fixes #366. @Shopify/kafka
=> Add Topics() and Partitions() to Consumer interface, and mock Consumer implementation.

consumer.go, consumer_test.go, functional_consumer_test.go, mocks/consumer.go
Expose high water marker offset in consumer for lag monitoring purposes.
@Shopify/kafka
=> High water mark offset support to the consumer

async_producer.go, async_producer_test.go
@Shopify/kafka fixes #419.
Rather than use the old complicated system of reference-counting flags to shutdown cleanly, do the much simpler thing: keep a `sync.WaitGroup` counting the number of messages "in flight" (aka owned by the producer). When shutdown is requested, spawn a goroutine that waits for this counter to hit 0, then closes everything in one go.
We add messages to the in-flight set in the `topicDispatcher` (only new messages with retries==0 though). We remove messages from the in-flight set in `returnError` and `returnSuccesses`; even if the `Producer.Return.*` values are false they are still guaranteed to see every message.
We also add/remove chaser messages in `leaderDispatcher`.
~~This still needs tests.~~
I'm not sure what performance impact the waitgroup will have. An …
=> Retry messages on shutdown

async_producer.go
Otherwise a client re-using message structs would run into weird problems.
@Shopify/kafka just occurred to me, we don't reuse messages ourself (and I suspect most people do not) but we already clear flags. Now we do it in one consistent place so this sort of inconsistency doesn't happen again.
=> Clear producer message retry field on success

consumer.go, consumer_test.go
Feed consumer responses to the user asynchronously
Give each PartitionConsumer a goroutine whose job is to feed the user, and have
the brokerConsumer feed each partition with the response, then wait for acks.
This makes the consumer much more resilient to weird user consumption ordering,
as the old "one partition at a time" logic was very unforgiving.
Fixes #325 
Replaces #398 
@Shopify/kafka careful :eyes: on this please
=> Consumer async partitions

consumer.go
We've gotten a number of people confused by this "missing" functionality.
=> Document consumergroup repo location

tools/kafka-console-topicconsumer/.gitignore, tools/kafka-console-topicconsumer/README.md, tools/kafka-console-topicconsumer/kafka-console-topicconsumer.go
It will consume all partitions for a given topic and write the messages to STDOUT.
@Shopify/kafka
=> Add a simple topic consumer tool

client.go, client_test.go
I stole this idea from the Zookeeper library because is such a simple yet powerful way to load balance the metadata requests in the cluster over the different brokers. After the initial seed broker shuffle, seed broker handling is deterministic, and will work the exact same way before.
The way I fixed the "resurrect dead brokers" test is not great, but that is primarily because of the limitation of the mock broker implementation. If you have ideas to do this in a better way, tell me :)
@Shopify/kafka
=> Shuffle seed brokers so we don't always connect to the first one provided

snappy.go
Profiling the Kafka consumers at VividCortex showed me that a large portion of the allocated memory in our code comes from sarama.snappyDecode. This change reduces the average number of allocated bytes by pre-allocating the destination slice, and by re-using the chunk slice for cases that make multiple calls to snappy.Decode. Doing so should reduce GC pressure by a modest amount.
=> Amortize allocations in snappyDecode

snappy.go
Also organize imports according to the go-import convention used everywhere else
already.
=> trivial: replace x=x+y with x+=y

async_producer.go
@eapache This is not the cause of #449, but fixes another a potential issue when using the waitgroup.
=> Ensure we always have called Add() on the inflight counter before we Wait() for it

async_producer.go
Don't increment and immediately decrement the wait group on a message which we
just return with ErrShuttingDown. Otherwise:
```
prod.AsyncClose() // starts prod.shutdown() goroutine
prod.Input() <- msg
```
1. shutdown() goroutine calls Wait()
2. while in the call to Wait(), Go switches contexts
3. the message is sent on Input(), is received, and causes the wait counter to
increment from 0 while being waited on
Where the WaitGroup docs say "calls with a positive delta that occur when the
counter is zero must happen before a Wait".
@Shopify/kafka @wvanbergen hopefully this explanation makes sense, it was the second issue I came up with from #450.
=> Fix another hypothetical wait group issue

client.go
Mention requirement of kafka 0.8.2. /cc @eapache and @zaynetro
=> Update godoc for Client.Coordinator and Client.RefreshCoordinator

sarama.go
Hopefully sufficient to fix #458.
@4578395263256 does this read better?
=> Update and simplify doc for MaxResponseSize

async_producer.go
Otherwise there is a case where the retried messages can have their
newly-selected broker closed out from under them if the remainder of this
goroutine gets heavily delayed by the scheduler.
I believe this may be the cause of the flaky failure in
TestAsyncProducerBrokerBounce (see e.g.
https://travis-ci.org/Shopify/sarama/jobs/66053366)
@Shopify/kafka
=> Don't retry messages until the broker is closed

vagrant/boot_cluster.sh, vagrant/create_topics.sh, vagrant/setup_services.sh
This should improve an occasional case where functional tests would fail
because a service wasn't ready yet.
=> Tweak where and how we wait for kafka to boot

async_producer.go, async_producer_test.go
It shouldn't wrap the entirety of `assignPartition`, since that also protects
things like the call to actually choose the partition. The only thing it is
supposed to protect is the call to get the list of partitions, since that is
what can block.
This may or may not fix (or be the right way to fix) #466.
@ssahukar @Shopify/kafka
=> Shrink the scope of the partition circuit-breaker

async_producer.go
- rename topicDispatcher to dispatcher
- make a topicProducer struct to handle the old partitionDispatcher
- make a partitionProducer struct to handle the old leaderDispatcher
- move and rename methods for a much more readable structure
Part 1 of #300.
There shouldn't be any functional changes. Thoughts @Shopify/kafka ?
=> Refactor producer goroutines somewhat

broker.go, consumer_metadata_request.go, consumer_metadata_request_test.go, encoder_decoder.go, fetch_request.go, fetch_request_test.go, metadata_request.go, metadata_request_test.go, offset_commit_request.go, offset_commit_request_test.go, offset_fetch_request.go, offset_fetch_request_test.go, offset_request.go, offset_request_test.go, produce_request.go, produce_request_test.go, request.go, request_test.go
This change makes every request-response pair processed by a mock broker visible in test logs. It helped me to understand the flow of the tests, so I figured it may be beneficial for other users too. It might seems like a lot of changes, but basically I just added `decode` function to every request.
=> Add decode method to request types

consumer.go
Fixes bug #475 
Should be correct in all cases, unlike #483.
@Shopify/kafka
=> Fix hypothetical consumer deadlock, attempt 2

async_producer_test.go, consumer_test.go, mockbroker_test.go
EDIT: This PR introduces `SetHandler` method to the mock broker that allows setting a function that can generate responses based on actual incoming requests. That allows writing tests that account for concurrent execution non-determinism. By default a handler function that returns responses read from the expectations channel populated by the `Returns` method is used. Besides the broker can accept many connections now.
Old PR description:
Let me explain why I have made these changes first: The thing is that the current consumer implementation can block if a message channel of one of consumed partitions is not being drained. This logic does not play well with our use case, we cannot allow one partition consumer affect others, so we have reimplemented the consumer (our …
=> Enhance mock broker

broker.go, config.go, encoder_decoder.go, errors.go, length_field.go, message.go, prep_encoder.go, real_decoder.go, request.go, response_header.go
As pointed out by Willem (https://github.com/Shopify/sarama/pull/485#discussion_r35786611) we have a bunch of not-quite-idiomatic error formats. Fix up a bunch of obvious ones.
=> Cleanup error formatting

config.go, consumer.go, consumer_test.go
If a partitionConsumer fills up and is not being drained (or is taking a long time) remove its subscription until it can proceed again in order to not block other partitions which may still be making progress.
@Shopify/kafka @horkhe
=> Dont require all consumers drained

broker.go, config.go, examples/http_server/http_server.go
as mentioned in https://github.com/Shopify/sarama/issues/154 this has been rebased on current master and can be merged
=> Add configuration to support broker SSL

async_producer.go
Another chunk of #300. Once this lands the final step will be to break out the
existing massive `run()` methods into useful helper functions now that
parameter-passing isn't such a pain.
In theory no functional changes; just slightly nicer code and stricter typing
around channel direction.
@Shopify/kafka
=> Structure the aggregator and flusher goroutines

async_producer.go
=> Clean up the flusher via helper methods

async_producer.go, config.go
Also get rid of forceFlushThreshold it does not need its own function
@wvanbergen
=> Clean up aggregator via helper methods

mockresponses_test.go, produce_request.go
- implement a mockProduceResponse
- fix decoding of produceRequests (bless my foresight in making getSubset a
method on the packetDecoder)
- collapse three of the simpler existing producer tests into one as a
proof-of-concept
Heavily influenced by Maxim's recent work on the consumer tests.
@Shopify/kafka cc @horkhe
=> Improve async_producer tests and prep for more

offset_manager.go, offset_manager_test.go
This way, an OffsetManager that uses an external data store can properly clean up the resources it uses.
- Should we add `AsyncClose()` for consistency?
- I added a dummy implementation for the Kafka offset managers. Should be do something there now the function is present?
@eapache
=> Add Close() OffsetManager interface

config.go, functional_offset_manager_test.go, functional_test.go, offset_manager.go, offset_manager_test.go
This allows you to set the initial offset `Offset()` will return if no offset was committed yet for the partition. 
Right now, we depend on the implicit behaviour of the Kafka broker, which is returning -1. This patch makes the behaviour explicit, and allows you to change that to either `OffsetOldest` or OffsetNewest`.
I prefer using a config setting instead of an extra argument to ManagePartition, because this value will always be the same for every partition in a consumer.
@Shopify/kafka
=> Offset manager: make initial offset configurable

config.go, functional_offset_manager_test.go, functional_test.go, offset_manager.go, offset_manager_test.go
There are still some TODOs sprinkled throughout, but not all of them necessarily need to be fixed before we ship this (it's already pretty close to the minimum viable implementation). The only critical missing piece is implementing `AsyncClose` for the `PartitionOffsetManager`.
Regardless, it's at the state where it can be opened up for comments. This should completely supersede #379.
=> OffsetManager Implementation

.travis.yml
@wvanbergen noticed this in the CI logs:
```
$ eval "$(gimme 1.5.0)"
I don't have any idea what to do with '1.5.0'.
(using type 'auto')
$ gimme version
v0.2.3
$ go version
go version go1.4.1 linux/amd64
```
=> Gimme expects 1.5 not 1.5.0

config.go, offset_manager.go
=> A few minor offset-manager tweaks

broker.go, fetch_response.go
(https://github.com/dvyukov/go-fuzz)
- handle negative message-set sizes in FetchResponses
- handle IPv6 and/or malformed broker addresses
@Shopify/kafka
=> Fix two decoding bugs found by go-fuzz

fetch_response.go, produce_request.go, real_decoder.go
The fix in #523 did not cover all cases, as found by subsequent go-fuzz runs.
@wvanbergen
=> Centralize and unify getSubset error checking

crc32_field.go
Needs testing to ensure that this is actually faster (and is still correct), but may solve #255.
=> Use an optimized crc32 library which is faster

message.go
- Don't short-circuit return when inflating compressed messages. There are no
other fields left, but we should still check the wrapping message's CRC32.
- Do short-circuit return that CRC32 field, it's the last thing we do so there's
no need for a manual if-not-nil return.
@Shopify/kafka found while testing #527
=> Fix and simplify message decoding

offset_manager.go
Thanks to Maxim for pointing out that 0 doesn't mean now, it means unix epoch 0
(a long time ago).
Fixes #530.
@horkhe @Shopify/kafka
=> Fix offset-manager expiry timestamps to 'now'

consumer.go
I discovered a "send on closed channel" panic in the consumer while testing #527
which I was finally able to track down. If a partition takes a long time to
drain to the user, then the responseFeeder reclaims its ownership token from
the broker so that the broker doesn't block its other partitions. However, if
the user closes the PartitionConsumer (closing the dying channel) then the
brokerConsumer will unconditionally return the ownership token to the dispatcher
even if the responseFeeder is holding it. This results in two ownership tokens
for the same partition (one in the feeder, one in the dispatcher) which leads to
all sorts of subtle brokeness. It manifested in at least two different "send on
closed channel" backtraces depending on the exact timing, and possibly more.
To fix, move …
=> Fix consumer race panic on close

broker_test.go
go-vet recently added a rule for this it seems
cc @wvanbergen
=> Don't return from example functions

async_producer.go, client.go, config.go, consumer.go, offset_manager.go, partitioner.go, sync_producer.go
cc @wvanbergen 
closes #540 
The fact that the go docs explicitly say "Go has no line length limit" and then godoc.org enforces 80 characters anyways makes me sad :(
=> Wrap all godoc at 80 characters

async_producer.go, async_producer_test.go
Quick fix for #449, pending more thought and writing tests etc.
=> Correctly handle unencodable messages in the producer

async_producer.go
Minor oddity I noticed while working on the aggregator/flusher refactor; this
looks like vestigial code from some attempt at handling the weird size
requirements of compressed message batches, but since `msg.byteSize()`
*includes* `msg.Value.Length()` if appropriate, the entire first condition of
this `||` is superceded by the second.
@wvanbergen Saturday's not-so-scary PR :)
=> producer: simplify initial "too large" check

broker.go
When a broker gets an error trying to receive a response (either from the
network layer, or from failing to parse the minimal global header), it should
just abandon ship and die. Save that error and return it immediately for any
further requests we might have made.
- The vast majority of the time the connection is going to be hosed anyways, if
nothing else by being out-of-sync on correlation IDs (which we don't handle
and which doesn't seem particularly urgent).
- All of Sarama's built-in callers (producer/consumer/offset-manager)
immediately `Close` a broker when they receive one of these errors anyways, so
all this does is speed up that in the common case.
*If* one of these errors is recoverable, and *if* there is user-space code
somewhere which actually tries to recover in one of those …
=> Make dead brokers die harder

async_producer.go
First stand-alone chunk extracted from #544. This introduces and uses a
produceSet structure which takes care of collecting messages, rejecting ones
which don't encode, and turning the rest into a `ProduceRequest`.
This has several knock-on effects:
- we no longer nil out array entries, so nil checks in several places (e.g.
`returnErrors`) can be removed
- parseResponse gets re-indented since it loops over the partitions in the set
via a callback now rather than a pair of nested loops
- groupAndFilter is much simpler, a lot of its logic now lives in the produceSet
- the flusher has to use the set to return errors/successes/retries, rather than
`batch` which may now contain messages not in the eventual request
- keyCache and valueCache can be removed
@wvanbergen cc @kvs
=> Refactor the producer, part 1

async_producer.go, async_producer_test.go
Second stand-alone chunk extracted from #544, (first chunk: #549). This uses the
`produceSet` struct in the aggregator as well, and moves the `wouldOverflow` and
`readyToFlush` methods to methods on the `produceSet`.
Knock-on effects:
- now that we do per-partition size tracking in the aggregator we can do much
more precise overflow checking (see the compressed-message-batch-size-limit
case in `wouldOverflow` which has changed) which will be more efficient in
high-volume scenarios
- since the produceSet encodes immediately, messages which fail to encode are
now rejected from the aggregator and don't count towards batch size
- we still have to iterate the messages in the flusher in order to reject those
which need retrying due to the state machine; for simplicity I add them to a
second …
=> Refactor the producer, part 2

async_producer.go
@wvanbergen depends on #550, I'll rebase once that's merged.
This is the final step, it moves the request/response handling and all state into the "aggregator" (which is now named the `brokerProducer`). This makes what used to be the `flusher` really trivial, so it gets inlined into the constructor.
Most of the logic stays the same, the most confusing change is probably around forcing a blocking flush, because we now have to handle the case where we receive a response while we are waiting, and that changes our state (see the new `waitForSpace` method).
=> Producer refactor 3

mocks/consumer.go
The mock `PartitionConsumer` sent messages to an expectations channel
on calls to `YieldMessage` and `YieldError`. This led to race conditions
in tests if `pc.Messages` was called before the `handleExpectations`
goroutine added a message to the channel.
This PR sends message and errors to their respective channels
directly. The expectations channel & goroutine are removed
altogether, simplifying the code.
This resolves issue #553.
@eapache @wvanbergen
=> Send messages and errors directly in consumer mock

mocks/consumer.go
Simple PR to restore `sync.Mutex` lock/unlock calls in `YieldMessage`.
@eapache @wvanbergen
=> Add lock/unlock to YieldMessage

mocks/consumer.go
It doesn't matter since we're inside a mutex anyways, but this is cleaner.
cc @wvanbergen @aaronkavlie-wf
=> Collapse two sync.atomic calls

consumer_test.go, mockbroker_test.go, mockresponses_test.go
This PR introduces `mockSequence` response builder that is created of a sequence of (mock)responses and everytime when `MockBroker` calls its `For` method it returns the next response from the sequence. When the last element in the sequence is reached it is returned for every subsequent call of the `For` method.
This change allows to define `MockBrocker` handler with `SetHandlerByMap` exclusively, that makes tests a bit shorter and easier to read.
=> Introduce mockSequence and further simplify tests

.travis.yml, Vagrantfile, vagrant/provision.sh
This adds java 7 which will be necessary for kafka 0.9, but drops support for
non-virtualbox hosts.
Also bump kafka 0.8.2.1 to 0.8.2.2 for trivial bug-fixes.
@wvanbergen @kvs
=> Upgrade vagrant from precise to trusty

.travis.yml, functional_offset_manager_test.go, functional_test.go, vagrant/provision.sh, vagrant/server.properties
Fix one new constraint on the broker ID which must now be small unless you
configure otherwise. Fortunately it seems older versions just ignore unrecognized config stanzas.
P.S. I believe this is because 0.9 now optionally auto-generates broker IDs for you within a given range? At some point we need to find/read a good changelog.
=> Add kafka 0.9

async_producer.go
Introduce a `syn` flag (a la TCP) and send a syn message from partitionProducer
to brokerProducer on setup. This lets brokerProducer know exactly which
partitions it should handle at any time, even if they haven't sent an actual
message yet.
For symmetry, rename `chaser` to `fin`, since it is already the last message
from a partitionProducer to a brokerProducer, and also the last from
brokerProducer to partitionProducer. Tweak logging to be a little more explicit around the brokerPoducer state.
First piece of a refactor my subconscious has been working on without me.
@wvanbergen
=> producer: explicitly register partitions

functional_offset_manager_test.go, offset_manager.go
[Here](https://github.com/apache/kafka/blob/0.9.0/core/src/main/scala/kafka/coordinator/GroupCoordinator.scala#L402-L405) is why the solution works.
=> Fix offset_manager for Kafka 0.9.0.0

offset_commit_request.go, offset_manager.go
In #585 I made a mistake declaring `groupGenerationUndefined` as module internal. It is a part of protocol and therefore should be public. It also belongs to **offset_commit_request.go** file along with `ReceiveTime` constant.
=> Publish GroupGenerationUndefined constant

broker.go, utils.go
Reduces the number of read syscalls issued by short, sequential reads on the broker's net.Conn. A similar technique is used in the [`net/http`](https://github.com/golang/go/blob/master/src/net/http/server.go#L482) package.
=> Add a buffer around the broker's net.Conn for reads

async_producer.go
Work around the const/label conflict bug in go16beta1 by replacing a label & goto with a method.
golang/go#13684
=> replace label & goto with a method

async_producer.go
Add InvalidMessage, and re-order the others to match their definition order.
=> Upstream has spoken on retriable errors

consumer_group_members_test.go
Don't do encode/decode testing with multi-value maps, the order is not
predictable.
cc @wvanbergen
=> Fix flaky test

.travis.yml, CHANGELOG.md, README.md
- Declare 0.9 supported in the readme
- Stop testing 0.8.1 in CI, it's outside our 2+2 policy now
- Rejig changelog to make "0.9 support" the primary item for the next release
- Bump the tested go minor version because why not
@wvanbergen did you have anything else you wanted in 1.8? If this looks good I'll merge it and release 1.8 on Monday.
=> Prep docs for Sarama 1.8 supporting kafka 0.9

client.go
As pointed out in #603 this is generally inefficient and misleading.
@wvanbergen cc @kiro
=> Recommend not sharing clients by default

broker.go
I was doing an unrelated experiment with a config that generated a warning on
validation, and I ended up flooded with warnings because we now call `Open` on
every broker returned from the Client, and we were revalidating the config every
single time. One thing led to another and I made several other adjustments in
the same vein.
- Move the atomic `AlreadyConnected` check to before the config validation in
`Broker.Open`. Config validation is expensive and can log, no point in doing
it if we don't have to.
- Move all the `atomic.StoreInt32` calls to *after* any of their related log
messages. None of these were real problems, but it removes any possibility of
out-of-order log messages due to unusual race conditions.
- Remove the double-check for `AlreadyConnected` after we've taken the full …
=> Adjust broker locking order slightly

async_producer_test.go, broker_test.go, client_test.go, consumer_test.go, mockbroker.go, mockresponses.go, offset_manager_test.go, sync_producer_test.go
This is a very selfish PR, I am probably one of the very few people (if not the only one) who needs this, so if you think that it makes no sense for you then just close this PR immediately.
Basically I need MockBroker and Mock response types to be available outside of Sarama to reuse in our tests. I also wanted to move them to `saram/mock` package, but that would require making the [encoder](https://github.com/Shopify/sarama/blob/master/encoder_decoder.go#L12) type public that would collide with the existing public [Encoder](https://github.com/Shopify/sarama/blob/master/utils.go#L59) type. A solution to that would be to move all request/response marshaling/unmarshaling logic to a dedicated package e.g. `sarama/proto` or `sarama/protocol`, but that seemed to be too much to ask...
=> Make mock brokers and protocol packets available for outsider

mockbroker.go, mockresponses.go
This was a minor regression from #570. Fixes #626.
@lvdlvd @wvanbergen
=> Don't import `testing` in the main lib

client.go, consumer.go, offset_manager.go
Gwen posted to the spec a list of expected error codes for each
request/response. This adds handling for the listed codes for consumer, client,
and offset manager. Some errors (e.g. around group membership) have been ignored
because we don't implement the relevant feature yet anyways.
Possible errors for the producer are not yet listed in the spec.
@wvanbergen closes #596
=> Add additional error handling based on spec

config.go
It requires v2 of the OffsetCommitRequest which was only introduced in Kafka
0.9; trying to use it with earlier broker versions will fail.
From #650.
@wvanbergen @dimchansky
=> Doc that Offset.Retention requires kafka 0.9

offset_manager.go
Only v1 OffsetCommitRequest messages had the per-partition timestamp, so only
send it in that case and let it be 0 otherwise. The `encode` method was already
smart enough to ignore it and log a warning, so this basically just suppresses
the annoying log message.
@wvanbergen @dimchansky fixes the less interesting piece of #650.
=> Don't try to send partition timestamps in v2 OCRs

broker.go, config.go
Hi
This is a simple patch that adds support for SASL plain text authentication to Kafka brokers, if enabled. This feature is useful when people want to leverage hosted Kafka services such as IBM Bluemix's Message Hub service (Kafka 0.9 with SASL plain text authentication). By default, the authentication is disabled.
=> Add support for SASL plain text authentication

offset_manager.go
If `updateCommitted` ran between the `Unlock` call and the read from `clean`
then we might miss the transition message and hang. Instead, use a condition
value from the `sync` package which does the right thing.
@wvanbergen @hasnickl fixes #656 
Supersedes #657
=> Fix race condition on OffsetManager shutdown

sarama.go, sync_producer.go
Hopefully addresses #653.
@wvanbergen @uhoh-itsmaciek
=> Update a bunch of docs

client.go, config.go, config_test.go
Documentation states that `"sarama"` is the default ClientID but the empty string actually is used.
This is a not a problem for connecting to the brokers but it creates issues when settings policies against the tools binaries (e.g. `kafka-console-producer`) like:
```
bin/kafka-configs.sh  --zookeeper localhost:2181 --describe --entity-name ""  --entity-type clients
Error while executing topic command Path must not end with / character
java.lang.IllegalArgumentException: Path must not end with / character
at org.apache.zookeeper.common.PathUtils.validatePath(PathUtils.java:58)
at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1137)
at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1184)
at org.I0Itec.zkclient.ZkConnection.readData(ZkConnection.java:119)
at …
```
=> Forbid empty ClientID and use 'sarama' as default

message.go
Per https://kafka.apache.org/documentation.html#compaction messages with null
payloads are valid when using log compaction. Make this work for all messages,
not just uncompressed ones. Should fix #634.
@tcrayford @wvanbergen
=> Support nil compressed messages

config.go, utils.go, utils_test.go
This is unused currently, but will have a bunch of uses soon. Based on a
simplified version of https://github.com/Shopify/sarama/pull/655 by Mohammad
Rafay Aleem.
Addresses the major chunk of #617.
=> Support configuring target kafka version

async_producer.go, broker.go, produce_request.go, produce_response.go, produce_set.go
- Support v0/v1/v2 of Produce requests in the protocol layer.
- Enforce the correct message version for Kafka version at the Broker.
- Use v2 messages in the producer if the Kafka version supports it, and pass the
resulting timestamp back to the user in the ProducerMessage.
Addresses #642
@makkes @wvanbergen
=> Support and provide producer message timestamps

mocks/sync_producer.go, sync_producer.go, sync_producer_test.go
Provide a `SyncProducer.SendMessages` method which produces a given *batch* of
messages (though does not guarantee they will end up in a single batch on the
wire).
Fixes #674 
@tadbook @JasonRosenberg cc @wvanbergen
=> SyncProducer batch support

async_producer.go, produce_response.go
Move it to the protocol layer for stronger typing, and parse it properly (it is
in milliseconds, not seconds).
Thanks again to @kchaliki.
=> Fix parsing of producer timestamp

consumer.go, fetch_request.go, fetch_response.go, message.go, produce_response.go
@makkes this is untested but should address #680. The protocol spec is a bit ambiguous on points.
=> Plumb through v0.10 support for consumer/fetch

client.go
err goes out of scope at the end of the if-block
Bug found with ineffassign.
=> client: fix returning the wrong error

errors.go, real_decoder.go
I saw that the dynamic creation of errors was contributing a lot to the heap profile (see below)
I haven't tested extensively yet, but this should fix it
```
(pprof) top30 -cum
62951786 of 63347642 total (99.38%)
Dropped 41 nodes (cum <= 316738)
flat  flat%   sum%        cum   cum%
57502851 90.77% 90.77%   63347642   100%  [metric_tank]
0     0% 90.77%   35258445 55.66%  github.com/Shopify/sarama.(*realDecoder).getInt64Array
3922373  6.19% 96.97%    3922373  6.19%  regexp/syntax.(*compiler).quest
680349  1.07% 98.04%     680349  1.07%  crypto/x509/pkix.(*Name).FillFromRDNSequence
444790   0.7% 98.74%     504731   0.8%  crypto/x509/pkix.Name.ToRDNSequence
0     0% 98.74%     491660  0.78%  github.com/Shopify/sarama.(*OffsetFetchRequest).decode
401423  0.63% 99.38%     401423  0.63% …
```
=> pre-allocate decoding errors

consumer.go
In certain cases the `subscriptionManager` and drain loop in `abort` could start
spinning against each other for a non-trivial amount of time, if e.g. a
partition was suspended waiting for the user to consume its buffer. The tight
loop has always been there, it has just tended to be trivially short in normal
operation so nobody noticed.
This is the same issue that the `wait` channel was introduced to solve for the
`subscriptionConsumer` so solve it the same way.
Fixes #692 cc @josselin-c
=> Consumer: fix possible tight loop

produce_set.go
This allows producing messages with correct CreateTime timestamps in 0.10
=> Passing ProducerMessage.Timestamp to broker when producing to v0.10

async_producer.go
Thank you for your response to #697. It makes much more sense to handle -1 timestamp in produce_response.go.
It would be nice to let ProducerMessage keep its timestamp, not overridden after being sent, so I made this pull request. Look forward to knowing your opinion.
=> Don't propagate zero timestamp to ProducerMessage

_layouts/index.html
If you access `https://shopify.github.io/sarama/` (note HTTPS), the page loads the icon via HTTP, breaking the seal. This PR makes it so it'll pick either HTTP or HTTPS, like the javascripts files at the bottom of the page.
=> Update logo to not use HTTP, but also allows HTTPS

partitioner.go, partitioner_test.go
Issue: I have found that for some Key, the Partition function of HashPartitioner return negative value. After I investigate the issue, I have found that if the fnv's Sum32 function returns 2147483648, which is -2147483648 in int32 and the negative of this will still be -2147483648 causing the negative result returned.
Reproduce: this issue can be reproduced by using "1468509572224" as message's key.
Change: 
- partitioner.go: Apply modulo before checking the negative value to ensure the positive result.
- partitioner_test.go: Add TestHashPartitionerMinInt32 to test the error case.
Please feel free to suggest the better way to fix this issue.
=> Fix HashPartitioner's negative result

CHANGELOG.md, offset_manager.go
We should retry them still (if topic auto-create is enabled that is enough) but
we should also tell the user since if auto-create is *off* we otherwise just
appear to hang.
Fixes #706.
@Kane-Sendgrid
=> Offset Manager: report unknown topic errors

CHANGELOG.md, consumer.go
Rather than allocating a new timer with `time.After` on every message we
consume, allocate one for the `responseFeeder` and just keep resetting it.
Thanks to @Tevic for suggesting this approach.
Fixes #707 cc @Dieterbe.
=> Consumer: reduce timer allocations

CHANGELOG.md, functional_offset_manager_test.go, offset_manager.go, offset_manager_test.go
Upstream requires you mark last-consumed+1 and then returns that value directly.
We were requiring you mark last-consumed and then adding one to the returned
value.
Match upstream's behaviour so that our offset tracking is interoperable.
Fixes #705.
@Kane-Sendgrid
=> OffsetManager: match upstream mark/next behaviour

_layouts/index.html
The current download link in gh-pages is for downloading the zip of gh-pages branch, which should not be intended.
=> Fix download link in gh-pages

consumer.go
Checking Reset()'s active return value is racy according to [Golang docs](https://golang.org/pkg/time/#Timer.Reset). 
>Note that it is not possible to use Reset's return value correctly, as there is a race condition between draining the channel and the new timer expiring. Reset should always be used in concert with Stop, as described above. The return value exists to preserve compatibility with existing programs.
Docs advice to call Stop in order to reuse a timer. Should fix #732.
=> Fix Racy call to Reset in feederLoop

consumer.go
Sorry for my earlier sloppy PR, I didn't catch this error until it was running in prod for some time.
In the old code, if the timer does indeed timeout, we read the value off the channel, restart the loop, and *end up trying to read the value off the channel again*, which causes a deadlock.
This PR adds a flag to ensure we don't do that.
=> Deadlock: Don't read from the timer channel if it already expired

consumer.go
New message format does something weird with these. See
https://cwiki.apache.org/confluence/display/KAFKA/KIP-31+-+Move+to+relative+offsets+in+compressed+message+sets
Fixes #720. Supercedes #721. Thanks to @dynamix for the first draft of the fix.
@dynamix @Dieterbe could you verify this fix works correctly?
cc @wvanbergen
=> Consumer: handle compressed relative offsets

broker.go, broker_test.go, config.go, config_test.go, functional_producer_test.go, metrics.go, metrics_test.go, mockbroker.go, request.go, request_test.go, sarama.go, tools/kafka-console-producer/kafka-console-producer.go
- add `MetricRegistry` configuration parameter that defaults to `metrics.DefaultRegistry`
- provide the following metrics:
- `incoming-byte-rate` meter (global and per registered broker)
- `request-rate` meter (global and per registered broker)
- `request-size` histogram (global and per registered broker)
- `outgoing-byte-rate` meter (global and per registered broker)
- `response-rate meter` (global and per registered broker)
- `response-size histogram` (global and per registered broker)
- add `metrics` flag to `kafka-console-producer` to output metrics
- add bytes read to `decodeRequest`
- count socket bytes read and written in `MockBroker` for unit testing
- add unit tests and example
- functional tests in `functional_producer_test`
- documentation of metrics in main package
Related …
=> Expose broker metrics with go-metrics

broker_test.go, config.go, config_test.go, functional_producer_test.go, sarama.go
- use a new dedicated registry per config instead of using the default global registry provided by go-metrics
- update documentation and unit tests
=> Use a local registry for metrics

produce_set.go, produce_set_test.go
The wrapper message has to use the "new" format if the compressed messages use it as well.
This will fix #757 #758
=> Fix compression timestamps

.travis.yml, utils.go
Add go 1.7 to CI, bump 1.6 CI point release, bump kafka 0.10 CI point version,
add kafka 0.10.0.1 to the pre-defined version set.
=> Bump some versions

describe_groups_response.go
The code did already exists in sync_group_response.go, but added them also in describe_groups_response.go.
Now you can read the MemberAssignment and MemberMetadata also (before it was raw bytes, and not that easy to get the actual structs)
=> add missing metadata and assignment methods in describegroups

Vagrantfile, vagrant/kafka.conf, vagrant/zookeeper.conf
When I am running the tests, I sometimes get out of memory errors from the Java processes running in the Vagrant VM:
```shell
vagrant@vagrant-ubuntu-trusty-64:~$ sudo tail -n 10 /var/log/upstart/kafka-909{2,5}.log 
==> /var/log/upstart/kafka-9092.log <==
[2016-10-25 21:14:16,050] INFO Client session timed out, have not heard from server in 2989ms for sessionid 0x257fdae91d40000, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2016-10-25 21:14:18,800] INFO zookeeper state changed (Disconnected) (org.I0Itec.zkclient.ZkClient)
[2016-10-25 21:14:23,999] INFO Opening socket connection to server localhost/127.0.0.1:2182. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2016-10-25 21:14:24,220] INFO Socket …
```
=> Use sensible heap size for Java processes in Vagrant

functional_client_test.go
When working on #771, the tests failed one time with:
```
=== RUN   TestFuncClientCoordinator
--- FAIL: TestFuncClientCoordinator (1.60s)
functional_client_test.go:81: kafka server: Offset's topic has not yet been created.
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8666d]
goroutine 1223 [running]:
panic(0x37c3e0, 0xc4200120c0)
/usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc4209a6180)
/usr/local/Cellar/go/1.7/libexec/src/testing/testing.go:579 +0x25d
panic(0x37c3e0, 0xc4200120c0)
/usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:458 +0x243 …
```
=> Stop test if client.Coordinator fails somehow

broker.go, consumer_group_members_test.go, encoder_decoder.go, functional_producer_test.go, join_group_request.go, message.go, metrics.go, metrics_test.go, mockbroker.go, packet_encoder.go, prep_encoder.go, produce_request.go, produce_set.go, real_encoder.go, request_test.go, sarama.go, sync_group_request.go
- provide the following metrics:
- `batch-size` histogram (global and per topic)
- `record-send-rate` meter (global and per topic)
- `records-per-request` histogram (global and per topic)
- `compression-rate` histogram (global and per topic)
- add `metrics.Registry` parameter to the encode function
- provide underlying `MessageSet` when encoding fake compressed "message"
- use `len(msg.Set.Messages)` for counting records
- use `payloadSize` property in `Message` for knowing the size of the compressed payload
- expose the configured metric registry in `ProduceRequest`
- expose current offset in `packetEncoder` for batch size metric
- expose real encoder flag in `packetEncoder` for recording metrics only once
- record metrics in `produce_request.go`
- add unit tests and functional tests
- …
=> Expose producer metrics with go-metrics

broker.go, functional_producer_test.go, sarama.go
The Java client exposes two metrics about request latency (`request-latency-avg` as the average request latency in ms and `request-latency-max` as the maximum request latency in ms).
This metric is extremely valuable when optimizing the communication between a remote producer and a Kafka cluster through TCP tuning, typically when the socket buffers are too small on either side to reach the bandwidth-delay product of the connection.
Code change:
- new `request-latency-in-ms` histogram metric (global and per registered broker)
- addng 10ms latency to brokers in producer functional tests for validation
- updating documentation
=> Expose request latency metric

config.go, config_test.go, message.go, message_test.go
This patch may cause issues with kafka < 0.10.0 as it doesn't handle "broken" framing.
It should thus only be used with 0.10+.
=> Add lz4 compression

async_producer.go, async_producer_test.go
If neither `Return.Errors` nor `Return.Successes` was set then `Close` wouldn't
actually block at all. This is arguably correct given the send-it-into-the-void-
and-pray configuration but it was still surprising.
It turns out to be a very minimal change to block anyway (since the `Errors`
channel is still present and closed at the appropriate moment) so just do that.
Also add a test for this configuration, since it's not one I remember to think
about on the regular.
@hchargois after poking around the code a bit I decided it was simpler to just fix this the way you suggested. Let me know if this works for you.
Closes #784.
=> Producer: block in `Close` without `Return.Errors`

sync_producer.go, sync_producer_test.go
It's surprising, for one thing, and as Alexander Zhuravlev discovered it can
actually lead to data races if you already have async producers active using the
same config object.
Instead, validate that it is pre-set correctly and return a config error if it
is not, so it is on the user to set things up properly (it's only one flag away
from default so it's not that big a deal).
Fixes #789.
cc @zaa
=> Sync Producer: Don't change config in constructor

consumer.go, mocks/consumer.go
This adds a way for a consumer user to access the PartitionConsumers high water marks.
=> Add Consumer.HighWaterMarks()

broker.go
A segmentation violation occurs when initializing producer using SASL fails.
=> Fix segmentation fault on SASL failed

consumer.go, produce_request.go
Clarify the behaviour of `WaitForAll`. Also fix some spelling/punctuation around
`HighWaterMarks` while I'm looking at the docs.
@CAFxX @giner
Closes #793.
=> Tweak some docs

client.go
Useful in general, but needed to iterate through all brokers and get consumer group offsets.
=> make list of brokers available through sarama.Client

mocks/async_producer.go, mocks/sync_producer.go
This two funcs were with wrong names in their comments, just corrected this.
=> Correcting two funcs comments

partitioner.go, partitioner_test.go
The function NewCustomHashPartitioner is a wrapper around the PartitionerConstructor, allowing for specifying the hash algorithm, which will be used.
Background for the proposed change: messages published on compacted topics by services, written in different languages (Go, Java, etc) end up on different partitions, although they have the same key. We were able to narrow the problem down to different hashing algorithms used by the different libraries, when determining the partition: murmur2 for a Java lib, FNV in sarama, crc32 for .NET and xxHash in librdkafka.  
A quick workaround is of course to copy/paste the hashPartitioner implementation to change the implementation of the hash.Hash32 interface ...which is basically one line out of ~50. So I decided I'd propose this PR to facilitate …
=> Add functionality for custom hash partitioner.

async_producer.go, sync_producer.go
AsyncClose has nothing to do with flushes at all.
Close *waits* for messages to be flushed, but does not *trigger* a flush
itself.
Clarifications as suggested in #834.
@agis- @wvanbergen
=> Tweak documentation of Close/AsyncClose methods

partitioner.go, partitioner_test.go
I had to realise that even though now the same hashing algorithm was used across services to determine the partition, the problem that messages published under the same key on log compact topics still ended up on different partitions. Unfortunately I found out that I made a huge mistake by passing an already instantiated hasher. Thus the proposed fix: pass a callback so the hasher is instantiated just before needed (thanks to the [wiki page](https://github.com/Shopify/sarama/wiki/Producer-implementation#message-flow) for helping my understanding of the publisher's flow).
=> Fix CustomHasher

join_group_request.go, join_group_request_test.go, request_test.go
The kafka protocol for JoinGroupRequest allows you to specify priority
on group protocols for seamless rollout of new protocols while a
consumer group is running. The old map was not supporting that use case.
Add an array field (OrderedGroupProtocols) and deprecate the map.
Fixes #812.
@DanielMorsing @wvanbergen
=> Permit protocol ordering in JoinGroup requests

errors.go
Support additional errors from https://kafka.apache.org/protocol#protocol_error_codes
=> Additional error codes

client.go, client_test.go
This restores the commit from @funkygao in PR #566, with an additional commit to expose the function on the `Client` interface and add some basic tests around its functionality.
The PR was previously closed with the suggestion that Zookeeper should be used directly, because, at the time, it was possible to receive stale information from Kafka. If I'm reading the [linked issue](https://issues.apache.org/jira/browse/KAFKA-1367?jql=text%20~%20%22ISR%20out%20of%20sync%22) correctly, that issue has been resolved since Kafka 0.9, so I'd like this patch to be reconsidered now.
I personally want this so that I can then add ISR support to the excellent [kt](https://github.com/fgeller/kt), which is the workhorse of a fair amount of the Kafka automation tooling I use.
=> Add client.Isr to determine in-sync replicas

mocks/consumer.go
This fixes a test crash on 32-bit architectures.
https://bugs.debian.org/cgi-bin/bugreport.cgi?archive=no&bug=860705
=> Fix memory alignment of int64 variable used as atomic.

crc32_field.go
As of Go 1.7, hash/crc32 has all the same optimizations. This means anyone on
an older Go version will see a performance hit, but anyone who cares about
performance should really be updating to Go 1.7 anyway.
=> Go back to hash/crc32

mocks/consumer.go
The config object is not unused and can in fact be set when calling the NewConsumer constructor.
This commit updates the function's description to reflect that.
=> Fix comment for mocks.NewConsumer

message.go
* Adds checks for negative timestamps on messages. Negative
timestamps are invalid. On decoding, return a zero time for easy
existence checking. On encoding, set timestamp to be -1 if the
given time describes a time before unix epoch.
=> negative timestamps on messages fix

consumer.go, fetch_request.go
This commit will add the 'MaxBytes' field to FetchRequests when the Kafka version is
0.10.1 or better (i.e. it adds support for V3 of the FetchRequest API). On send, it will be set to MaxResponseSize.
=> Added support for FetchRequest protocol version 3.

client.go, client_test.go, utils.go
It shouldn't sort the replicas and isr while the order is meaningful to Kafka(preferred leader)
=> FIX: Remove dupeAndSort in Replicas and InSyncReplicas

client.go, config.go
Typically the default is just to fetch and store all topics, as it is
simpler and more convenient not to have to go to the network for every
new topic that is needed. However this can use a lot of memory for
clusters with many topics and partitions, so add a flag which can be
unset in order to just store the minimal topic information needed so
far.
As suggested in #931.
@chandradeepak does this solve your problem?
=> Add a config option to store only minimal metadata

crc32_field.go, message.go, message_test.go
If sarama encounters an unknown message version somehow (e.g. due to a
bug in Kafka 0.11's downconversion), right now sarama will carry on
decoding the message, resulting in much harder to understand errors.
Instead, bail out early with a friendly error message.
I added a test, but struggled running tests on my laptop due to (I think) out of date dependencies, so will rely on CI running here. I also added a test for decoding a message with the `1` magic byte, which sarama supports but I could not see a test in `message_test.go` for.
=> make decoding unknown message versions error

mockresponses.go
@sanchezl this should address #938.
=> Permit setting version on mock fetch response

client.go
If Metadata.Full is set to false, and no topics have ever been
requested, the first background refresh would load them all because go's
varags don't distinguish between nothing and an explicitly splatted
empty array.
Just break instead.
@chandradeepak this *might* fix https://github.com/Shopify/sarama/issues/931#issuecomment-325829238? I'm just guessing.
=> Restrict client metadata update more

config.go, consumer.go, consumer_test.go, message_test.go
Add a ticker in (*partitionConsumer).responseFeeder to frequently check for
messages before starting the timeout timer. Using the fast checker significantly
reduces the number of timer function calls when timeouts are infrequent.
=> Add an optional fast checker to (*partitionConsumer).responseFeeder

offset_manager.go, offset_manager_test.go
This is mostly meant as a start of a discussion, happy to change it. cf #554 for initial discussions and use cases.
Added ResetOffset on PartitionOffsetManager that allows setting the offset to a value less than the current value.
From a downstream perspective I would prefer to have a single func to call that allows setting an offset to a smaller or greater value, regardless of the current value - but thought API-wise it'd make more sense to have MarkOffset and ResetOffset act as duals/complements. What do you think?
=> adds ResetOffset to reset to earlier offset values.

produce_response.go, produce_response_test.go
I have been running into an issue when using v1.13.0 of Sarama for unit testing a producer with the `MockBroker` abstraction.
When using an `AsyncProducer` with `config.version` >= `V0_9_0_0` decoding produce responses from a `MockBroker` fails with: `insufficient data to decode packet, more bytes expected`.
Example of application that fails when sending a `V0_10_0_0` `ProduceRequest` as it expects the same version in the `ProduceResponse`:
```go
package main
import (
"fmt"
"log"
"os"
"github.com/Shopify/sarama"
)
func main() {
sarama.Logger = log.New(os.Stdout, "[SARAMA]", log.LstdFlags|log.Lmicroseconds)
reporter := reporter{}
seedBroker := sarama.NewMockBroker(reporter, 1)
leader := sarama.NewMockBroker(reporter, 2)
metadataResponse := new(sarama.MetadataResponse) …
```
=> Support ProduceResponse v1 and v2 encoding

crc32_field.go, message.go
This is needed for Kafka 0.11 support as the new records' checksum is
computed with Castagnoli polynomial (previous versions of Kafka use
IEEE polynomial).
Issue #901
=> Add support for Castagnoli polynomial for CRC32 computation

length_field.go, packet_decoder.go, packet_encoder.go, prep_encoder.go, real_decoder.go, record.go, record_batch.go, record_test.go, records.go, records_test.go
This PR introduces implementation of the new Record and RecordBatch formats from Kafka 0.11. Also it introduces an union type to deal with request/responses that can contain either records or messages.
Issue #901
=> Add implementation of Kafka 0.11 Records

client.go
If we get `ErrReplicaNotAvailable` we should still return any partial
replicas/isr that we have.
@ruoshan this should address #929
=> client: return partial replicas

consumer.go
It's only needed for transactions (which we don't support yet) and the
logic was wrong anyway. Fixes slow consuming for certain Kafka 0.11
configurations.
@wladh @xhbpiao
Fixes #980. Supersedes #981.
=> consumer: don't check LastStableOffset

consumer.go, consumer_test.go, fetch_response.go, fetch_response_test.go, packet_decoder.go, produce_request.go, real_decoder.go, records.go, records_test.go
=> Determine the records type based on the magic number not API version

utils.go
This change makes error logging more informative for invalid version strings.
=> Escape periods in Kafka version regex

record_batch.go
In some corner cases (like v2 records produced on the topic but the
sarama consumer uses v0 Fetch API with a limit less than one record size)
we might receive a truncated record batch. We want to be able to make
progress by increasing the fetch limit, so don't return an error, but
rater mark the batch as partial trailing record.
Fixes issue #962
=> Check for insufficient data when we try to get the records.

broker.go, broker_test.go
@slaunay @mihasya @lday0321 this should hopefully solve #897? I don't know if I've covered all the cases.
=> Unregister metrics when closing broker

create_partitions_request.go, create_partitions_request_test.go, create_partitions_response.go, create_partitions_response_test.go, packet_decoder.go, packet_encoder.go, prep_encoder.go, real_decoder.go, real_encoder.go, request.go
this adds the request/response pair for `CreatePartitions`
=> add CreatePartitionsRequest/Response

consumer.go, consumer_test.go, errors.go, fetch_response.go
Hey, 
This seems to fix #1005. As far as I understood, we should advance partition consumer's offset with the LastOffsetDelta as this might be higher than the last record's offset in the batch if some of the offsets were compacted away.
=> partition consumer offset to last offset delta

produce_set.go, produce_set_test.go
This mimicks #1002, but for v3 requests. On Kafka 1.0.0
this prevents recompress on broker to add missing offsets.
=> Set Record.OffsetDelta to avoid broker recompression

async_producer_test.go, mockresponses.go
This allows setting the version of the message data struct for
MockProduceResponse. This change is very similar to what was already
done in pull request #939
In order to mock a "produce" request for Kafka version 0.10.2.0 you
would use the following:
leader.SetHandlerByMap(map[string]MockResponse{
"ProduceRequest": NewMockProduceResponse(t).
SetVersion(2).
SetError("my_topic", 0, ErrNoError),
})
=> Permit setting version on mock produce response

acl_bindings.go, acl_create_request.go, acl_create_request_test.go, acl_create_response.go, acl_create_response_test.go, acl_delete_request.go, acl_delete_request_test.go, acl_delete_response.go, acl_delete_response_test.go, acl_describe_request.go, acl_describe_request_test.go, acl_describe_response.go, acl_describe_response_test.go, acl_filter.go, acl_types.go, broker.go, request.go, request_test.go
continuing the `AdminClient` request-response party with `Describe`/`Create`/`DeleteAcls`.
These share some common stuff so easier to PR them together.
=> add Describe/Create/DeleteAcls

client_tls_test.go, mockbroker.go
and add some basic TLS tests now that we have it.
Our motivation is that we want to put similar tests in a library that wraps this one (https://github.com/rakutentech/kafka-firehose-nozzle/pull/21/), so are keen to get the `NewMockBrokerListener()` exposed.
=> Add NewMockBrokerListener() so that it's possible to test TLS connections

config.go
In my experiments of consuming very busy topics, I noticed this parameter makes a huge difference. Bumping up the default value from 32KB to 1MB almost increased consumption rate by 5X. 1MB seems to be the default value used in librdkafka as well.
=> changed Fetch.default value from 32KB to 1MB

add_offsets_to_txn_request.go, add_offsets_to_txn_request_test.go, add_offsets_to_txn_response.go, add_offsets_to_txn_response_test.go, add_partitions_to_txn_request.go, add_partitions_to_txn_request_test.go, add_partitions_to_txn_response.go, add_partitions_to_txn_response_test.go, broker.go, end_txn_request.go, end_txn_request_test.go, end_txn_response.go, end_txn_response_test.go, init_producer_id_request.go, init_producer_id_request_test.go, init_producer_id_response.go, init_producer_id_response_test.go, request.go, txn_offset_commit_request.go, txn_offset_commit_request_test.go, txn_offset_commit_response.go, txn_offset_commit_response_test.go
This should be pretty straight forward — it adds all the new related messages needed for the transactional producer:
=> add transaction-related messages (22, 24, 25, 26, 28)

message_set.go
If we end un unlucky and MessageSet buffer is truncated right before
we can read magic value, we just return `ErrInsufficientData`, even
if some messages were previously successfully parsed.
This propagates all the way up to `partitionConsumer`, where we zero
parsed messages, which results in `ErrMessageTooLarge` returned
to the consumer.
This commit fixes the issue by setting `PartialTrailingMessage` to `true`
on `MessageSet`, making it possible to read successfully parsed messages.
=> Do not choke on MessageSet without version

mocks/sync_producer.go, mocks/sync_producer_test.go
Fixing incorrect expectations checking for the SyncProducer mock
in SendMessages call.
1) SendMessages now checks the CheckFunction on each and
every single message/expectation. It's consistent with singular
SendMessage mocked implementation.
2) SendMessages now correctly copies the right size of expectations
to use when matching with produced messages. Fixes off by one error.
=> Proper mock expectations in SyncProducer.SendMessages

consumer.go
A ticker is created after each response, **even when there is no messages in the response**, so when the consumer is idle the CPU is still high. The cost of ticker creation and destruction is expensive, when the number of fetch requests goes up, both the CPU and memory are consumed by the tickers. 
So I try to reuse the ticker, and did not change the existing behavior. Now the timeout is still low precision (between `MaxProcessingTime` and `2 * MaxProcessingTime`).
Before:
After:
=> Consumer: reduce ticker allocations

produce_set.go, record_batch.go, record_test.go
Tweak to LastOffsetDelta calculation based on C implementation (which uses length of records - 1)
https://github.com/edenhill/librdkafka/blob/8fed971043e642c195860cd77006622d23616c22/src/rdkafka_msgset_writer.c#L1098-L1100
Fixes issue #1032
=> LastOffsetDelta calculation fix

config.go, message.go, produce_set.go, record_batch.go
This makes it possible to set compression level for gzip:
```
config.Producer.CompressionLevel = flate.BestCompression
```
There are no other compression codecs that support levels,
but the code is generic to easily add other codecs with
numeric levels.
Default compression level tracks what Go libraries
set as the default level.
=> Add support for compression levels, closes #1042

Makefile, alter_configs_request_test.go, async_producer_test.go, config.go, consumer.go, fetch_request.go, fetch_response.go, functional_consumer_test.go, message.go, metadata_request.go, metadata_response.go, offset_commit_request.go, offset_commit_response.go, offset_fetch_request.go, offset_fetch_response.go, offset_request.go, offset_response.go, produce_request.go, produce_request_test.go, produce_response.go, record_test.go, utils.go
This PR adds a test that is checking that messages produced by clients of all supported versions can be consumed by clients of all supported version, also throwing all possible compressions into the mix. When the test runs it uses the value of the `KAFKA_VERSION` environment variable as the upper version bound. First it produces with clients of all version up to the upper limit and for each version it produces messages with different compression algorithms. Then it reads all produced messages with clients of all supported versions.
The test revealed several issues:
1. ~`kafka: response did not contain all the expected topic/partition blocks`~: 
EDIT: I fixed that in this PR by only reporting `ErrIncompleteResponse` when there is no complete messages retrieved;
2. ~`lz4.Read: invalid …
=>  Add full version matrix produce/consume test

broker.go, client.go, consumer_metadata_request.go, consumer_metadata_request_test.go, consumer_metadata_response.go, consumer_metadata_response_test.go, find_coordinator_request.go, find_coordinator_request_test.go, find_coordinator_response.go, find_coordinator_response_test.go, request.go
As part of `KIP-98` and for the impl of the transactional producer the `GroupCoordinatorRequest`/`ConsumerMetadataRequest` has been renamed `FindCoordinatorRequest` and now serves the dual purpose of both looking up consumer group _and_ transaction coordinator.
This PR moves the logic to `FindCoordinatorRequest`, transitions `getConsumerMetadata` to use `FindCoordinatorRequest`, and provides transparent backwards compatibility for the `ConsumerMetadataRequest`.
=> refactor ConsumerMetadataReq/Resp -> FindCoordinatorReq/Resp

broker.go, delete_records_request.go, delete_records_request_test.go, delete_records_response.go, delete_records_response_test.go, request.go
I added the DeleteRecords operation. Hope it's welcome.
One thing I wasn't sure about is how you'd want the request struct to look. The current map in DeleteRecordsRequestTopic doesn't allow much room for expansion without breaking users. Is that OK?
=> Add DeleteRecords operation to Broker

consumer.go, fetch_response.go, fetch_response_test.go, offset_commit_request.go, produce_request.go, produce_set.go, produce_set_test.go, records.go, records_test.go
Kafka protocol implementation is public in Sarama and so it can be used in alternative producer/consumer implementations e.g. [mailgun/kafka-pixy](https://github.com/mailgun/kafka-pixy). But when `Records` union was introduced its fields `msgSet` and `recordBatch` were introduced as private for some reason, and that makes it impossible for protocol users to upgrade to the latest Sarama version. So in this PR I suggest to make those fields public to rectify this deficiency.
Besides `OffsetCommitRequest.Offset` method was introduced to allow inspecting the request offsets in test. It is not actually used in Sarama but can be useful.
=> Expose missing protocol parts

broker.go, find_coordinator_response.go, metadata_request.go, metadata_request_test.go, metadata_response.go, metadata_response_test.go
V1 enables to discover the cluster controller which is required to send CreateTopics, DeleteTopics and CreatePartitions requests
So far we've just added the v1 request/response "definition" just enough so v1 requests can be sent using `Broker.GetMetadata()` to find the controller.
`Client` is still using v0 metadata and also it would be nice to add a `Controller` field to `Broker.` We can do that in another PR.
Co-authored-by: Adrian Preston <prestona@uk.ibm.com>
Co-authored-by: Mickael Maison <mickael.maison@gmail.com>
=> Added support for Metadata Request/Response v1

find_coordinator_response.go, find_coordinator_response_test.go, mockresponses.go
`FindCoordinatorResponse.encode` function panics if `Coordinator` is `nil`, so I fixed that. Besides I added MockFindCoordinatorResponse to use in tests.
=>  Fix FindCoordinatorResponse.encode to allow nil Coordinator

find_coordinator_response.go, find_coordinator_response_test.go
#1050 introduced the `Rack`-field to the [`FindCoordinatorResponse`](https://kafka.apache.org/protocol#The_Messages_FindCoordinator), however this is only part of the [`MetadataResponse`](https://kafka.apache.org/protocol#The_Messages_Metadata). As we now have a shared method for decoding/encoding the broker for both these messages we can work around this (as was pre-#1050) by hard coding the version of the coordinator-decode to 0.
Ultimately I guess we should separate the decoding of the broker for these two messages, but maybe we should leave that for another day.
This removes the rack from the `FindCoordinatorResponse` and hardcodes the `Broker` `decode`/`encode` version to 0 and adds a comment for that.
cc @horkhe
=> remove rack from FindCoordinatorResponse

message_test.go
Support for Go 1.7 is dropped and tests are already failing on 1.7 (due
to the missing `sort.Slice`), so it might not make sense to keep the
fragile `runtime.Version` test.
Currently tests are failing on Go 1.10 (see #1064)
=> Drop testing empty gzip encoding with the pre-1.8 encoder

client.go
Currently, If you list topics, then delete a topic, and poll to find out when the topic is actually deleted, it will never appear as deleted. 
This is because `updateMetadata` doesn't remove topics that no longer exist from the metadata.
An example can be seen over at [terraform-provider-kafka](https://github.com/Mongey/terraform-provider-kafka/blob/bde19c591305bc385f6349d58f7b7183a2df8def/kafka/resource_kafka_topic.go#L115-L157)
Here's a very naive solution that deletes the previous metadata, if you've got all the topic information from the broker.
=> Clear all metadata when we have the latest topic info

client.go, client_test.go, errors.go, mockresponses.go
Sometimes we need to know the controller broker of a kafka cluster to do something, such as creating or deleting topics.
=> add Controller() method to Client interface

join_group_request.go, join_group_request_test.go, join_group_response.go, join_group_response_test.go
=> Added versioning for join-group requests and responses

consumer.go
There is a use-case in sarama-cluster where I want to `defer pcm.Close()` as well as call it explicitly to ensure it has actually stopped before proceeding with the next steps. I am currently wrapping the call in a `sync.Once` myself, but moving this to sarama seems generally a good idea.
=> Make PartitionConsumer.Close idempotent

broker.go, broker_test.go, delete_groups_request.go, delete_groups_request_test.go, delete_groups_response.go, delete_groups_response_test.go, request.go
=> Add support for DeleteGroups

Makefile
[This errcheck PR](https://github.com/kisielk/errcheck/pull/141) removed `fmt.Fprintf` from default exclude list and that makes CI sad, e.g. https://travis-ci.org/Shopify/sarama/jobs/385690067.
This PR brings back old behavior of errcheck.
=> Ignore fmt package when doing errcheck

consumer.go, consumer_test.go
Increment offsets to avoid consumer blocking. The issue is described here https://github.com/Shopify/sarama/issues/1087
=> Unblock consumer when receiving invalid FetchResponse (response did not contain all the expected topic/partition blocks)

async_producer.go, sync_producer.go
In SyncProducer, do not modify ProducerMessage.MetaData during the whole process of publishing the message to Kafka. 
MetaData could be used in a user-defined Partitioner. The original design saves the MetaData and reuse the field as a signal channel to wait for completion of publish. It's better to add a non-exeported field for this purpose in the ProducerMessage struct.
=> Do not modify ProducerMessage.MetaData

async_producer.go, partitioner.go, partitioner_test.go
This is a little bit speculative, but it was about as easy to write the patch as it was to write the proposal, so this seemed easier. I don't have any particular commitment to any aspect of the implementation, so I'm interested in hearing feedback.
---
One of the useful features of the random partitioner is that it will only partition messages onto partitions that are currently online. In theory, hash partitioner is capable of exhibiting the same behavior for messages where the key is unset, but it can't because RequiresConsistency is a constant for the partitioner. It's also not feasible to add methods to the Partitioner interface, since that's part of the public API.
Therefore, this introduces a new interface, ExtendedPartitioner, which includes an additional method: …
=> Make Partitioner.RequiresConsistency vary per-message

consumer.go
Move the skip for those block to after the point where we've
parsed/incremented the offset so we don't get stuck on a response
containing *only* control messages.
Should fix #1106. @FrancoisPoinsot can you please confirm?
=> Fix block on control messages

partitioner.go
So the partitioner has a lot of different partitioner constructors now, and they contain functionality which cannot all be created without creating new custom constructor functions for each.
This PR introduces a customizable partitioner which works with functions as options. New added options will not break the current behavior nor will it break the function signature. That will let us introduce new options while we are still backwards compatible.
For reference: 
https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis
=> add customizable partitioner

admin.go, admin_test.go, broker.go, mockresponses.go
@eapache @buyology @Mongey @mimaison @ongardie-ebay 
I started working on ClusterAdmin support and wrote an initial draft version. Want to get your comments that I am moving in the right direction. After your comments i will close to the pull request.
=> ClusterAdmin Support 

broker.go, config.go
We have hosts that are multi-homed and being able to pick a source address is important to contend with things like network ACLs.
=> Add LocalAddr to Config struct and honor in broker.Open().

client.go
This PR can help fix producer topic metadata on-demand fetch when topic error happens in metadata response.
There is an option [`Full`](https://github.com/Shopify/sarama/blame/f7df95cff1bc4d14a4194a5be4c88a86253afb98/config.go#L86-L90) in [`Config`](https://github.com/Shopify/sarama/blob/master/config.go#L285-L324) to config whether producer should fetch all topic metadata in a cluster or do it on-demand.
This feature is added in #937. 
But there is an situation where we may make on-demand topic metadata fetching fall back to empty once an topic error happens in metadata update.
For example, if `ErrUnknownTopicOrPartition` or `ErrInvalidTopic` or `ErrTopicAuthorizationFailed` or any other errors that will make the `switch` case `continue` happens, the topic name will be deleted from …
=> fix producer topic metadata on-demand fetch when topic error happens

metadata_request.go
If the set of Topics is an empty array, we don't need to put it in the
request or we'll just get an empty set of data back which is useless.
As far as I can tell the nil check was for safety, but len(nil) is
already safe and the boolean logic was wrong anyway.
Thanks to @Preylien for figuring this one out.
Fixes #1130.
=> Fix metadata requests on later versions

.gitignore, config.go, offset_manager.go, offset_manager_test.go
This is a necessary prerequisite for #1099, please also see the inline comments in the diff.
=> Simpler offset management, fixed minor race

CHANGELOG.md
Update changelog for release 1.18.0.
=> Changelog for release 1.18.0

message.go, message_test.go, record_batch.go
[KIP-110](https://cwiki.apache.org/confluence/display/KAFKA/KIP-110%3A+Add+Codec+for+ZStandard+Compression) is finally [accepted](https://lists.apache.org/thread.html/7ab8407e6cff115eafab1b8e0750cbb906cc9414104b352e26b32e55@%3Cdev.kafka.apache.org%3E), so I can make a PR with something [we've been using](https://blog.cloudflare.com/squeezing-the-firehose/) for quite a while now.
cc @dqminh, @andrew-plunk
=> Zstd support for compression

broker.go, broker_test.go
This change enables library clients to use the sarama Client to implement
rack-aware features.
=> exported Broker's rack setting

message.go, record_batch.go, zstd_cgo.go, zstd_fallback.go
The github.com/DataDog/zstd library wraps a c library, so it requires
cgo to compile. Add zstd wrapper funcs to sarama and put the zstd
import behind a build flag requiring cgo. Without cgo, the wrapper
funcs return an error saying zstd doesn't work without cgo.
Resolves #1179
=> Fix build without cgo

async_producer.go, async_producer_test.go, client.go, config.go, config_test.go, functional_consumer_test.go, produce_response.go, produce_set.go, produce_set_test.go
This PR adds support for the Idempotent Producer.
If the Idempotent configuration is enabled, upon startup the producer will retrieve a ProducerID and add it as well as sequence numbers to all produce requests.
This is still not complete and has not been properly tested yet. Quick tests showed that when retrying with idempotency, messages that have already been written to disk by brokers are correctly marked as duplicates.
This should be enough to start a discussion. Have a look and see if it's something you'd like merged. If so, I'll complete testing.
=> Added support for Idempotent Producer

.travis.yml, utils.go, vagrant/install_cluster.sh
Old download URLs for kafka return 404 so I updated them with a new mirror. 
Also fix `make fmt` condition to match all patch versions of Golang—instead of only matching 1.11.0 (`make fmt` would never run since we're already on 1.11.2).
Last but not least, add new version definitions and support for recently released Kafka 2.1.0.
@varun06 @muirrn could you please 👀this PR?
=> Add support for Kafka 2.1.0 and fix CI

offset_commit_request.go, offset_commit_request_test.go, offset_commit_response.go, offset_commit_response_test.go
Added OffsetCommit v3 and v4:
- request: no changes
- response: v3 added throttled time. v4 was just a version bump to indicate a change in quota handling (KIP-219)
=> Add support for newer OffsetCommit request/response

mockresponses.go, offset_fetch_request.go, offset_fetch_request_test.go, offset_fetch_response.go, offset_fetch_response_test.go
This adds support for OffsetFetch up to version 5 (v5 is added in Kafka 2.1).
We were especially interested in v2, which allows to query offsets for all partitions used by a group instead of explicitly passing the partitions but adding the extra versions was straight forward (very few new arguments).
=> Support new OffsetFetch request/response

offset_request.go, offset_request_test.go
This change adds `SetReplicaID` to the OffsetRequest structure. If `SetReplicaID` has not been used on an instance of `OffsetRequest`, `-1` will be used when serializing the request.
=> Optional replica id in offset request

describe_configs_request.go, describe_configs_request_test.go, describe_configs_response.go, describe_configs_response_test.go
This is needed to determine if a Topic Config is actually a Default in Kafka 1.0 and above. The Default value in the DescribeConfigResponse should really be deprecated, if < 1.0 is no longer supported.
Not quite sure what the new struct fields in DescribeConfigResponse should include `Config` prefixes or not. (`ConfigSource` `ConfigSynonms` etc)
=> Implement DescribeConfigs Request + Response v1 & v2

async_producer.go, async_producer_test.go
This should fix #1187 
Also do idempotent batch retries in a goroutine. This avoids the deadlock but does not
solve a race condition that can lead to out-of-sequence errors.
Idempotent producer is at proof-of-concept quality
Co-authored-by: Edoardo Comar <ecomar@uk.ibm.com>
Co-authored-by: Mickael Maison <mickael.maison@gmail.com>
=> Revert to individual msg retries for non-idempotent

compress.go, decompress.go, message.go, record_batch.go
Reusing lz4/gzip reader and writer objects via sync.Pool greatly reduces CPU usage (saves allocations and creates much less garbage).
=> Reuse compression objects

fetch_response.go
The deprecation notice for `FetchResponseBlock.Records` is a bit confusing.
Not sure which one between `Records` and `RecordsSet` is actually deprecated.
Looking through commit history it seem it is supposed to be that way.
=> fix typo in deprecation notice for FetchResponseBlock.Records

produce_set.go, produce_set_test.go
This is the fix for the issue reported here https://github.com/Shopify/sarama/issues/1140
=> Respect MaxMessageBytes limit for uncompressed messages

CHANGELOG.md
changelog for `1.20.1` release
=> changelog for 1.20.1 release

broker.go, broker_test.go, config.go, config_test.go, mockresponses.go, request.go, sasl_authenticate_request.go, sasl_authenticate_request_test.go, sasl_authenticate_response.go, sasl_authenticate_response_test.go, sasl_handshake_request.go
Hello,
This commit implements SASL/OAUTHBEARER client authentication as described in [KIP-255](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=75968876) and issue #1223.
To get started, the user must set `c.Net.SASL.Mechanism:  OAUTHBEARER` and assign a user-defined token generator to `config.Net.SASL.TokenProvider`. For backwards compatibility, a blank value for `c.Net.SASL.Mechanism` defaults to `PLAIN`.
Example:
```go
type TokenProvider struct {
}
func (t *TokenProvider) Token() (*sarama.AccessToken, error) {
return &sarama.AccessToken{Token: "access-token-string"}, nil
}
// ...
config.Net.SASL.Enable = true
config.Net.SASL.Mechanism = sarama.SASLTypeOAuth
config.Net.SASL.TokenProvider = &TokenProvider{}
```
cc @ggrcha
=> Implement SASL/OAUTHBEARER support

admin.go, admin_test.go, async_producer.go, client.go, client_test.go, config.go, consumer.go, consumer_group.go, consumer_metadata_response_test.go, errors.go, find_coordinator_response_test.go, leave_group_response_test.go, metadata_response_test.go, mocks/consumer_test.go, offset_manager.go, offset_manager_test.go, produce_response_test.go
Part of #1216 
This one is very opinionated since it makes a lot of renamings just for the sake of clear mapping between sarama's error codes and messages and kafka protocol.
Errors from https://kafka.apache.org/protocol#protocol_error_codes were converted to CamelCase style. Descriptions were taken as is. 
See also: 
https://github.com/apache/kafka/blob/741cb761c5239297029a446518c332f6c4ed08f6/clients/src/main/java/org/apache/kafka/common/protocol/Errors.java#L116
While it would be useful to keep this on par with the upstream kafka's error names and descriptions I understand that there is possibility of breaking backwards compatibility for users who already rely on error names that sarama has provided.
If you think this change is not worth it feel free to decline it.
=> Synced error names and descriptions with the kafka's protocol

admin.go, admin_test.go, async_producer.go, client.go, client_test.go, config.go, consumer.go, consumer_group.go, consumer_metadata_response_test.go, errors.go, find_coordinator_response_test.go, leave_group_response_test.go, metadata_response_test.go, mocks/consumer_test.go, offset_manager.go, offset_manager_test.go, produce_response_test.go
=> Revert "Synced error names and descriptions with the kafka's protocol"

consumer.go, consumer_test.go, fetch_response.go, message.go, record_batch.go
Currently sarama doesn't seem to properly support LogAppend type of timestamps. The patch is addressing this issue. The following was used is the reference for the change:
* https://github.com/dpkp/kafka-python/blob/34fcb11c1cf96d69573274104d3b746ce67a97f4/kafka/record/default_records.py#L204 and 
* https://github.com/dpkp/kafka-python/blob/34fcb11c1cf96d69573274104d3b746ce67a97f4/kafka/record/legacy_records.py#L262
=> Support LogAppend timestamps

tools/README.md, tools/kafka-producer-performance/README.md, tools/kafka-producer-performance/main.go
This tool mirrors `kafka-producer-perf-test.sh` in the Kafka distribution. I was using this myself for some performance testing on this library and thought I might as well drop this here in in case others find it useful.
=> Producer performance tool

admin.go, admin_test.go, mockresponses.go
This PR adds the following admin client methods:
DescribeTopic
DescribeConsumerGroup
ListConsumerGroups
ListConsumerGroupOffsets
For ListConsumerGroups, all brokers are queried (the java client does it the same way). Since this will be super slow with multiple brokers, i made an implementation with parallel requests.
The others methods are rather straight forward.
I'll be happy about comments on the API, is it fine?
I'm not 100% sure - for the groups i chose it to be  'singular' - each method call is for one consumer group. For topics it's a slice of topics as parameter - in my case (building a kafka cli tool) it's very often the case that multiple topics are requested, so i kept it this way.
In #1155 (another addition to the admin client) i wondered how the API should look like. I kept …
=> admin: Add some missing admin methods

describe_configs_request.go
V1 is only supported on Kafka 1.1.0 and higher.
Difficult to find an official page, other than [this](https://cwiki.apache.org/confluence/display/KAFKA/Kafka+APIs),  where this is documented, but from a describe api versions
Kafka 1.0
```
Key:32, Min: 0, Max: 0
```
Kafka 1.1
```
Key:32, Min: 0, Max: 1
```
=> Set correct Kafka version for DescribeConfigsRequest v1

admin.go, admin_test.go, mockresponses.go
Follow-on from #1155 / #1178 include the replica assignment information that we got back in the ListTopics() TopicDetail responses
=> admin: include ReplicaAssignment in ListTopics()

async_producer.go, async_producer_test.go, sync_producer_test.go
Some applications may wish to disable retries so that they can implement custom
retry logic.  As currently written, though, setting Config.Producer.Retry.Max to
zero also disables the mechanism by which the producer updates its metadata in
response to an error.  If the producer gets an error such as
ErrNotLeaderForPartition or an io.EOF, it will never recover...even in response
to background metadata updates.  This commit resolves that issue by ensuring
that the partition producers still update the leader and corresponding input
channel even when retries are turned off.
=> Maintain metadata in the producer even when retries are disabled.

consumer.go
See https://github.com/Shopify/sarama/pull/1086#issuecomment-442226755 for details
=> Fix consuming compacted topic

async_producer.go, async_producer_test.go, client.go, client_test.go, config.go, consumer.go, consumer_test.go, offset_manager.go, offset_manager_test.go
This is just a proof-of-concept to convey the idea, I intend to flesh things out based on feedback if this seems like something that would be likely to land.
The `Retry.Backoff` config settings as they currently stand can force users to make some hard choices. Take `Config.Producer.Retry.Backoff` for example: using the default configuration, a 300ms+ hiccup in the cluster could lead to data loss without careful error handling in user code. Say you want to survive up to a 10s hiccup without data loss -- you're left with a few bad options:
1. You increase `Producer.Retry.Backoff` to 4-5s+ and live with the occasional large latency spike. (This includes things like partition leadership changes.); or
2. You increase `Producer.Retry.Max` to 100 and keep `Producer.Retry.Backoff` in the low …
=> *.Retry.BackoffFunc

consumer_group.go
When using a ConsumerGroup I managed to block all but one consumers after Kafka went down (but Zookeeper kept running).
Test setup:
* zookeeper + kafka
* 1 partition
* run a consumer multiple times, restarting as desired causing the group to be rebalanced (just in case)
* kill kafka - one consumer properly leaves the "Consume" method while the others keep waiting
Debugging revealed that the "retries" went into negative numbers, simply because the failed retries were not evaluated at that point in the code. My PR adds this missing check and therefore allows a clean shutdown on a failed kafka connection.
=> fixed potential deadlock when a heartbeat request fails

utils.go, vagrant/install_cluster.sh
Since Kafka 2.2.0 RC is out, add support to the next release.
=> Add support for Kafka 2.2.0

admin.go, admin_test.go, create_partitions_response.go, create_partitions_response_test.go, create_topics_response.go, create_topics_response_test.go, mockresponses.go
Contributes-to: Shopify/sarama#1153
Signed-off-by: Dominic Evans <dominic.evans@uk.ibm.com>
=> Satisfy the error interface in create responses

async_producer.go, client.go, consumer.go, consumer_group.go
Instead of carrying around a symbol for `ownClient`, just embed the `Client` passed in by the caller with a wrapper that disables invoking `Close()`.
=> reduce client close bookkeeping

consumer.go, record.go
- Preallocate message slice as it is more efficient
- Apparently in Go, if pointers are in front of struct, it reduces pressure on GC, so I have made that change in consumer file, if everything works fine, I will do that for other types too.
From performance slack channel ->
>So the reason that works, as I understand it, is that for any given block of data, there's a series of bits describing its pointerness. Specifically, two bits per 64-bit word; one indicates whether *this* word is a pointer, one indicates whether *any bit after it* is a pointer.
So the GC scans through from the beginning of the object until there's no more pointers, and checks all the things marked as pointers.
if you have pointers at the end of an object, the gc has to scan through the entire object looking for them. …
=> preallocate message slice in consumer.go and random fixes

broker.go, broker_test.go, config.go, config_test.go, response_header.go
Hi ! I would like to add SCRAM-SHA-512 and SCRAM-SHA-256 SASL mechanismes. We are already using this fork in production.
=> Add SASL SCRAM-SHA-512 and SCRAM-SHA-256 mechanismes

tools/kafka-console-consumer/kafka-console-consumer.go, tools/kafka-console-producer/kafka-console-producer.go, tools/tls/config.go
For testing TLS with Kafka ACL I added TLS options for the consumer and producer tools...
=> Added TLS options with client auth to kafka-console-producer and consumer

consumer.go, sarama.go
This has been a great source of confusion. Removed the existing references to sarama-cluster library as sarama itself supports consumer group api now.
=> removed references to sarama-cluster

consumer.go, consumer_test.go
When closing a `PartitionConsumer`, a race condition will happen if draining the channel `messages` . This causes user's consuming routine gets partial messages, which can lead to confusion.
This problem is related to https://github.com/bsm/sarama-cluster/issues/255
=> try fixing a PartitionConsumer's race condition

offset_manager.go
- I don't think that go routine add anything to that code, it's a singleton already and shouldn't spin a go routine, saves 1 go routine scheduling :)
=> remove go keyword from channel close in singleton

balance_strategy.go
This fixes the comment for the Plan function in balanceStrategy. There was also another typo in a comment.
=> Fix typo and comment in balance_strategy.go

.github/CONTRIBUTING.md
minor fix, since the doc was pointing to older docs for `vet`
=> Fixing broken link for vet

broker.go, metrics.go
Add methods for registering broker-specific metrics so it is possible to
keep track of them and they can be unregistered on broker stop.
Fixes #1219
=> Unregister all broker metrics on broker stop

examples/consumergroup/main.go
I did accidently put a goroutine inside the `ConsumeClaim`, but that was wrong.
In the docs it's mentioned that the `ConsumeClaim` itself is called w/in a goroutine.
I felt like adding a note, to avoid others doing the same mistake.
=> Adding note for clarification

consumer_group.go
when cleanup return an error , why handle ‘err’ ( seem always nil ) ？
=> fixed handle cleanup error

admin.go, admin_test.go, async_producer_test.go, client.go, client_test.go, metadata_request.go, metadata_response.go, mockresponses.go, offset_manager_test.go, sync_producer_test.go
Added Offline Replicas Operation to `Client`.
- Added `OfflineReplicas` Operation
- Implemented Operation
- Added unit tests
- Changed the metadata request and response encoders
- Add to add logic to set the version id based on the version present on the `Config`
https://github.com/Shopify/sarama/issues/1311
=> added offline replicas operation to client for kafka version >= 1.x

consumer_group.go
Group coordinators seem to be selected from among those brokers which lead `__consumer_offsets` partitions, so when leadership of `__consumer_offsets` partitions move from one broker to another (e.g. due to an outage, or a controlled reassignment of partition replicas) the coordinator for a given group may move with it.
Sarama usually seems to handle these events by returning nil from `ConsumerGroup.Consume()` after a heartbeat fails due to a `ErrNotCoordinatorForConsumer`. In these cases it seems like you can just call `ConsumerGroup.Consume()` again to ask the consumer to resume where it left off. If you do this, what you typically see something like this in the logs when group coordinators move:
```
[sarama] 2018/12/04 01:32:58 consumer_group: <nil>
[sarama] 2018/12/04 01:32:58 …
```
=> Retry ErrNotCoordinatorForConsumer in ConsumerGroup.newSession

.travis.yml
Looks like `ld` is too old on Ubuntu 14.04.
=> Run CI builds on ubuntu 16.04

metadata_request.go, metadata_request_test.go
Consulting the protocol guide the V5 request uses the same nullable
array for topics as the V1-V4 requests. Improve existing unittest to
properly exercise the encoding paths.
Fixes #1352
=> bug: V5 MetadataRequest nullable topics array

broker.go, broker_test.go, config.go, config_test.go, examples/sasl_scram_client/main.go
As sarama can connect to multiple brokers as the same time, the scram client must be different for each connection as it uses steps to connect via sasl. This avoids the auth mechanism to use the same scram client on connection that have different states.
Symptoms example:
``2019/03/29 09:24:18 kafka: error while consuming *****/6: kafka server: Request is not valid given the current SASL state.``
- error while decoding scram/sasl fields
=> [sasl] use a SCRAM client for each connection

broker.go, broker_test.go, client.go
> If SaslHandshakeRequest version is v0, a series of SASL client and
> server tokens corresponding to the mechanism are sent as opaque packets
> without wrapping the messages with Kafka protocol headers. If
> SaslHandshakeRequest version is v1, the SaslAuthenticate
> request/response are used, where the actual SASL tokens are wrapped in
> the Kafka protocol. The error code in the final message from the broker
> will indicate if authentication succeeded or failed.
References:
https://kafka.apache.org/protocol#sasl_handshake
https://kafka.apache.org/protocol#The_Messages_SaslHandshake
https://kafka.apache.org/protocol#The_Messages_SaslAuthenticate
=> feat: support SaslHandshakeRequest v1

async_producer.go
The `Timestamp` field was introduced in https://github.com/Shopify/sarama/pull/678 and at this point was only set by 
the broker.
Subsequent to this, the changes described in [KIP-32] were implemented,
allowing the `Timestamp` of the message to be set by a producer when the
broker was configured to use `CreateTime`.
This commit updates the doc on the ProducerMessage struct to reflect that
depending on which of the `CreateTime` and `LogAppendTime` modes are active,
the `Timestamp` can be meaningfully set by either the request or the
response.
[KIP-32]: https://cwiki.apache.org/confluence/display/KAFKA/KIP-32+-+Add+timestamps+to+Kafka+message
=> async_producer: clarify ProducerMessage `Timestamp` doc

client.go, client_test.go, config.go
Sarama Version: `v1.22.0-6-g2a49b70` (2a49b70a5c87e2dac5801f72d80fd2732c1c7b75)
Kafka Version: `1.0.2`
Go Version: `1.12`
What configuration values are you using for Sarama and Kafka?
Default configuration, see unit tests.
Fetching metadata from an unreachable cluster using the default configuration (`30s` `DialTimeout`, `3` retries, `250ms` backoff) of **2** brokers can take more than **4 minutes**  before failing with `ErrOutOfBrokers`.
The following logs can be seen when running the provided unit test against `master` with unresponsive seed brokers (with TCP read timeout on `127.0.0.1:63168` and `127.0.0.1:63169` to simulate unreachable cluster with TCP dial timeout):
```
DEBUG=true go test -v -run=TestClientMetadataTimeout/timeout=10m0s
[sarama] 2019/04/18 09:38:00 Using random seed: …
```
=> Support timeout when fetching metadata

packet_decoder.go, real_decoder.go, records.go
Background:
In a project I use, sarama produces by far the most ongoing allocations (mainly, I think, because have lots of small messages) which negatively impacts our GC stats. I recently went through and tried to reduce them where I could and have been quite successful in that sarama doesn't show up in the pprof top10 by `alloc_objects`.  This is the simplest change I made so far. The others follow the pattern from #1161 and are more invasive.
I benchmarked this change by consuming 5 million messages and then dumping out a heap profile.
Before the change:
```
Showing nodes accounting for 30777165, 99.24% of 31012468 total
Dropped 6 nodes (cum <= 155062)
Showing top 10 nodes out of 19
flat  flat%   sum%        cum   cum%
10362760 33.41% 33.41%   25777082 83.12% …
```
=> Provide peekInt8 to reduce allocations

consumer.go, consumer_test.go
Kafka 2.2 returns a throttled FetchResponse with an empty array of topics.
Previously Sarama treated this as an ErrIncompleteResponse and would
abandon and re-create the subscription instead of retrying the
FetchRequest.
=> bug: handle and log throttled FetchResponses

crc32_field.go, length_field.go, message.go, message_set.go, record_batch.go
This is a followup to #1373 to further reduce objects allocated per message. It takes some inspiration from #1161 but starts with internal allocations, to not require clients to release any objects.
Tested allocations by consuming 2 million (small, ~32 bytes) messages and profiling which functions allocated the most. Here is the base case:
```
Type: alloc_objects
Showing nodes accounting for 10886534, 99.52% of 10939241 total
flat  flat%   sum%        cum   cum%
4256506 38.91% 38.91%    7504220 68.60%  github.com/Shopify/sarama.(*MessageBlock).decode
2419737 22.12% 61.03%    8980700 82.10%  github.com/Shopify/sarama.(*MessageSet).decode
2031646 18.57% 79.60%    2031646 18.57%  github.com/Shopify/sarama.newCRC32Field
1952968 17.85% 97.46%    1952968 17.85% …
```
=> Pool internal objects allocated per message

errors.go
Adds Kafka server error codes corresponding to https://kafka.apache.org/protocol#protocol_error_codes
=> Add Kafka error codes 77-81

examples/sasl_scram_client/main.go
In the process of debugging and testing a kafka proxy SASL SCRAM implementation I found the need to consume to validate it works. I thought it may be useful for others so submit it here.
=> Add consume ability to sasl_scram_client example

broker.go, broker_test.go, config.go
Sarama force SASL V1 handshake when Kafka protocol is greater than 1.0.
Azure Eventhub is still using SASLV0.
I moved the SASL protocol version to the config, defaulting to V0 (like before), but I also removed the auto V1 when Kafka > 1.0
Refer to https://github.com/Shopify/sarama/issues/1408 for more info.
@varun06 Let me know if this is what you expected or let me know what you prefer, like keeping the old behaviour but adding a config flag to disable the force change to V1 when Kafka > 1.0
=> added SASLVersion in config

admin.go, admin_test.go, mockresponses.go
This PR adds the Admin Command DeleteConsumerGroup. I made it singular, like it has been done with DeleteTopic.
=> admin: add DeleteConsumerGroup

admin.go, admin_test.go, mockresponses.go
According to [this](https://cwiki.apache.org/confluence/display/KAFKA/KIP-88%3A+OffsetFetch+Protocol+Update) it is possible to send an OffsetFetch Request with `Version 2` starting from kafka version `0.10.2.0`.
This allows to send `nil` as parameter `topicPartitions` and returns offsets for all topicPartitions available.
my pull request implements this.
=> support ListConsumerGroupOffsets without topicPartition

broker.go, broker_test.go
This PR aims to fix a bug (Issue #1423) in the SASL/OAUTHBEARER implementation where the Sarama client does not fail when the broker rejects the auth token and instead fails on the subsequent request following the auth flow. 
This fix is based upon how the Java implementation handles token rejection.
The client handles SaslAuthenticate responses [containing a non-empty challenge](https://github.com/apache/kafka/blob/2.3.0/clients/src/main/java/org/apache/kafka/common/security/oauthbearer/internals/OAuthBearerSaslClient.java#L99) as an auth failure. Previously, Sarama only logged the challenge. The initial broker response containing the challenge does not contain an error code that can be raised to the client—the client must then make a subsequent request to the broker with a [`\x01` …
=> Handle SASL/OAUTHBEARER token rejection

admin.go, admin_test.go, errors.go
The pr is to fix a bug about delete records. Currently sarama send the request to the controller.  It should be sent to the leader according the code in kafka client.
related with https://github.com/Shopify/sarama/issues/1377
=> fix deleteRecord  

CHANGELOG.md
Bug Fixes:
- Fix fetch delete bug record
([1425](https://github.com/Shopify/sarama/pull/1425)).
- Handle SASL/OAUTHBEARER token rejection
([1428](https://github.com/Shopify/sarama/pull/1428)).
=> changelog for 1.23.1

.travis.yml, Makefile, async_producer.go, async_producer_test.go, go.mod, go.sum
Every create a of a brokerProducer spins off a goroutine for the run()
loop func, but this appeared to just be abandoned if the brokerProducer
was shutdown and would manifest as orphaned goroutine(s) with a long
select time leaking over time:
e.g.,
```
goroutine 6982 [select, 1868 minutes]:
github.com/Shopify/sarama.(*brokerProducer).run(0xc420c4ac00)
/home/travis/build/org/repo/vendor/src/github.com/Shopify/sarama/async_producer.go:672 +0x258
github.com/Shopify/sarama.(*brokerProducer).(github.com/Shopify/sarama.run)-fm()
/home/travis/build/org/repo/vendor/src/github.com/Shopify/sarama/async_producer.go:622 +0x2a
github.com/Shopify/sarama.withRecover(0xc4207aa3f0)
/home/travis/build/org/repo/vendor/src/github.com/Shopify/sarama/utils.go:45 +0x43
created by …
```
=> fix brokerProducer goroutine leak

admin.go
Added ...FromClient constructor to ClusterAdmin in the same way as for others in order to reuse clients
=> cluster admin from client

admin.go
This PR adds a conditional to set the Kafka version. If the version is at last 2 then it sets request.Version = 1, which enables the functionality of getting the AclResourcePatternType field for the ACLs.
=> Set the Kafka version in ListAcls method

admin.go
Right now the request version is always set to 0 when using CreateACL method. And it is therefore ignores the ResourcePatternType value causing created ACLs to be always of LITERAL type.
This PR fixes the issue and allows to create ACLs of any pattern type on brokers with versions 2.0+.
=> Set request version in CreateACL ClusterAdmin method

admin.go
One more PR to enable ResourcePatternTypeFilter in the request. For method DeleteACL this time.
This fix will allow deleting ACLs with pattern type other than LITERAL.
=> Set request version in DeleteACL ClusterAdmin method

client.go, errors.go
Adds a few missed errors that I've encountered, in particular one https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-TopicMetadataRequest and one https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-GroupCoordinatorRequest 
Also adds https://kafka.apache.org/protocol#protocol_error_codes code # `82`
The CLA check is failing, but I have previously signed it - if I try to do so again, I get
```
To sign our CLA 1 field needs to be changed
GitHub username has already signed a CLA
```
=> Handle missed error codes on TopicMetaDataRequest and GroupCoordinatorRequest

Makefile, go.mod, gssapi_kerberos.go
fixes https://github.com/Shopify/sarama/issues/1438
`jcmturner/gokrb5` needs to use the `jcmturner/gofork` in order to have
some workarounds about some stuff not implemented or not working as
expected.
For the specific case of github.com/jcmturner/gofork/encoding/asn1 there
is no reason right now to keep using `jcmturner/gofork` as the issue
golang/go#17321 was solved/closed in Dec 15, 2016 and released in go
1.10
`jcmturner/gokrb5` still uses internally `jcmturner/gofork`, it seems
the `gofork` `asn1` part could be removed and use the standar library,
but that will need some more work and PRs on the `jcmturner/gokrb5`
side.
=> removes gofork direct usage as fix is part of go

Makefile, go.mod, go.sum
Uses a valid release of zstd
`v1.3.6` doesn't exist in https://github.com/DataDog/zstd/releases
Fixes https://github.com/Shopify/sarama/issues/1401
=> Uses a valid release of zstd

CHANGELOG.md
Wondering if we need to add this to the readme, as I think the current Zstd support is misleading according to https://github.com/Shopify/sarama/issues/1252
We can even delete all Zstd related code until a proper fix/feature is added. (and remove the cgo dependency :) )
Thoughts @bai @mkaminski1988 @varun06
=> make a note about incomplete zstd support

.github/ISSUE_TEMPLATE.md
This will help reviewers as most of the time go code is posted without
formatting, or big logs are pasted
=> improves template formatting

balance_strategy.go, balance_strategy_test.go, consumer_group.go, examples/consumergroup/main.go, sticky_assignor_user_data.go, sticky_assignor_user_data_test.go
This PR adds support for the sticky partition assignment strategy defined in Kafka Improvement (KIP) [KIP-54 ](https://cwiki.apache.org/confluence/display/KAFKA/KIP-54+-+Sticky+Partition+Assignment+Strategy), and later in [KIP-341](https://cwiki.apache.org/confluence/display/KAFKA/KIP-341%3A+Update+Sticky+Assignor%27s+User+Data+Protocol). This includes the use of consumer group generation numbers to reconcile conflicting information from consumer group members.
The sticky partition assignment strategy differs from the range and roundrobin strategies by attempting to keep topic partition assignments on the same consumer from the previous assignment. This is accomplished by having the consumer group leader use assignment information stored in the consumer `userdata` to learn about previous …
=> Sticky partition assignor

.travis.yml, README.md, dev.yml, go.mod
Add support for Go 1.13 and remove Kafka 2.1 from build matrix according to 2 releases + 2 months schedule.
=> Add support for Go 1.13

mockresponses.go
This PR adds a Version field to the MockDeleteTopics response with the same value as request has. This allows to mock a response from Kafka version higher than V0_11_0_0.
=> Set correct version in MockDeleteTopicsResponse

mockresponses.go
This PR adds a Version field to the MockDeleteAcls response with the same value as request has. This allows to mock a response from Kafka version higher than V2_0_0_0.
=> Use response with the same version as request in MockDeleteAclsResponse

examples/consumergroup/main.go
Sarama was misspelled as Sarma in one part of the file.
=> Update documentation with Sarama instead of Sarma

broker.go, describe_log_dirs_request.go, describe_log_dirs_request_test.go, describe_log_dirs_response.go, describe_log_dirs_response_test.go, request.go
=> Add describe log dirs request and response

broker.go, broker_test.go
The broker.go connection doesn't consistently set Read and Write
deadlines before performing read/write operations on the net.Conn. In
various scenarios if the broker stops responding that can cause the
given connection in the client to block indefinitely
Fixes #1528
=> fix: ensure consistent use of read/write deadlines

mocks/consumer.go
2052bd96dcab85d948d0160df9f9c812f39e7641 introduced function [SetTopicMetadata](https://github.com/Shopify/sarama/commit/2052bd96dcab85d948d0160df9f9c812f39e7641#diff-6acb248b0c9e15a39154801da6ee192eR120) but referred to it as to `SetMetadata` in the code which causes confusion if you try to use mock consumer. This PR fixes references to correct name.
UPD: I've signed the CLA.
=> fix incorrect SetTopicMetadata name mentions (introduced in 2052bd9)

client.go
`Println` is used instead of `Printf` for logging in `client.tryRefreshMetadata` which result in a bad `%s` substitution and a two lines log statement (see below).
This was introduced in commit fe1b1849d04059a2b197e824095364637405e31f.
| Sarama | Kafka | Go |
|--------|-------|----|
| 1358e9c (`v1.24.0`)  | N/A | 1.13  |
```
$ DEBUG=true go test -v -run=TestClientMetadataTimeout/timeout=250ms | grep -C 2 "not fetching
metadata"
[sarama] 2019/11/07 09:17:58 Closed connection to broker 127.0.0.1:50294
[sarama] 2019/11/07 09:17:58 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama] 2019/11/07 09:17:58 client/metadata not fetching metadata from broker %s as we would go past the metadata timeout
127.0.0.1:50295
[sarama] 2019/11/07 …
```
=> Fix client.tryRefreshMetadata Println

client.go, consumer_group.go
Hello, after updateing sarama to `v1.24.1` in https://github.com/ThreeDotsLabs/watermill-kafka our tests are failing because of `assignment to entry in nil map`:
```
[watermill] 2019/11/01 16:20:41.213125 subscriber.go:211: 	level=INFO  msg="Starting consuming" consumer_group=test kafka_consumer_uuid=jPK7fjGRZHsbSueM94mnqg provider=kafka subscriber_uuid=GZqfP4ixUbbvvoQYMHJcVF topic=topic_620ff2d2-616d-472e-a016-8329edb4738d 
[watermill] 2019/11/01 16:20:41.505179 subscriber.go:298: 	level=DEBUG msg="Consume stopped without any error" consumer_group=cg_9d09a750-cee9-402d-b6e9-5549781ef810 kafka_consumer_uuid=fsXW4sWL3Bs2XPoaHY5PXj provider=kafka subscriber_uuid=6PLBzrNsMkvZZFjPzWxa9F topic=topic_a1916770-8048-4928-ae01-3768f760d229 
[watermill] 2019/11/01 16:20:41.506553 subscriber.go:304: …
```
=> fixed panic on calling updateMetadata on closed client

tools/kafka-producer-performance/main.go
Support TLS security protocol in the kafka-producer-performance tool.
- add `security-protocol` flag with `PLAINTEXT` default for backward compatibility
- add `tls-ca-certs`, `tls-client-cert` and `tls-client-key` flags to configure broker and client mutual authentication
- add `verbose` flag to turn on logging
- use `outgoing-byte-rate` metric to get real throughput
Working scenario:
```
$ ./kafka-producer-performance \
-brokers kafka:9093 \
-security-protocol SSL \
-tls-ca-certs /path/to/ca-cert.pem \
-tls-client-cert /path/to/cert.pem \
-tls-client-key /path/to/key.pem \
-topic topic \
-message-load 2000000 \
-message-size 1000 \
-version 1.1.0
61164 records sent, 292280.2 records/sec (278.74 MiB/sec ingress, 0.00 MiB/sec egress), 74.3 ms avg latency, 3.4 ms stddev, 74.0 ms 50th, 77.8 …
```
=> Support TLS protocol in kafka-producer-performance

functional_producer_test.go, vagrant/halt_cluster.sh
Functional tests `TestFuncProducing*` can fail because of "faulty" metric recorded when one of Kafka brokers is not reachable.
This happened when building #1539 as seen from the following logs (https://travis-ci.org/Shopify/sarama/jobs/612081678#L12183-L12217):
```
=== RUN   TestFuncProducingSnappy
[sarama] 2019/11/14 21:59:11 Initializing new client
[sarama] 2019/11/14 21:59:11 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama] 2019/11/14 21:59:11 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama] 2019/11/14 21:59:11 client/metadata fetching metadata for all topics from broker localhost:9091
INFO[0376] Accepted client …
```
=> Fix possible faulty metrics in TestFuncProducing*

.travis.yml, README.md, dev.yml, utils.go
Kafka 2.4.0 will be cut in a few days.
=> Add support for kafka 2.4.0

produce_set.go, produce_set_test.go
It is possible for the same record to have a different timestamp depending on where it appears in a produceSet, as the test case in this commit illustrates.
The problem is that the produceSet's FirstTimestamp and the record's TimestampDelta are each calculated with nanosecond precision, and then truncated to millisecond precision during encoding. This leads to accumulated rounding error when the original timestamp is later reconstructed.
Instead, truncate all timestamps to millisecond precision before calculating the FirstTimestamp and TimestampDelta, so that if the same record is produced multiple times, it will always have the same timestamp.
It might be better to call encode on each record instead of reproducing the logic of how to encode a timestamp in the test, but I can't see an …
=> Produce records with consistent timestamps

admin.go, admin_test.go, config_resource_type.go, mockresponses.go
When operating on Broker configuration via the Admin API, the request
_must_ be sent to the specific broker that the change applies to, _not_
just (as usual) to the Controller.
=> fix: use the broker for any admin on BrokerConfig

admin.go, admin_test.go, mockresponses.go
Although fbd8338 had added protocol support for DescribeConfigsRequest
v1 and v2, nothing in the admin client was actually setting the Version
field to utilise these. Set the Version based on the selected
sarama.Config version.
=> fix: set DescribeConfigRequest Version field

admin.go
A very minor fix, but the v1 MetadataRequest (which returns the
controller ID) was actually introduced in Kafka 0.10.0.0 (not 0.11.0.0)
under https://issues.apache.org/jira/browse/KAFKA-3306 so can be used
there.
=> fix: MetadataRequest version in DescribeCluster

fetch_request.go, fetch_request_test.go, fetch_response.go, request.go
In order to consume zstd-compressed records the consumer needs to send
and receive version 10 FetchRequest/FetchResponses, but they need to do
so in a well-formed manner that adheres to the encoding format.
Ref: https://kafka.apache.org/protocol
Signed-off-by: Dominic Evans <dominic.evans@uk.ibm.com>
=> fix: fill in the Fetch{Request,Response} protocol

consumer_group.go
reduce refresh  metadata frequency  to avoid flood logs
=> fixed ConsumerGroup flooding logs with client/metadata update req #1544

consumer_group.go
The deadlock can happen if the heartbeat request runs out of retries while the consumer group session is being released. `consumerGroup.Consume` will acquire the consumer group lock and then call `consumerGroupSession.release` which will block waiting for the channel `hbDead` to be closed. If the `heartbeatLoop` then runs out of retries and calls `consumerGroup.handleError` the `handleError` call will block on the lock preventing `heartbeatLoop` from closing `hbDead`.
It is safe to remove the lock acquisition in `handleError` because the channel operations in the critical section are already thread safe.
I also moved the lock/unlock from `Close` into `leave` to more accurately reflect the resources being protected.
Example stack traces for the deadlock:
```
goroutine 1 [semacquire, 2 …
```
=> Fix deadlock in consumer group handleError

broker.go, broker_test.go, config.go
We'll only flow the SASL auth identity through to Kafka if it is set by
the user in `sarama.Config{}`. If it is left unset then it will just
flow through the empty string null separated as before.
=> Add SASL AuthIdentity to SASL frames (authzid)

CHANGELOG.md, config.go, config_test.go, consumer.go, functional_consumer_test.go, produce_request.go, produce_response.go, produce_response_test.go, produce_set.go
Zstd support was initially added to sarama before
https://issues.apache.org/jira/browse/KAFKA-4514
https://cwiki.apache.org/confluence/display/KAFKA/KIP-110%3A+Add+Codec+for+ZStandard+Compression
was done.
The final release added some changes like bumping the produce and fetch
requests to only allow new clients to use zstd.
This PR tries to do that, however, there are some other protocol changes
that are not addressed on this PR, and I'm not sure what would be the
effect of bumping the produce and fetch requests without filling the
protocol gaps.
Tries to solve https://github.com/Shopify/sarama/issues/1252
TODO:
- it seems it's working fine after my latests commits 🎉 
Now I need to figure it out what to do with the new producer response field, or just leave it like that?
- It still …
=> Enables zstd (for real this time)

admin.go, admin_test.go, client.go, config.go
If an admin request to Create/Delete Topic{Partitions} receives a
ControllerNotAvailable kError back from Kafka, we should expire the
cached controller and refresh it from metadata.
Additionally add a `Retry` section to the `Admin` config similarly to
the Java AdminKafkaClient and consider this case one that is eligible to
be re-tried
=> fix: retry topic request on ControllerNotAvailable

admin_test.go
fixes https://github.com/Shopify/sarama/issues/1238
``` text
kafka_1        | [2020-01-31 20:01:54,868] INFO [Admin Manager on Broker 1001]: Updating topic test.1.nokey with new configuration org.apache.kafka.common.requests.AlterConfigsRequest$Config@614a2b22 (kafka.server.AdminManager)
zookeeper_1    | [2020-01-31 20:01:54,880] INFO Got user-level KeeperException when processing sessionid:0x100008cfc4f0000 type:create cxid:0x3bf zxid:0x1eb txntype:-1 reqpath:n/a Error Path:/config/changes Error:KeeperErrorCode = NodeExists for /config/changes (org.apache.zookeeper.server.PrepRequestProcessor)
kafka_1        | [2020-01-31 20:01:54,930] INFO Processing notification(s) to /config/changes (kafka.common.ZkNodeChangeNotificationListener)
kafka_1        | [2020-01-31 20:01:54,953] INFO …
```
=> fix misleading example for cluster admin

broker.go, broker_test.go, functional_producer_test.go, metrics_test.go, sarama.go, tools/kafka-producer-performance/main.go
Add `requests-in-flight` metric similar to the Kafka Java client described as:
> The current number of in-flight requests awaiting a response.
This is an interesting metric to monitor for optimizing throughput when writing to a Kafka cluster on a high latency network link and something that is recommended when implementing the Kafka protocol as described in [their network section](https://kafka.apache.org/protocol#protocol_network):
> The broker's request processing allows only a single in-flight request per connection in order to guarantee this ordering. Note that clients can (and ideally should) use non-blocking IO to implement request pipelining and achieve higher throughput. i.e., clients can send requests even while awaiting responses for preceding requests since the outstanding …
=> Add requests-in-flight metric

balance_strategy.go, balance_strategy_test.go, consumer_group.go
The StickyBalanceStrategy currently provides state information with member assignments. This is achieved through a custom name check in the `syncGroupRequest` of the consumer group. This works well for this case, but falls apart when trying to create additional stateful balance strategies. This update will make it possible to create new stateful balance strategies
=> Allow BalanceStrategy to provide custom assignment data

CHANGELOG.md, balance_strategy_test.go
=> Add changelog for 1.26.1

client_test.go
This fixes `TestClientAutoRefreshShutdownRace()` to not fire `t.Fatal()` inside a goroutine.
`t.Fatal()` is a convenience function that calls `t.Log()` and `t.FailNow()`. `t.FailNow()` should not be called from inside a goroutine. From the godoc:
> FailNow must be called from the goroutine running the test or benchmark function, not from other goroutines created during the test.
This replaces the `done` channel with an `error` channel, and tests the error variable outside the goroutine.
=> fix: remove use of testing.T.FailNow() inside goroutine

consumer_group.go, consumer_group_test.go, examples/consumergroup/main.go
Improve consumer group `Consume` method docs.
=> adds a note about consumer groups Consume method

async_producer_test.go
This removes `testLogger{}` and its functions. It is unused today, and it appears to have been unused since its introduction in 8/2019.
@dnwe, am I missing anything here?
=> tests: remove unused testLogger

produce_response.go
This removes two unused functions from the root `sarama` package.
=> produce_response.go: Remove Unused Functions

tools/kafka-producer-performance/main.go
This removes two unused variables that were intended as `flag` options in `tools/kafka-producer-performance`.
=> tools/kafka-producer-performance: prune unused flag variables 

functional_test.go, kerberos_client_test.go, request_test.go
This removes some unused variables and the `testRequestBody` type from the tests.
=> Prune Unused Test Types and Variables

client.go
The "client/metadata retrying" log message was always reporting
the sleep duration as `config.Metadata.Retry.Backoff`, regardless
of whether `config.Metadata.Retry.BackoffFunc` is implemented.
We now report the actual retry time before sleeping.
=> Updated "retrying" log message when BackoffFunc implemented

broker.go
Broker.registeredMetrics is increased in Broker.Open, but isn't cleared in Broker.Close.
So when Open and Close is called repeatedly it causes memory leak.
=> Fix memory leak when Broker.Open and Broker.Close called repeatedly

admin.go, admin_test.go, describe_configs_response.go, describe_configs_response_test.go, mockresponses.go
We were relying on the `ConfigEntry.Default` field to filter out any default config settings when using `admin.DescribeConfig()`.
After updating to the most recent version of sarama, this flag is always set to `false` with Kafka versions > `V1_1_0_0`.
We found out that we can now use the `ConfigEntry.Source` to check for defaults. I don't know it was intended change to "break" the `ConfigEntry.Default` in higher versions - let me know. 
This change sets the `ConfigEntry.Default` flag in addition to the `ConfigEntry.Source` for Kafka versions > `V1_1_0_0`. 
I haven't written any tests yet as I'm not familiar with the code base. I can add some later.
=> Sets ConfigEntry.Default flag in addition to the ConfigEntry.Source for Kafka versions > V1_1_0_0

compress.go
when large number of messages, for gzip(1-9) cost high cpu, because of gc.
=> add sync pool for gzip 1-9

config.go, config_test.go
According to https://github.com/golang/go/blob/master/src/net/dial.go#L81
tcp keepalive is **ENABLED** when `KeepAlive` is set to 0 by default
=> fix `config.net.keepalive`

consumer_group.go
`err` is always `nil`, it is checked above already.
=> Return the response error in heartbeatLoop

index.md
The text on https://shopify.github.io/sarama/ is outdated. 
This updates the text to match the project readme.
Fix https://github.com/Shopify/sarama/issues/1248.
=> Fix outdated website readme

client.go, client_test.go, consumer_test.go
This pull request solves the problem: #1629. I find it only have update and add broker when update brokers by latest metadata, however there is no code of remove broker which if offline
=> Remove broker(s) which no longer exist in metadata

consumer.go, consumer_test.go
KIP-227 says that if a client provides a session ID of 0 and a session epoch of 0 in a FetchRequest, the broker should allocate a new sessionID. Then, the consumer can use this ID to avoid repeating the list of partitions to consume on every call. I figured this out from the table in KIP-227 here: https://cwiki.apache.org/confluence/display/KAFKA/KIP-227%3A+Introduce+Incremental+FetchRequests+to+Increase+Partition+Scalability#KIP-227:IntroduceIncrementalFetchRequeststoIncreasePartitionScalability-FetchRequestMetadatameaning (let me know if I got this wrong!)
Sarama is currently sending 0 for both values (I validated this with a packet capture), but totally ignoring the session ID generated by the broker. This means that the broker is allocating a new session ID on every request, filling …
=> Fix brokers continually allocating new Session IDs

async_producer.go, async_producer_test.go, functional_producer_test.go, produce_set.go
When the following three conditions are satisfied, the producer code can skip message sequence numbers and cause the broker to complain that the sequences are out of order:
* `config.Producer.Idempotent` is set
* The producer loses, and then regains, its connection to a broker
* The client code continues to attempt to produce messages whilst the broker is unavailable.
For every message the client attempted to send while the broker is unavailable, the transaction manager sequence number will be incremented, however these messages will eventually fail and return an error to the caller. When the broker re-appears, and another message is published, it's sequence number is higher than the last one the broker remembered - the values that were attempted while it was down were never seen. Thus, …
=> Fix "broker received out of order sequence" when brokers die

broker.go, broker_test.go, client_tls_test.go, config.go
It seems that the code was either proxy or tls but in my case I need tls over the socks proxy so Ive created this PR to fix this issue.
Note there seems to be an issue with the tls test where the server name was never set so Ive fixed that too.
=> Bugfix: Allow TLS connections to work over socks proxy.

admin.go, admin_test.go, mockresponses.go
Some requests didn't returns ErrorMsg whereas ErrorCode is set to non 0.  
On kafka 2.1.1 with SASL configured, a call to clusterAdmin.AlterConfig on a not authorized resource, return no ErrorMsg but ErrorCode is 29 (ErrTopicAuthorizationFailed)
=> Handle errors with no message but error code

broker.go, client_tls_test.go
fixes https://github.com/Shopify/sarama/issues/1691
TBH I'm not sure if this is enough.
There was a big change here:
https://github.com/Shopify/sarama/pull/1666/files#diff-019034382244c82f15c92490660e4a18
`s/tls.DialWithDialer/tls.Client`
and all code that was in `tls.DialWithDialer` is not in `tls.Client`, so no handshake, timeouts, etc.
https://github.com/golang/go/blob/go1.14.2/src/crypto/tls/tls.go#L102
=> Set ServerName using tls.DialWithDialer approach

vagrant/boot_cluster.sh
For some reason we'd ended up with quite a short (10s) limit on waiting
for Kafka to startup and open its listener and since moving from Travis
to GitHub actions, this can periodically take longer causing the build
to abort early. Bump it up to 2m and tweak a couple of other parts of
the boot script.
=> testfix: give kafka longer to startup

vagrant/boot_cluster.sh
- set Java heap options for ZooKeeper and Kafka
- disable the adminServer (:8080) in ZooKeeper 3.5.x
=> testfix: set KAFKA_HEAP_OPTS for zk and kafka

broker.go, client_tls_test.go
Fixes https://github.com/Shopify/sarama/issues/1700
=> Set server name only for the current broker

gssapi_kerberos.go, kerberos_client.go, kerberos_client_test.go
This PR allows Kerberos to be configured with fast negotiation disable, it is required for certain KDCs (i.e Active directory Kerberos server).
=> Expose kerberos fast negotiation configuration

go.mod, gssapi_kerberos.go
This reverts commit bfff38f6e549a57ac7209f146d3b271ebcf6e044.
Closes #1658
=> Use gofork for encoding/asn1 to fix ASN errors during Kerberos authentication

consumer_group.go, offset_manager.go, offset_manager_test.go
Provide manual Commit method and don't create mainloop if AutoCommit is disabled
Fixes #1570
=> Consumer group support for manually comitting offsets

go.mod, go.sum
There have been some performance optimizations for zstd in last few version of compress package. We are running relatively old version, this PR updates compress package to latest.
```
+--------+---------+---------------------------+-------+------+------+------+
| STATUS | ELAPSED |          PACKAGE          | COVER | PASS | FAIL | SKIP |
+--------+---------+---------------------------+-------+------+------+------+
| PASS   | 77.05s  | github.com/Shopify/sarama | 0.0%  |  446 |    0 |    1 |
+--------+---------+---------------------------+-------+------+------+------+
```
=> updated zstd dependency to latest v1.10.10

async_producer.go, async_producer_test.go, config.go, consumer.go, consumer_test.go, functional_producer_test.go, interceptors.go
[KIP-42 Add producer and consumer interceptors](https://cwiki.apache.org/confluence/display/KAFKA/KIP-42%3A+Add+Producer+and+Consumer+Interceptors)
This PR includes:
Producer: `OnSend` but it doesn't implement `onAcknowledgement`
Consumer: `OnConsume` but it doesn't implement `onCommit`
I tried on purpose to not follow the Java design too closely. This PR tries to follow Go idioms to the degree possible.
I didn't add an `onClose` method on the interface, Go has other alternatives for this if needed.
for:
> Since there may be multiple interceptors, the first interceptor will get a record from client passed as the 'record' parameter. The next interceptor in the list will get the record returned by the previous interceptor, and so on. Since interceptors are allowed to mutate records, …
=> KIP-42 Add producer and consumer interceptors

balance_strategy.go
As-is, the first thing `isBalanced()` does is clobber its `sortedCurrentSubscriptions` argument. This changes its signature to ditch that argument, and continue its current behavior of deriving its own `sortedCurrentSubscriptions` via `sortMemberIDsByPartitionAssignments(currentAssignment)`.
=> sarama: Fix isBalanced Function Signature

.gitignore, admin.go, async_producer_test.go, balance_strategy.go, consumer.go, consumer_group.go
This is part of cleaning up some of the Lint and Vet issues. This is first PR in list of many PR's.
=> fixed variable names that are named same as some std lib package names

client_tls_test.go
`tls.Config.BuildNameToCertificate()` is deprecated. `godoc` advises:
>// Deprecated: NameToCertificate only allows associating a single certificate with a given name. Leave that field nil to let the library select the first compatible chain from Certificates.
This removes both uses of it from `doListenerTLSTest()`
=> sarama: remove deprecated tls options from test

.github/workflows/ci.yml, .golangci.yml, README.md, functional_test.go, utils.go
=> Add support for Kafka 2.6.0

api_versions_request_test.go, async_producer_test.go, broker.go, client.go, consumer.go, examples/README.md, examples/sasl_scram_client/main.go, mockresponses.go, tools/kafka-console-producer/kafka-console-producer.go, tools/kafka-producer-performance/main.go
Another lint/vet fix that's backward compatible. 
```
+--------+---------+---------------------------+-------+------+------+------+
| STATUS | ELAPSED |          PACKAGE          | COVER | PASS | FAIL | SKIP |
+--------+---------+---------------------------+-------+------+------+------+
| PASS   | 76.81s  | github.com/Shopify/sarama | 0.0%  |  446 |    0 |    1 |
+--------+---------+---------------------------+-------+------+------+------+
```
=> fixed declaration dependencies and other lint issues in code base

client.go, client_test.go
`RefreshBrokers` takes a list of addresses to be used as seed brokers.
Existing broker connections are closed and the updated list of seed brokers will be used for the next metadata fetch.
`RefreshBrokers` can be used in the case of failovers when the Kafka cluster's DNS would have to be re-resolved
=> Refresh brokers given list of seed brokers

admin_test.go, async_producer_test.go, broker_test.go, client_test.go, client_tls_test.go, config.go, config_test.go, consumer_group_test.go, consumer_test.go, functional_client_test.go, functional_consumer_group_test.go, functional_consumer_test.go, functional_offset_manager_test.go, functional_producer_test.go, functional_test.go, kerberos_client_test.go, metadata_response_test.go, mocks/async_producer_test.go, mocks/consumer_test.go, mocks/mocks.go, offset_manager_test.go, partitioner_test.go, produce_set_test.go, sync_producer_test.go, utils.go
This PR fixes https://github.com/Shopify/sarama/issues/1787. As explained there:
The current default, 0.8.2, is a 5 year-old version. The problem with defaulting to older versions when the Kafka cluster is a newer version is manifold:
- requires Kafka to downconvert consumer response messages (e.g if a newly-configured client produced messages and a default Sarama client is reading) - this has implications on the performance of Kafka, because it uses additional CPU. Especially so if compression is enabled, at which point the broker would need to decompress, downconvert and compress the message back. Downconversion also blocks zerocopy, because your fetch response now needs to be copied into memory
- requires Kafka to upconvert producer requests' messages
- in general is hard to support. …
=> fix: bump default version to 1.0.0

client.go
Related: https://github.com/Shopify/sarama/pull/1781#discussion_r473121038
https://github.com/Shopify/sarama/pull/1781 added an interface method for `Client`.
Adding interface methods will break backwards compatibility if there's anyone implementing it.This PR adds a `private()` method to prevent implementation,
=> Add private method to Client interface to prevent implementation

async_producer.go, consumer.go
A little PR adding support for Go 1.13 `errors.Unwrap` to `ConsumerError` and `ProducerError`. 
This feature might be particularly useful for generic error handling code, such as when propagating custom errors from `Consumer.ConsumeClaim()` or unit testing failure cases using mocks.
I considered extending other error structs in the codebase but they either do not surface external or custom errors; or are aggregated errors that cannot have an unambiguous `Unwrap()` result.
I am not sure what tests might be useful for this change. Please let me know if any tests are needed.
=> Support Go 1.13 error unwrapping

CHANGELOG.md
update changelog
will create a [release](https://github.com/Shopify/sarama/releases) once it's merged. [draft](https://github.com/Shopify/sarama/releases/tag/untagged-8833f120e6782dd9953a)
=> 1.27.1 changelog

client.go
Reverts Shopify/sarama#1785
this is causing more damage that the initial intention to prevent breaking changes.
Some people are using mock libraries and they are getting issues with this change
i.e, when using mockery
```
Cannot use 'mockSaramaClient' (type *mocks.Client) as type sarama.Client Type cannot implement 'sarama.Client' as it has a non-exported method and is defined in a different package
```
=> Revert "Add private method to Client interface to prevent implementation"

README.md
So the godoc.org is outdated now, so maybe it would be more convenient to give a link to a new platform instead.
=> Update Godoc link to pkg.go.dev

.github/workflows/ci.yml
This PR fixes CI being permanently red due to `setenv` permissions issues with GitHub Actions.
/cc @dnwe @d1egoaz fyi
=> Fix CI setenv permissions issues

balance_strategy.go, balance_strategy_test.go
There is a different behavior between 
- [sarama's roundrobin balance strategy](https://github.com/Shopify/sarama/blob/master/balance_strategy.go#L80)
```go
// pseudo code
for topic, partitions := range allTopicPartitions {
i := 0
for partition := range allPartitions {
consumer := allconsumers[i % len(allconsumers)]
consumer.assign(topic, partition)
i += 1
}
}
```
- [kafka java client's roundrobin balance strategy](https://github.com/apache/kafka/blob/6649b7a91dafcff4f2ed5b5ec1c0bb02b755e7f7/clients/src/main/java/org/apache/kafka/clients/consumer/RoundRobinAssignor.java):
```go
// pseudo code
i := 0
for partition := range AllSortedPartitions {
consumer := allconsumers[i % len(allconsumers)]
consumer.assign(topic, partition)
i += 1
}
```
In some case, sarama's implementation may incur …
=> feat[balance_strategy]: announcing a new round robin balance strategy

mocks/sync_producer.go, mocks/sync_producer_test.go
Mock sync producer does not handle the offset while invoking `SendMessages`.
e.g.
```go
mockSyncProducer := mocks.NewSyncProducer(t, sarama.NewConfig())
msgs := []*sarama.ProducerMessage{
{Key: sarama.StringEncoder("foo")},
}
mockSyncProducer.SendMessages(msgs)
// Print offset
print(msgs[0].Offset)
```
=> fix: mock sync producer does not handle the offset while sending messages

offset_manager.go
Adds ``om.conf.Consumer.Offsets.AutoCommit.Enable`` during closing of the ``offset_manager`` and hence fixing #1843
=> Do not ignore Consumer.Offsets.AutoCommit.Enable config on Close

CHANGELOG.md
Add changelog entries before 1.28.0 release.
=> Add changelog for 1.28.0

control_record.go, control_record_test.go
Kafka documentation defines control batches as a single record batches
containing data that shouldn't be passed to applications. The record
contained inside the control batch consist of a key with well defined
format and a value which format is defined by the control batch type.
Control batch key format:
```
ControlRecordKey => version type
version => INT16
type => INT16
```
Fixed control batch parsing logic by first parsing the key to check if
control batch is of known type and only then parsing corresponding
record value.
Signed-off-by: Michal Maslanka <michal@vectorized.io>
=> Parsing only known control batches value

acl_types.go, acl_types_test.go
Sometimes it's useful converting the constants of the acl types from/to text.
The text representation is the name without the prefix.
When converting from text to the types the string will be normalized to catch most variants.
=> add String, (Un)MarshalText for acl types.

.github/workflows/ci.yml, Makefile, README.md, functional_test.go, utils.go
This PR adds support for Kafka 2.8.0.
=> Add support for Kafka 2.8.0

admin.go, broker.go, gssapi_kerberos.go
- Incorrect conversion between integer types
- Size computation for allocation may overflow
=> fix: correct initial CodeQL findings

acl_delete_request.go, admin.go, decompress.go, encoder_decoder.go, message.go, mockbroker.go, partitioner.go
The switch-case here is redundant. There is the logic of this part of the code in the `decompress` function.
=> Remove redundant switch-case, fix doc typos

broker.go, errors.go, offset_fetch_request.go, offset_fetch_request_test.go, offset_fetch_response.go, offset_fetch_response_test.go, offset_request.go, offset_request_test.go, offset_response.go, offset_response_test.go, request.go
This PR enables OffsetRequest and to require read committed isolation.
It adds RequireStable field to FetchOffsetRequest, this requires the use of the new compact protocol present in version 6+.
=> Handle isolation level in Offset(Request|Response) and require stable offset in FetchOffset(Request|Response)

async_producer_test.go
The TestAsyncProducerRecoveryWithRetriesDisabled periodically fails and
then passes on a re-run. Stepping through it I believe this was because
the test had assumed metadata requests would always go to the
seed/bootstrap broker, but they can actually go to any broker. So there
was a 1 in 3 chance that the test would fail because it would await
timeout of metadata requests that were never going to be responded to.
Rewriting the test to use the handler map capability rather than the
expectations interface and configuring the mock metadata responses on
all mock brokers allows the test to pass quickly and reliably.
=> fix(test): improve flakey async producer test

consumer_group.go
Unlikely to cause an issue in Sarama unless the user explicitly set
Metadata.Retry.Backoff especially high and was hitting lots of retry
conditions, but no harm in guarding against this.
Ref: https://medium.com/@oboturov/golang-time-after-is-not-garbage-collected-4cbc94740082
=> fix: ensure backoff timer is re-used

acl_types.go
According to current ResourceTypes in https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/resource/ResourceType.java#L66 Sarama is missing DelegationToken definition.
=> Add DelegationToken ResourceType

alter_configs_response.go, broker.go, incremental_alter_configs_request.go, incremental_alter_configs_request_test.go, incremental_alter_configs_response.go, incremental_alter_configs_response_test.go, request.go
Hello!
In this PR I cover IncrementalAlterConfigs API in Sarama. It is very useful, due to fact we can specify which config entry needs to be affected (instead of sending everything over and over again).
Fixes: #1830, https://github.com/birdayz/kaf/issues/155
Kafka Code Links:
- [KIP-339](https://cwiki.apache.org/confluence/display/KAFKA/KIP-339%3A+Create+a+new+IncrementalAlterConfigs+API)
- Operation definitions: https://github.com/apache/kafka/blob/2.3/clients/src/main/java/org/apache/kafka/clients/admin/AlterConfigOp.java#L38
Best Regards,
Adam.
=> KIP-339: Add Incremental Config updates API

tools/kafka-producer-performance/main.go
#1969  fix  kafka-producer-performance tool panic
=> fix  kafka-producer-performance throughput panic

consumer.go
Missing call for interception when MaxProcessingTime timed out and we process the remaining messages
=> fix(consumer):  call interceptors when MaxProcessingTime expire

partitioner.go, partitioner_test.go
WithCustomFallbackPartitioner implementation was broken and didn't allow passing a partitioner
Fixes #1913
=> fix: correct WithCustomFallbackPartitioner implementation

async_producer.go
Not closing AsyncProducer before process shutting down seems a common mistake when using it.
I believe it is worth to inform users that messages can be lost if they omit to call `Close()` when using AsyncProducer.
=> docs: inform AsyncProducer Close pitfalls

consumer_group.go, sarama.go
This PR adds 4 new metrics:
* `consumer-group-join-total-<GroupID>`
* `consumer-group-join-failed-<GroupID>`
* `consumer-group-sync-total-<GroupID>`
* `consumer-group-sync-failed-<GroupID>`
It should be useful when troubleshooting ongoing network issues.
=> feat: add counter metrics for consumer group join/sync and their failures

.github/workflows/ci.yml, README.md, dev.yml
=> Add support for Go 1.17

broker.go, broker_test.go
Fix #1918 ,Maybe other scram issues are also relevant！Thanks！
=> feat: support SaslHandshakeRequest v0 for SCRAM

.golangci.yml, alter_configs_response.go, describe_configs_response.go, logger_test.go
nilerr finds code which returns nil even though it checks that error is
not nil. This flagged up a few incorrect checks in some of our packet
encoder/decoders, so fix those.
=> fix: enable nilerr linter and fix iferr checks

CHANGELOG.md, admin.go, admin_test.go, broker.go, broker_test.go, delete_offsets_request.go, delete_offsets_request_test.go, delete_offsets_response.go, delete_offsets_response_test.go, functional_consumer_group_test.go, mockresponses.go, request.go
Implement #1912 
Add support for _KIP-496: Administrative API to delete consumer offsets_: 
https://cwiki.apache.org/confluence/display/KAFKA/KIP-496%3A+Administrative+API+to+delete+consumer+offsets
=> Add support for DeleteOffsets operation

delete_offsets_request_test.go, delete_offsets_response_test.go
Fix #2012 
Disable encoded response/request check when map contains multiple elements. In that situation the encoded/request response varies because of unpredictable map traversal order
=> fix(test): disable encoded response/request check when map contains multiple elements

admin.go, alter_client_quotas_request.go, alter_client_quotas_request_test.go, alter_client_quotas_response.go, alter_client_quotas_response_test.go, broker.go, describe_client_quotas_request.go, describe_client_quotas_request_test.go, describe_client_quotas_response.go, describe_client_quotas_response_test.go, packet_decoder.go, packet_encoder.go, prep_encoder.go, quota_types.go, real_decoder.go, real_encoder.go, request.go
This PR implements the new ClientQuota API, available since Kafka 2.6.0.0
KIP: https://cwiki.apache.org/confluence/display/KAFKA/KIP-546%3A+Add+Client+Quota+APIs+to+the+Admin+Client
Protocols:
https://kafka.apache.org/protocol#The_Messages_DescribeClientQuotas
https://kafka.apache.org/protocol#The_Messages_AlterClientQuotas
=> KIP-546 Client quota APIs

.github/CONTRIBUTING.md, .github/stale.yml, .github/workflows/codeql-analysis.yml, README.md, examples/consumergroup/main.go, examples/interceptors/trace_interceptor.go
Change default branch from master to main.
=> Change default branch to main

Vagrantfile, consumer_group.go, functional_consumer_group_test.go
This update will allow stateful balance strategies to provide initial state information to send as part of the `joinGroupRequest`.
Previous to this PR if initial data was provided via `c.config.Consumer.Group.Member.UserData` it would always be sent when re-joining. This would trump the previous assignment data returned as part of the `syncGroupRequest`. After this PR the initial data will be sent when there is no currently assigned user-data that was returned as part of the assignment.
=> feat: allow balance strategies to provide initial state

docker-compose.yml, functional_client_test.go, functional_producer_test.go, functional_test.go
Part of the effort to upgrade to Kafka 2.8.0
=> Bump confluentPlatformVersion from 6.1.1 to 6.2.0

config.go, consumer_test.go, decompress.go, examples/http_server/http_server.go, examples/sasl_scram_client/main.go, functional_test.go, produce_response_test.go, produce_set_test.go, sarama.go, sync_producer.go, tools/kafka-console-producer/kafka-console-producer.go, tools/kafka-producer-performance/main.go
- always perform time.Time comparison with the Equal func
see https://pkg.go.dev/time#Time.Equal
- replace deprecated ioutil usage with corresponding io.|os. calls
=> chore: replace deprecated Go calls

sarama.go
Currently Sarama has the single `Logger` instance of a `StdLogger` that
is used for all log statements within the module. This works well
because user applications can trivially redirect it to their own logging
library of choice simply by implementing the StdLogger interface and
changing the package root variable.
However, currently there are a fair number of quite verbose log statements in the
module that output during normal golden path operation and it would be
helpful to be able to differentiate those from the abnormal output.
e.g.,
```go
Logger.Println("Initializing new client")
Logger.Printf("client/metadata fetching metadata for %v from broker %s\n", topics, broker.addr)
Logger.Printf("client/metadata fetching metadata for all topics from broker %s\n", broker.addr)
```
etc.
This PR …
=> log: add a DebugLogger that proxies to Logger

broker.go, client.go
Replace some of the more verbose golden path log statements with a call
to DebugLogger rather than Logger. With the out of the box Sarama
configuration, these will still just get proxied to whatever the regular
Logger is set to use. However, the caller can override DebugLogger with
their own implementation which may include a Discard logger.
=> feat: use DebugLogger reference for goldenpath log

consumer_test.go, logger_test.go
As it turns out, this setup was periodically causing the test to fail
due to a data race occurring on the `Logger` global when the defer ran
(!)
Fixes #2011
=> fix(test): remove testLogger from TrackLeader test

api_versions_request.go, api_versions_request_test.go, api_versions_response.go, api_versions_response_test.go, mockresponses.go, request.go
Add support for the ApiVersionsRequest V3 protocol which includes
ClientSoftwareName and ClientSoftwareVersion as specified by KIP-511
=> feat: support ApiVersionsRequest V3 protocol

.github/release.yaml
Add some customisation around the new automatically generated releases
notes in the releases UI
https://github.blog/2021-10-04-beta-github-releases-improving-release-experience/
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#example-configuration
=> chore: add release notes configuration

sarama.go
Default DebugLogger had broken Printf directives -
for DebugLogger.Printf(fmt,A,B,C) it called Logger.Printf(fmt,[A B C]),
which resulted in logs like
```
client/coordinator coordinator for consumergroup [topicname
%!s(int32=1) host:9094] is #%!d(MISSING) (%!s(MISSING))
```
This commit fixes value passing for Printf.
=> logger: fix debug logs' formatting directives

consumer.go, consumer_test.go, fetch_response.go, fetch_response_test.go, records.go, records_test.go
#2053 
Sometimes in rare cases of corruption or other reason, Kafka can return batches with zero records even if a high watermark was not reached. In this case, sarama just tries to reread this batch again and again and is stuck. There is no resolution in this case except skipping this batch.
librdkafka can handle these cases skipping with a warning.
=> fix: stuck on the batch with zero records length

docker-compose.yml, functional_test.go
Confluent released their distro of Kafka 3.0 as Confluent 7.0
=> chore: confluent platform version bump

consumer.go, fetch_response.go
FetchResponse from a follower will _not_ contain a PreferredReadReplica. It seems like the partitionConsumer would overwrite the previously assigned value from the leader with -1 which would then trigger the "reconnect to the current leader" changes from #1936 causing a flip-flop effect.
Contributes-to: #2071
=> fix: only update preferredReadReplica if valid

mocks/async_producer.go, mocks/async_producer_test.go, mocks/consumer.go, mocks/consumer_test.go, mocks/sync_producer.go, mocks/sync_producer_test.go
In some tests I left it as it was, just to show and test that both ways are possible.
=> fix(test): add fluent interface for mocks where missing

consumer.go, consumer_test.go
Based on https://github.com/Shopify/sarama/pull/2081 , please check the commits separately to get clearer diff.
=> fix: set HWMO during creation of partitionConsumer (fix incorrect HWMO before first fetch)

admin.go, admin_test.go, mockresponses.go
For [#2083](https://github.com/Shopify/sarama/issues/2083)
=> feat: expose IncrementalAlterConfigs API in admin.go

admin.go, functional_admin_test.go
That PR resolve issue #2095, it has been tested against Kafka 2.7.0 and Kafka 2.8.1
=> fix: ignore non-nil but empty error strings in Describe/Alter client quotas responses

consumer_group.go
Sarama would immediately stop heartbeating on rebalance. If the session teardown took longer than the session timeout, it would get evicted from the group.
This can be fixed by ensuring that heartbeats only stop _after_ the session has completed its cleanup process.
Contributes-to: #1608
=> fix: ensure heartbeats only stop after cleanup

mockresponses.go
- testers can create a broker with custom supported api versions.
=> feat: add method MockApiVersionsResponse.SetApiKeys

README.md, dev.yml, utils.go
=> Add Kafka 3.1.0 version number

CHANGELOG.md
Note that I added `Version 1.31.1 (2022-02-01)` that I intend to cut today.
=> Backport missing changelog entries from 1.28 onwards

consumer_test.go
rework this test to be a bit more reliable and wait for the expected
message receipts at each stage of the test rather than handling them
separately in a goroutine, which was sensitive to timing and made the
test a little flakey
=> fix: rework RebalancingMultiplePartitions test

functional_consumer_test.go, functional_test.go
One of the pieces of #1695 was to use a small jar for publishing
uncommited messages as part of the functional test. Replacing that with
the native Sarama transactional producer
Fixes #1733
Co-authored-by: @KJTsanaktsidis
=> fix(test): use Sarama transactional producer

Makefile
Seeing some memory issues on the GitHub actions workers so disabling parallel until we can learn more
=> chore: restrict to 1 parallel test at once

record_test.go
`TestRecordBatchDecoding` was sporadically failing for me on main (6d970c751edfe80a21c91376ce749070541e4352).  This test command normally brings out the failure:
```
go test -p 2  -run 'TestRecordBatch.*' -count 10
--- FAIL: TestRecordBatchDecoding (0.00s)
record_test.go:291: invalid decode of snappy compressed record
got {FirstOffset:0 PartitionLeaderEpoch:0 Version:2 Codec:snappy CompressionLevel:0 Control:false LogAppendTime:false LastOffsetDelta:0 FirstTimestamp:2016-11-22 20:49:55 +0000 GMT MaxTimestamp:1970-01-01 01:00:00 +0100 BST ProducerID:0 ProducerEpoch:0 FirstSequence:0 Records:[<*>(0xc00020e0e0){Headers:[<*>(0xc000210090){Key:[8 9 10] Value:[11 12]}] Attributes:0 TimestampDelta:5ms OffsetDelta:0 Key:[1 2 3 4] Value:[5 6 7] length:{startOffset:0 length:0}}] …
```
=> fix: TestRecordBatchDecoding failing sporadically

Makefile, functional_producer_test.go
Just a simple test to kill broker connectivity whilst the producer is
in-use and confirm that it is able to successfully recover.
=> feat(test): add an fvt for broker deadlock

consumer.go
(from @pavius)
The first few fetches from Kafka may only fetch data from one or two partitions, starving the rest for a very long time (depending on message size / processing time)
Once a member joins the consumer groups and receives its partitions, they are fed into the "subscription manager" from different go routines. The subscription manager then performs batching and executes a fetch for all the partitions. However, it seems like the batching logic in `subscriptionManager` is faulty, perhaps assuming that `case:` order prioritizes which `case` should be handled when all are signaled which is not the case, according to the go docs (https://golang.org/ref/spec#Select_statements):
```
If one or more of the communications can proceed, a single one that can proceed is chosen via a uniform …
```
=> fix: avoid starvation in subscriptionManager

broker.go, errors.go, errors_test.go
The SASL Authentication response message from Kafka has an additional field which can contain a description of why the authentication failed. Currently we drop this in Sarama and just return a generic message based on the kError code.
=> fix: return underlying sasl error message

version.go
Running `go test -race` on some integration tests with Sarama trigger a data race warning:
```
WARNING: DATA RACE
Read at 0x0001052f7940 by goroutine 11:
github.com/Shopify/sarama.version()
/Users/pior/pkg/mod/github.com/!shopify/sarama@v1.32.0/version.go:8 +0x34
github.com/Shopify/sarama.(*Broker).Open.func1.1()
/Users/pior/pkg/mod/github.com/!shopify/sarama@v1.32.0/broker.go:183 +0x44
github.com/Shopify/sarama.(*Broker).Open.func1()
/Users/pior/pkg/mod/github.com/!shopify/sarama@v1.32.0/broker.go:245 +0x1368
github.com/Shopify/sarama.withRecover()
/Users/pior/pkg/mod/github.com/!shopify/sarama@v1.32.0/utils.go:43 +0x54
```
```
Previous write at 0x0001052f7940 by goroutine 12:
github.com/Shopify/sarama.version()
/Users/pior/pkg/mod/github.com/!shopify/sarama@v1.32.0/version.go:16 +0xec …
```
=> fix: potential data race on a global variable

message.go, message_test.go
This allows the user to include a CompressionCodec in a structure to
be unmarshaled from a configuration file using YAML/JSON/whatever.
=> feat(message): add UnmarshalText method to CompressionCodec

async_producer.go, async_producer_test.go
Since async producer now support multiple inflight messages
thanks to https://github.com/Shopify/sarama/pull/1686 and https://github.com/Shopify/sarama/pull/2094, it now may "leak"
the "fin" internal management message to Kafka (and to the client)
when broker producer is reconnecting to Kafka broker and retries
multiple inflight messages at the same time.
Steps to reproduce: start async producer and restart Kafka broker (potentially multiple times). 
This trigger leader update and retires current broker producer.
There's a chance that newly created broker producer is used to retry an
inflight message so it is also marked as "dying" but it does not contain
any explicit errors.
This results in a "fin" message to be sent to Kafka and reported as successful
operation to the client.
Versions …
=> producer: ensure that the management message (fin) is never "leaked"

consumer_group.go
https://github.com/Shopify/sarama/pull/2110 was merged to avoid stopping heatbeats on rebalance. 
However, the change is not as effective as it could be since session context is canceled on rebalance (which results in the recreation of the session in the end).
This patch allows session consumer to continue its life if heartbeat loop detected rebalance event.
=> consumer-group: do not cancel sessions context during rebalance

.github/workflows/fvt.yml, Makefile, functional_test.go, utils.go, utils_test.go
use separate 2m timeout for standard unittests
=> chore: bump functional test timeout to 12m

client.go, client_test.go
#2202 exposes a goroutine test in the client's `RefreshBrokers` API. 
On analysis I see that `RefreshBrokers` implementations leak the original seed brokers and the test itself was leaking a client.  This PR resolves both issues.
=> fix: prevent RefreshBrokers leaking old brokers 

client.go
As exposed by #2202, the `RefreshController` API leaks the broker that was in the controller role.
=> fix: prevent RefreshController leaking controller

broker.go, broker_test.go, mockresponses.go, sasl_authenticate_request.go, sasl_authenticate_request_test.go, sasl_authenticate_response.go, sasl_authenticate_response_test.go
Proposed fix for #2060.
If the server uses KIP-368, the client will cause itself to reauthenticate by emitting the necessary SASL handshake/authenticate with the next client to server interaction.
```
2022/03/29 18:09:50 Completed pre-auth SASL handshake. Available mechanisms: [PLAIN OAUTHBEARER]
2022/03/29 18:09:50 Session expiration in 299000 ms and session re-authentication on or after 283079 ms
```
=> KIP-368 : Allow SASL Connections to Periodically Re-Authenticate

broker.go
Broker register metrics name to `registeredMetrics` and then
authenticate to broker by socket, when authenticate failed many times,
the `registeredMetrics` is slice and will append a metrics name many
times
Fixes #1960
=> fix: prevent metrics leak when authenticate fails 

consumer.go, functional_consumer_test.go
Since subscription manager was improved to batch the subscriptions (see https://github.com/Shopify/sarama/pull/2109/commits/dadcd808a5f6c6394e91f6a614818cf8eab732de)
it created a deadlock in the case when new subscription are added after a rebalance.
After a rebalance, the subscription is [stuck](https://github.com/Shopify/sarama/blob/dadcd808a5f6c6394e91f6a614818cf8eab732de/consumer.go#L915) on pushing to the `wait` channel, which is drained only if there are no active subscriptions.
=> fix: prevent deadlock between subscription manager and consumer goroutines

async_producer.go, async_producer_test.go
Add check for idempotent producer epoch overflow, as it is required by the
[KIP-360](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=89068820), the producer should request a new producer ID when the epoch
is exhausted. Otherwise, the producer might get desynchronized with the
broker.
[AK producer](https://github.com/apache/kafka/blob/df2236d73bc630a588adc049e7e63a4a5095da32/clients/src/main/java/org/apache/kafka/clients/producer/internals/TransactionManager.java#L580) for reference
Similar issue to https://github.com/edenhill/librdkafka/issues/3720
=> fix: prevent idempotent producer epoch exhaustion

admin.go, admin_test.go
Also prevent a few other creations of new errors where the existing
KError should have been preserved for errors.Is checking.
Fixes #2225
=> fix(admin): make DeleteRecords err consistent

.gitignore, Makefile
Try out mfridman/tparse in the CI for the various quality of life
improvements it gives us around readability of test results
=> chore(ci): experiment with using tparse

describe_groups_response.go, describe_groups_response_test.go
As we currently expose this directly in the response from admin.go it
makes sense to document the struct fields using the text included in the
kafka json protocol description. Whilst checking the protocol
implementation against the specs, I worked these in.
=> fix(protocol): tidyup DescribeGroupsResponse

balance_strategy.go, balance_strategy_test.go
https://kafka.apache.org/31/javadoc/org/apache/kafka/clients/consumer/RangeAssignor.html
=> fix: range balance strategy not like reference

Makefile
If GITHUB_STEP_SUMMARY isn't set then the redirect should be to
/dev/null, even if it isn't called the shell parser will complain
=> chore(ci): fix redirect with GITHUB_STEP_SUMMARY

version.go
As we send the version in our ApiVersionsRequest as the
ClientSoftwareVersion we need to make sure it is considered valid by
Kafka by conforming to their version regex
=> fix: ensure empty or devel version valid

.github/workflows/cla.yml
Hello 👋
We are deprecating probot usage, so all Shopify repos should be migrated to use new [GitHub CLA Action](https://github.com/Shopify/shopify-cla-action).
You can see how this works in [vscode-shopify-ruby repo](https://github.com/Shopify/vscode-shopify-ruby/pull/171).
If you have any questions, please reach us [on Slack](https://shopify.slack.com/archives/C03FLDE8SLB).
1. Go to `Settings > Branches > Edit main (or any default) branch`
2. Remove the CLA check from probot (click `x`): <img width="733" alt="image" src="https://user-images.githubusercontent.com/899452/179303783-1b5b8084-3e91-4b72-b857-916b63cdb07c.png">
3. Add CLA check from GitHub action: <img width="731" alt="image" src="https://user-images.githubusercontent.com/899452/179303840-1257d0bf-ee34-4f35-b461-a5956d79d2e1.png …
=> Migrate off probot-CLA to new GitHub Action

.github/workflows/fvt.yml, Dockerfile.kafka, docker-compose.yml, entrypoint.sh, functional_test.go, utils.go, utils_test.go
Bump default fvt version to 3.1.1 as well.
=> chore: add kafka 3.1.1 to the version matrix

.golangci.yml, admin_test.go, async_producer_test.go, broker.go, client.go, delete_offsets_response.go, functional_consumer_test.go, mocks/async_producer.go, offset_commit_response_test.go, partitioner_test.go, records.go
=> chore(lint): re-enable a small amount of go-critic

config.go, consumer_group.go
When consuming a partition using a consumer group, the code
handles ErrOffsetOutOfRange errors by resetting to the "initial"
position, as specified by user (i.e. either oldest or newest available
offset). This, however, can be very dangerous. Say a consumer has
consumed up to offset 100 on replica A but replica B has only
replicated up to offset 99 due to temporary under-replication. During
a rebalance, sarama can end up with an offset out-of-range error if it
fetches partition metadata from replica B since the desired offset of
100 is greater than the newest offset of 99. The sarama consumer would
reset the offset in this case, which can cause reprocessing of old
data, especially if the initial offset is configured as "oldest".
This commit adds a config flag to disable this automatic …
=> feat: add option to propagate OffsetOutOfRange error

consumer.go
I'm submitting a purpose in order to address this [issue](https://github.com/Shopify/sarama/issues/2125)
=> fix(consumer): avoid submitting empty fetch requests when paused

balance_strategy.go, broker.go, broker_test.go, consumer_group_members_test.go, consumer_metadata_response_test.go, describe_groups_response.go, encoder_decoder.go, fetch_request.go, fetch_response.go, functional_producer_test.go, join_group_response.go, message_test.go, metrics_test.go, packet_decoder.go, real_decoder.go, record_batch.go, records_test.go, request.go, request_test.go, sarama.go, sync_group_response.go
In additional to the global request rates, split out the fetch request
rates for consumers.
- consumer-fetch-rate
- consumer-fetch-rate-for-broker-X
- consumer-fetch-rate-for-topic-Y
- consumer-fetch-response-size
=> feat(metrics): track consumer fetch request rates

consumer.go
This PR addresses [this issue](https://github.com/Shopify/sarama/issues/2316).
Signed-off-by: Panos Koutsovasilis <koutsobill@hotmail.com>
=> fix(consumer): avoid pushing unrelated responses to paused children

consumer_test.go, mockresponses.go
While working with `MockBroker`, I found out that this mock doesn't support key in the message for `FetchRequest`. In my case having key mocked is essential as in the project I'm working on, we rely on the parsed key from Kafka message.
I added the support and added the test for this behavior.
=> feat: support key in MockFetchResponse.

config.go, consumer_group.go, consumer_group_test.go, examples/consumergroup/main.go, functional_consumer_group_test.go
As shown below, Kafka supports specifying multiple rebalance protocol from the very begining. ([source](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-PossibleErrorCodes:~:text=all%20client%20implementations.-,Join%20Group%20Request,-The%20join%20group))
```
v0 supported in 0.9.0.0 and greater
JoinGroupRequest => GroupId SessionTimeout MemberId ProtocolType GroupProtocols
GroupId => string
SessionTimeout => int32
MemberId => string
ProtocolType => string
GroupProtocols => [ProtocolName ProtocolMetadata]
ProtocolName => string
ProtocolMetadata => bytes
v1 supported in 0.10.1.0 and greater
JoinGroupRequest => GroupId SessionTimeout MemberId ProtocolType GroupProtocols
GroupId => string
SessionTimeout => int32
RebalanceTimeout => …
```
=> feat(consumer): support multiple balance strategies

consumer_group.go
We encounter a data race issue when closing consumer group.
*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
| Sarama | Kafka | Go |
|--------|-------|----|
| 1.36.0 | 2.8.1  | 1.17.7 |
<details><summary>logs: CLICK ME</summary>
<p>
```
WARNING: DATA RACE
Write at 0x00c000f448b0 by goroutine 750:
runtime.closechan()
/Users/xxxxxxxxx/.gvm/gos/go1.17.7/src/runtime/chan.go:355 +0x0
github.com/Shopify/sarama.(*consumerGroup).Close.func1.1()
/Users/xxxxxxxxx/go/pkg/mod/github.com/!shopify/sarama@v1.36.0/consumer_group.go:161 +0x44
Previous read at 0x00c000f448b0 by goroutine 1238:
runtime.chansend()
/Users/xxxxxxxxx/.gvm/gos/go1.17.7/src/runtime/chan.go:158 +0x0
github.com/Shopify/sarama.(*consumerGroup).handleError() …
```
=> fix: race condition(may panic) when closing consumer group

config.go
A number of people have reported issues with the change in default behaviour that was introduced in #2252 and the comment for this configuration value had suggested it would retain the behaviour of previous Sarama versions. This PR puts the default behaviour back to resetting to `c.Consumer.Offsets.Initial` when the server returns an out of range error on a Fetch.
Contributes-to: #2342
=> fix(consumer): default ResetInvalidOffsets to true

.github/workflows/fvt.yml, Dockerfile.kafka, docker-compose.yml, entrypoint.sh, functional_test.go, utils.go
- also populate utils.go with versions matrix
=> chore(ci): bump kafka-versions to latest

mocks/async_producer.go, mocks/async_producer_test.go, mocks/consumer.go, mocks/consumer_test.go, mocks/sync_producer.go, mocks/sync_producer_test.go
Normally this happens during creation of the `Client`, but for mock
interfaces there is no `Client`.
=> Validate the `Config` when creating a mock producer/consumer

config.go
see https://github.com/Shopify/sarama/issues/2351
=> fix: support existing deprecated Rebalance.Strategy field usage

async_producer.go
Sarama allows [several options](https://github.com/Shopify/sarama/blob/v1.37.0/config.go#L229-L247) to control how often to flush a batch of messages to brokers. It utilizes [`time.After`](https://github.com/Shopify/sarama/blob/v1.37.0/async_producer.go#L972) to control the frequency of a flush. However, it would cause high memory usage in some cases.
I've written the following example with `Flush.Messages = 1` and `Flush.Frequency = time.Second * 60` to demonstrate it. In practice, the situation could be even worse since there could be **multiple broker producers** in one producer and **multiple producers** in one instance/machine.
```
func TestProducerMemory(t *testing.T) {
var mem runtime.MemStats
topic := "mem-test-topic"
config := NewConfig()
config.Producer.Flush.Messages = 1 …
```
=> fix(producer): replace time.After with time.Timer to avoid high memory usage

client.go
As per golang/go#41970 any 64-bit variable that is accessed atomically must be 64-bit aligned and this can be ensured by making it the first entry in the struct.
Fixes #2337
=> fix: ensure updateMetaDataMs is 64-bit aligned

zstd.go, zstd_test.go
Currently a single zstd encoder with default concurrency is used. Default concurrency causes EncodeAll to create one encoder state per GOMAXPROC - per default per core.
On high core machined (32+) and high compression levels (32MB / state) this leads to 1GB memory consumption per ~32 cores. A 1GB encoder is pretty expensive compared to the 1MB payloads usually sent to kafka.
The new approach limits the encoder to a single core but allows dynamic allocation of additional encoders if no encoder is available. Encoders are returned after use, thus allowing for reuse, with a limit of 1 spare encoder to limit memory overhead.
A benchmark emulating a 96 core system shows the memory effectiveness of the change.
Previous result:
```
goos: linux
goarch: amd64
pkg: github.com/Shopify/sarama
cpu: …
```
=> feat: improve memory usage of zstd encoder by using our own pool management

admin.go, async_producer_test.go, client.go, metadata_request.go, metadata_response.go, request.go
In order to receive the LeaderEpoch as part of the metadata response we need to be sending and receiving version 7 of the
MetadataRequest+Response protocol. Luckily the first flexible version wasn't until v8 so the changes to achieve this are minimal.
Contributes-to: #2365
=> feat(proto): implement and use MetadataRequest v7

client.go, consumer.go, fetch_request.go, fetch_request_test.go, fetch_response.go
Include the consumer's view of the leader in Fetch requests as per KIP-320
Contributes-to: #2365
=> fix: track and supply leader epoch to FetchRequest

zstd.go
After upgrading Sarama from 1.27.0 to 1.37.2, we noticed a significant performance regression in one of our services. This service runs on a very large (96 CPU) instance, and normally processes about 120K messages/sec. After the upgrade, it could only do about half that.
We traced the issue to [this change](https://github.com/klauspost/compress/pull/498) in klauspost/compress. Since Sarama uses the defaults when creating a new reader, concurrency is limited to 4.
By setting `WithDecoderConcurrency(0)`, concurrency is set to `GOMAXPROCS` (which in our app is set to `runtime.NumCPU()` == 96. When we deployed our service with this change, our performance issue disappeared.
=> fix(zstd): default back to GOMAXPROCS concurrency

async_producer.go
The function `newHighWatermark` send fin message to the input channel; it might panic when the `pp.brokerProducer` is `nil`. I added a simple check to fix it. Please help double-check if there are any unwanted side effects when you have time. Thanks a lot!
=> fix: add nil check while producer is retrying

.github/workflows/ci.yml, .github/workflows/fvt.yml, Dockerfile.kafka, docker-compose.yml, entrypoint.sh, utils.go
- drop 3.0.x series from fvt runs
- add kafka version constants for 3.3.0 and 3.3.1
- default to 3.3.1 in docker-compose
=> chore: include kafka 3.3.1 in testing matrix

async_producer.go, async_producer_test.go
This fixes https://github.com/Shopify/sarama/issues/2377
=> fix(producer): return errors for every message in retryBatch to avoid producer hang forever

consumer_group.go
fix the issue of consumergroup not closing properly when calling consumergroup.close()
currently, the NewConsumerGroup method calls the NewConsumerFromClient method which creates a nopclient, and thus this client cannot be closed properly
Replaces https://github.com/Shopify/sarama/pull/2423
=> fix: use newConsumer method in newConsumerGroup method

consumer_group.go, consumer_group_test.go
If the consumer group hit an error finding the coordinator whilst setting up a session it would end up retrying forever because the retry count didn't get decremented and there was no exit of the loop. Fix that up and add a unittest to cover the scenario
Fixes #2426
=> fix(consumer): don't retry FindCoordinator forever

broker.go
On failure, `Broker.Open()` can be called several times while a producer is running. In #2409, it was assumed that AsyncProduce can only be called with an open broker, however, it should be read that a user should call it after opening the broker. The broker could be disconnected and in progress of being reconnected. This is not hard to fix as we already have a lock protecting the creation of the registry: just don't create a new metric registry when attempting to reopen the broker.
Fix #2320 (again)
=> fix(metrics): fix race condition when calling Broker.Open() twice

admin.go, describe_groups_request.go, describe_groups_response.go
=> #2443 Use version 4 of DescribeGroupsRequest only if kafka broker version is > 2.4.0.0

balance_strategy.go, balance_strategy_test.go, config.go, config_test.go, examples/consumergroup/main.go, examples/exactly_once/main.go, functional_consumer_group_test.go
For every `BalanceStrategy`, it may be shared across different consumer groups in one instance. Considering every built-in balance strategy has several fields in the struct as shown in the below snippet, data race issues may happen when several consumer group rebalances simultaneously.
```
type balanceStrategy struct {
coreFn func(plan BalanceStrategyPlan, memberIDs []string, topic string, partitions []int32)
name   string
}
type stickyBalanceStrategy struct {
movements partitionMovements
}
```
Even worse, I think this issue could cause
- panic
- some topics/partitions are not subscribed by the corresponding consumers, because the corresponding fields in the struct may be modified by other consumer groups
To verify this issue, a unit test was written, which fails when -race detection is …
=> fix: prevent data race in balance strategy

offset_commit_request.go, offset_commit_request_test.go, offset_manager.go
In v1.34.0 a breaking API change to (*OffsetCommitRequest) AddBlock was inadvertently introduced by 59a3d39
We weren't aware that anyone was driving the offset commit protocol directly via the broker.go call rather than via offset_manager.go (or via a consumer client)
For now we restore the old AddBlock signature and move the new one to AddBlockWithLeaderEpoch. This will unfortunately impact anyone who had updated their own code to call the new func signature, but it's probably more important that we restore the longer term backwards compatibility now until we move to a v2 release.
Fixes #2358
=> fix: restore (*OffsetCommitRequest) AddBlock func

.github/workflows/apidiff.yml
In order to try and prevent breaking changes to the API going forward, add a simple call to the cmd wrapper of
https://pkg.go.dev/golang.org/x/exp/apidiff
=> chore(ci): add simple apidiff workflow

.github/workflows/ci.yml, .golangci.yml
Hi 👋 
Good luck with the project ownership!
In this PR:
* Bumped the `golangci` version to `v1.53.3`
* Changed the `local-prefixes` to IBM
* Commented out [deprecated](https://golangci-lint.run/usage/linters/#disabled-by-default) linters (replaced by `unused `)
* Added some basic `depguard` configs - don't allow `io/ioutil`
=> chore(ci): bump golangci version, cleanup, depguard config

Dockerfile.kafka, acl_create_request_test.go, acl_describe_request.go, acl_types.go, add_partitions_to_txn_request.go, async_producer.go, balance_strategy.go, broker.go, client.go, client_test.go, consumer_group.go, describe_configs_request_test.go, errors.go, heartbeat_request_test.go, join_group_response_test.go, message_test.go, offset_manager.go, packet_decoder.go, sarama.go, sync_producer.go, tools/kafka-producer-performance/main.go, transaction_manager.go
Fix obsolete reference to `ioutil.Discard` in docs.
Fix duplication of defaults in `tools/kafka-producer-performance` help output (flag output already includes the defaults without explicitly documenting them).
Fix some typos spotted while reading the code.
=> Clean up some typos and docs/help mistakes

admin.go, admin_test.go, client.go
This fixes #2515.
It also fixed similar off-by-one errors in logging in client.go.
I specifically didn't fix the four off-by-one logging errors in transaction_manager.go since it looks to me like the number of attempts also has off-by-one errors (e.g. [here](https://github.com/IBM/sarama/blob/6ecdb50a30c3f2897be5e863aa7c854781e389be/transaction_manager.go#L299)) so technically until that logic is fixed they are correct.
=> Fix some retry issues

admin.go, admin_test.go
The previous fix in #2515 wasn't correct. While looking at the transaction_manager.go logic, it became clear that the intention is that retry.max should not count the first attempt. This seems very reasonable so this fixes the test and logic to reflect that. The original code would fail this updated test because it didn't make the final required attempt.
It seems like it might be a good idea to have a single retry mechanism to implement all of the requirements of the Config...Retry configs. It might be a v2 issue as the Retry configs aren't currently consistent - some don't have BackoffFunc and those that do take different numbers of arguments.
=> fix: admin retry logic

decompress.go
While profiling my application, I've noticed that Sarama spends a significant amount of time growing slices when it's decompressing messages:
This patch uses an intermediate buffer from a  pool for decompression, to avoid these allocations.
When the final size is know, the result buffer can be allocated and copied.
After the patch:
=> Use buffer pools for decompression

config.go, config_test.go, gssapi_kerberos.go, kerberos_client.go, kerberos_client_test.go
Implemented the support for Kerberos authentication using a credentials cache, as described in #2421.
This adds a KRB5_CCACHE_AUTH value for GSSAPIConfig.AuthType.
=> feat: support for Kerberos authentication with a credentials cache.

admin.go
Contrary to the discussion [here](https://github.com/IBM/sarama/pull/1617#discussion_r385132244), you can use the retryOnError function when you are returning results by using a closure to capture the results. This PR wraps a few more functions with retry logic.
I stopped before doing any more in part because I was distracted by the inconsistent use of 'Acls', 'ACLs', etc in variables and function names.  :-) (Something else for v2 perhaps).
I also wondered about the fact that the retryOnError function currently only checks for isNotControllerError *and* many of the functions that it wraps also check the error since they need to refresh the controller. Perhaps it would be better to make simpler retryOnError function like:
```
func (ca *clusterAdmin) retryOnError(fn func() (bool, error)) …
```
=> Add some retry logic to more admin client functions

functional_consumer_test.go
This test is currently skipped but I was planning to look at flakiness in the functional tests so I thought I'd make this one not panic due to nil txnmgr.
=> fix(test): allow testing of skipped test without IsTransactional panic

functional_test.go
Potential workaround for issues like #2529. It would be good to understand the root cause though.
=> fix(fvt): ensure fully-replicated at test start

metadata_request.go
Version 8 is unsupported since the existing code doesn't support the fields IncludeClusterAuthorizedOperations and IncludeTopicAuthorizedOperations required by that version.
=> fix: correct unsupported version check

consumer.go
Sarama has addressed the issue of submitting empty fetch requests after calling `PauseAll`, as seen in [#2143](https://github.com/IBM/sarama/issues/2143). However, there is still a CPU utilization problem.
The root cause lies in two operations:
1. In [`subscriptionConsumer`](https://github.com/IBM/sarama/blob/v1.40.1/consumer.go#L924-L965), if `response` is nil, it immediately attempts to [fetch](https://github.com/IBM/sarama/blob/v1.40.1/consumer.go#L945) from the `bc.newSubscriptions` channel.
2. In [`subscriptionManager`](https://github.com/IBM/sarama/blob/v1.40.1/consumer.go#L883C27-L920), it continuously sends `nil` to `bc.newSubscriptions`.
These two operations alternate indefinitely until a rebalance or until `ResumeAll/Resume` is called. Consequently, this leads to the CPU burn …
=> fix: avoiding burning cpu if all partitions are paused

client.go, config.go
This PR allows specifying the equivalent of `client.dns.lookup=resolve_canonical_bootstrap_servers_only`, described in [KIP-235][]. The motivation is identical to the one in the proposal: the lack of this feature effectively mandates providing individual canonical broker hostnames when using GSSAPI, rather than a single alias which resolves to the same underlying IPs. This increases the likelihood of errors, and commits application owners to checking for new and removed brokers on an ongoing basis.
[KIP-235]: https://cwiki.apache.org/confluence/display/KAFKA/KIP-235%3A+Add+DNS+alias+support+for+secured+connection
The Java client implementation for this can be found [here](https://github.com/apache/kafka/blob/3.1.0/clients/src/main/java/org/apache/kafka/clients/ClientUtils.java#L62-L71). …
=> Implement resolve_canonical_bootstrap_servers_only

broker.go, broker_test.go
This is a fairly simple approach to implement [KIP-219](https://cwiki.apache.org/confluence/display/KAFKA/KIP-219+-+Improve+quota+communication), but I couldn't think of any reason why it shouldn't be sufficient.
=> feat: sleep when throttled (KIP-219)

.github/workflows/fvt.yml, Dockerfile.kafka, utils.go
Also add KafkaVersion constants in utils.go
=> chore: rollup fvt kafka to latest three

consumer_group.go
Use the correct version and format of LeaveGroup as determined by the configured Version field.
Fixes #2486
=> fix(consumer): use newer LeaveGroup as appropriate

broker.go, list_groups_request.go, list_groups_request_test.go, list_groups_response.go, list_groups_response_test.go
This adds support for versions 1 through 4 of the [ListGroups API](https://kafka.apache.org/protocol.html#The_Messages_ListGroups).
A compromise for backwards compatibility is the addition of a new `GroupsData` field to the list groups response, leaving the existing `Groups` field unchanged:
```go
type ListGroupsResponse struct {
Version      int16
ThrottleTime int32
Err          KError
Groups       map[string]string    // <- existing field group_id -> protocol_type
GroupsData   map[string]GroupData // <- new field added by this PR
}
type GroupData struct {
GroupState string
}
```
A more faithful, yet incompatible, rendering for this part of the Kafka protocol (see below) would have been to change the type of the existing `Groups` field to be a map of `string` (group ID) to a `struct` …
=> Add support for up to version 4 List Groups API

tools/kafka-producer-performance/main.go
For short test runs `kafka-producer-performance` may not print any metrics at all. This is fixed by moving the final call to `printMetrics` just before closing the producer. Calling `printMetrics` after the producer is closed does nothing as the producer metrics are unregistered as part of the close.
=> Fix printing of final metrics

describe_configs_request.go, describe_configs_response.go, request_test.go
Add a test to ensure that the requiredVersion of the request and response pairs matches. Accordingly fix DescribeConfigs which had a V1_0_0_0 instead of V1_1_0_0 bug for V1 in the Response
=> fix(proto): ensure req+resp requiredVersion match

admin.go, create_partitions_request.go, create_partitions_response.go, describe_configs_request.go, describe_configs_response.go, request_test.go
This is identical in format to V0, but just influences the broker's response behaviour:
> starting in version 1, on quota violation, brokers send out responses
> before throttling.
=> chore(proto): permit CreatePartitionsRequest V1

admin.go, alter_configs_request.go, alter_configs_response.go, create_partitions_request.go, create_partitions_response.go, delete_groups_request.go, delete_groups_response.go, describe_configs_request.go, describe_configs_response.go, request_test.go
This is identical in format to V0, but just influences the broker's response behaviour
=> chore(proto): permit DeleteGroupsRequest V1

broker_test.go
This test can fail at the moment because the timer is set up (slightly) before we start measuring the wait.
=> fix(test): test timing error

async_producer_test.go, client_test.go, metadata_request.go, metadata_response.go, sync_producer_test.go, transaction_manager_test.go
Even though most of these are identical, we may as well match up correctly.
=> fix(proto): use full range of MetadataRequest

.github/workflows/apidiff.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/fuzz.yml, .github/workflows/fvt.yml, .github/workflows/stale.yml
- use consistent `on:` triggers across all
- remove `if:` clause that left "Skipping xyz action..." in the status checks, not sure why we were doing that rather than just limiting push builds to `main`
- yamlfmt
=> chore(ci): tidyup and improve actions workflows

admin.go, client.go, consumer_group.go, heartbeat_request.go, heartbeat_response.go, leave_group_request.go, leave_group_response.go, offset_fetch_request.go, offset_fetch_response.go
Continuing to make use of higher versions where available (even if identical) to be more compliant with the spec
=> fix(proto): use fuller ranges of supported proto

consumer_group.go, functional_consumer_group_test.go, functional_test.go
fix #2562 
A functional test is provided as well, which will fail in the old versions. (if u simply copy the new test to the older version, plz also remember to copy [this line](https://github.com/IBM/sarama/pull/2563/files#diff-6dc37cfd96e85af03c7f31398c791c686048539779e71fee06011dcd3d866fafR409))
btw, this also fixes #2460
=> fix(consumer): cannot automatically fetch newly-added partitions unless restart

partitioner.go, partitioner_test.go
See https://github.com/IBM/sarama/issues/2430 for a discussion of the issue.  Relevant items from that issue are copied here for visibility:
There is a difference between how sarama partitions when using the Crc32 hash and what is done in librdkafka (and ruby-kafka). It looks like this issue was reported some time ago but nothing came of it (https://github.com/IBM/sarama/issues/1213). The main issue is that librdkafka/ruby-kafka treat the hashed value from Crc32 as an unsigned value, whereas sarama casts it to a signed value. However, when using other hashing algorithms, the signed cast is necessary.
=> bug: implement unsigned modulus for partitioning with crc32 hashing

config.go
If Go's logging implementation is plugged into Sarama then it will introspect the contents of the Dialer, potentially giving rise to concurrent access to a map used to implement the dialer.
Fixes #2547
=> fix: avoid logging value of proxy.Dialer

mockresponses.go
In mockresponses.go ensure we reply to a HeartbeatRequest with a matching Version of HeartbeatResponse
=> chore(proto): match HeartbeatResponse version

admin_test.go, mockresponses.go
Allow set Error for Delete Topic Mock Response
With this we can set up tests for error while deleting topics
=> feat: add new error for MockDeleteTopicsResponse

.github/workflows/apidiff.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/fuzz.yml, .github/workflows/fvt.yml
Also fixup golangci-lint caching behaviour
=> chore(ci): use latest Go in actions

async_producer_test.go, client_tls_test.go, config_test.go, consumer_group_test.go, consumer_test.go, functional_admin_test.go, functional_client_test.go, functional_consumer_follower_fetch_test.go, functional_consumer_group_test.go, functional_consumer_staticmembership_test.go, functional_consumer_test.go, functional_offset_manager_test.go, functional_producer_test.go, functional_test.go, mockbroker.go, mockresponses.go, mocks/async_producer_test.go, mocks/mocks.go, mocks/sync_producer_test.go, sarama_test.go
- make consumer and produce retries zero backoff
- use parallel on TLS test
- reduce mockbroker noise
- add mockresponses support for per-topic Err in MetadataResponse
- use microseconds in test debug logger
=> chore(test): speedup some slow tests

admin_test.go, sync_producer_test.go
These clients must be closed after use.
=> chore(test): fix a couple of leaks

Dockerfile.kafka, docker-compose.yml, entrypoint.sh, functional_test.go
Switch to templating the Dockerfile and docker-compose so that each
image is uniquely named and contains just the kafka version specified.
This will make it easier to have a large matrix test for the main branch
whilst keeping the PR checks at 2 or 3 kafka versions
=> feat(fvt): experiment with per-kafka-version image

functional_producer_test.go, functional_test.go, internal/toxiproxy/README.md, internal/toxiproxy/client.go, internal/toxiproxy/proxy.go, internal/toxiproxy/toxic.go
The v2.5.0 client implementation happens to have a resource leak, and pulling in HEAD notably carries a large number of transitive dependencies that we don't really want to track in our go.mod just for FVT purposes. Therefore, knock up a minimal implementation of an http client for toxiproxy to satisfy our usage.
=> chore(ci): replace toxiproxy client dep

admin_test.go, functional_admin_test.go, functional_consumer_staticmembership_test.go
=> fix(test): add missing closes to admin client tests

compress.go, config.go, decompress.go, message_test.go, record_test.go, request_test.go
As suggested in #2359, use klauspost/compress for our gzip implementation as we're already using the module for other compression algorithms and benchmarks show 1.5x-7x improvement
=> feat(gzip): switch to klauspost/compress gzip

functional_producer_test.go, metrics_test.go
- update the TestFuncProducing tests to exercise a number of different client versions so we cover the old msgset (which the tests were originally written for) and batchset format, as well as all the currently supported versions of ProduceRequest
- relax some of the metrics validation to account for messages being sent in batches on the higher kafkaVersions
=> fix(fvt): handle msgset vs batchset

.github/workflows/fvt.yml, docker-compose.yml, functional_test.go
Update the docker-compose.yml to include healthchecks for toxiproxy and kafka and make the FV startup wait for them to become healthy.
=> feat(fvt): add healthcheck, depends_on and --wait

functional_test.go
- use correct metadata version for target kafka in ensureFullyReplicated
- skip full metadata and apiversionsrequest as we just want to check the test topics are fully replicated
=> fix(fvt): Metadata version in ensureFullyReplicated

.github/workflows/fvt.yml, functional_producer_test.go
- also use per-versioned test name clientID in testProducingMessages helper
=> fix(fvt): versioned cfg for invalid topic producer

functional_producer_test.go
Trying to nail down flakiness with the verification of metrics in these tests. Since adding the additional versions these have been flakey and I think the reason is that the registry is getting re-used between tests as it is only created fresh on a call to NewConfig
=> fix(fvt): fresh metrics registry for each test

.github/workflows/fvt-main.yml, .github/workflows/fvt-pr.yml, .github/workflows/fvt.yml
Run a larger FV against the main branch, whilst keeping the PR builds to a smaller subset of versions using GitHub actions re-usable workflows
https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-a-matrix-strategy-with-a-reusable-workflow
=> feat(fvt): test wider range of kafkas

tools/README.md
install using `go get` is deprecated. https://go.dev/doc/go-get-install-deprecation
=> chore: use go install for installing sarama tools

mocks/consumer.go
I tried to add the missing comments mentioned by #2374 though I'm not the original author. This PR only contains comment changes. Please help check if the change explains the function as desired. Thanks a lot!
=> fix(doc): add missing doc for mock consumer

async_producer.go
Since we already return a `ConfigurationError` on line 449 it should be reasonable to return one here rather than returning an error that suggests that the server has rejected the message.
Fixes #1225
=> fix: make clear that error is configuration issue not server error

admin.go
According to [KIP-554](https://cwiki.apache.org/confluence/display/KAFKA/KIP-554%3A+Add+Broker-side+SCRAM+Config+API), the AlterUserScramCredentialsRequest description states:
> It will be will be sent to the controller and will return NOT_CONTROLLER if the receiving broker is not the controller.
so this request should handle retries.
I also fix a typo in the error check function name for consistency.
=> fix: add retries to alter user scram creds

consumer_group.go, consumer_group_test.go
Quite minor, but passing a nil client into NewConsumerGroupFromClient would cause a panic. Add a simple guard to prevent that.
=> fix(consumer): guard against nil client

consumer_group.go, consumer_group_test.go
=> fix(consumer): don't retry session if ctx canceled

record_batch.go
This change aims to reduce pressure on GC by grouping allocations of records in a record batch.
=> perf: Alloc records in batch

admin_test.go, async_producer_test.go, client.go, client_test.go, consumer_test.go, functional_test.go, mockbroker.go, offset_manager_test.go, sync_producer_test.go
Seed brokers never change after client initialization. If the first seed
broker became stale (still online, but moved to other Kafka cluster),
Sarama client may use this stale broker to get the wrong metadata. To
avoid using the stale broker to do metadata refresh, we will choose the
least loaded broker in the cached broker list which is the similar to
how the Java client implementation works:
https://github.com/apache/kafka/blob/7483991a/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java#L671-L736
Contributes-to: https://github.com/IBM/sarama/issues/2637
=> fix: use least loaded broker to refresh metadata

utils.go
Fix compiling regular pattern redundantly to optimize CPU usage.
Fixes #2662
=> fix: pre-compile regex for parsing kafka version

client.go, client_test.go, client_tls_test.go, offset_manager_test.go, sync_producer_test.go
We should skip the metadata refresh if the startup phase broker returns empty brokers in metadata response. The Java client skips the empty response to update the metadata cache (https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java#L1149) and we should make a feature parity in Sarama too
Fixes #2664
=> fix(client): ignore empty Metadata responses when refreshing

.github/dependabot.yml, .github/workflows/apidiff.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/dependency-review.yml, .github/workflows/fuzz.yml, .github/workflows/fvt-main.yml, .github/workflows/fvt-pr.yml, .github/workflows/fvt.yml, .github/workflows/stale.yml, .pre-commit-config.yaml
Various hardening commits to improve [ossf scorecard](https://securityscorecards.dev/viewer/?uri=github.com/IBM/sarama) result
=> chore(ci): improve ossf scorecard result

.github/workflows/codeql-analysis.yml
Scorecard checks expect that every commit is checked, regardless of content. The check is fairly quick to run so just go ahead and always run it.
=> fix(ci): always run CodeQL on every commit

.github/workflows/fuzz.yml, encoder_decoder_fuzz_test.go, fetch_request.go, record_batch.go
Explore what's possible with the fuzzer.
=> feat(test): add a simple fuzzing example

client.go
In production, we noticed that calling RefreshBrokers could take some time before closing the channels, which could cause a bottleneck on the producer.
This PR enables asynchronous closure of brokers (fire and forget) to make the client available as quickly as possible.
We have tested this modification in production, and the results have been satisfactory.
=> Asynchronously close brokers during a RefreshBrokers

broker.go
The underlying case was not waiting for the goroutine running the `responseReceiver()` method to fully complete if SASL authentication failed. This created a window where a further call to `Broker.Open()` could overwrite the `Broker.done` channel value while the goroutine still running `responseReceiver()` was trying to close the same channel.
Fixes: #2382
=> Fix data race on Broker.done channel

offset_manager.go, offset_manager_test.go
The retention time field of the offset commit request uses -1 to mean "use the broker's default". Sarama uses the value 0 in the `Config.Consumer.Offsets.Retenton` field to mean "use the broker's default". Ensure that Sarama's default (0) is correctly mapped to the broker's default (-1).
Fixes: #2677
=> Fix default retention time value in offset commit

admin.go, offset_fetch_request.go, offset_fetch_response.go, offset_fetch_response_test.go, offset_manager.go
The `fetchInitialOffset` func in offsetManager was hardcoded to send a Version 1 OffsetFetchRequest rather than sending the appropriate version based on the config KafkaVersion. As discussed in #2694 this meant that LeaderEpoch was always being decoded as the default value '0' (because it was only returned in Version >= 5 OffsetFetchRequest). However, other areas of the offsetManager code were sending the newer protocol versions, so for example the OffsetCommitRequest would include a leader epoch value of 0 rather than an accurate one.
Correct this bug by sending the correct protocol version in fetchInitialOffset and also ensure we default to `-1` when we decode an OffsetFetchResponse of a Version < 5
Fixes #2694
=> fix: make fetchInitialOffset use correct protocol

config.go, config_test.go, mocks/async_producer_test.go, mocks/consumer_test.go, mocks/sync_producer_test.go
The original validation regex was based on the one that existed in the Java clients pre-1.0.0 but KIP-190 removed the client-side validation because instead the brokers were updated to be able to cope with any clientID and sanitize it before using it in metrics etc.
We can do similar in Sarama and only do client-side validation when the user has specified a version number older than 1.0.0
Fixes #2697
=> fix(config): relax ClientID validation after 1.0.0

consumer_group.go
This PR optimizes new session initialization in case of client with empty member id. There is no need to backoff before sending another join request with assigned id.
=> fix: don't waste time for backoff on member id required error

consumer_group.go
If context isn't cancelled, ConsumerGroup.Close can indefinitely lock on waiting for `c.lock` inside `c.leave()` which is holden by the `Consume` method.
=> fix: prevent ConsumerGroup.Close infinitely locking

admin.go, alter_configs_response.go, describe_configs_response.go
return KError instead of errors in AlterConfigs and DescribeConfig, It's help for check error type, like grpc error code.
=> feat: return KError instead of errors in AlterConfigs and DescribeConfig

mockbroker.go
Some of the FV tests involve shutting down a MockBroker and then re-creating a new one on the same ip:port. Sometimes this fails because the port shows as still being in-use. Add some rudimentary retry attempts for this case to try and close the FV flakiness in that area.
=> fix(test): retry MockBroker Listen for EADDRINUSE

interceptors.go
Fixes https://github.com/IBM/sarama/issues/2801
=> Use %v formatting words and remove unnecessary newline

.github/workflows/apidiff.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/fuzz.yml, .github/workflows/fvt-main.yml, .github/workflows/fvt-pr.yml, .github/workflows/fvt.yml, examples/consumergroup/go.mod, examples/consumergroup/go.sum, examples/exactly_once/go.mod, examples/exactly_once/go.sum, examples/http_server/go.mod, examples/http_server/go.sum, examples/interceptors/go.mod, examples/interceptors/go.sum, examples/sasl_scram_client/go.mod, examples/sasl_scram_client/go.sum, examples/txn_producer/go.mod, examples/txn_producer/go.sum, go.mod
Bumping minimum Go version to 1.19, aligning with compress and other dependencies which now require 1.19
```
go get go@1.19
go mod tidy
go fix ./...
```
Also bump GitHub workflows to use latest 1.22 by default, and use 1.21 (N-1) and 1.19 as the additional unittest runs for stdlib compatibility.
=> feat: update go directive to 1.19

config.go
https://kafka.apache.org/documentation/#brokerconfigs_message.max.bytes
Says this default value should be `1048588`, not 1 megabyte (and also weirdly not 1 Mebibyte 🤷‍♀️ ) matching these expected values is important, as one language could publish an event that another language would then refuse to republish.
The produced error message `ConfigurationError(fmt.Sprintf("Attempt to produce message larger than configured Producer.MaxMessageBytes: %d > %d", size, p.conf.Producer.MaxMessageBytes)` is also poorly designed to allow for event handling of that message. It would require an `errors.As` followed by a `strings.HasPrefix(…)` which is really not what Go recommends to handle errors (that is, direct string manipulation, which is inherently fragile as the error string should be easily …
=> fix: message.max.bytes should default to 1048576 not 1 MB

.github/workflows/apidiff.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/dependency-review.yml, .github/workflows/fuzz.yml, .github/workflows/fvt.yml
We don't need actions/checkout to persist credentials for any submodules or other fetches. Whilst it is a read-only token, there's no need to leave it around on disk after the checkout has completed.
https://github.com/actions/checkout/blob/v4.1.1/action.yml#L48-L50
=> chore(ci): disable checkout credentials persist

broker.go
The producer can be easily blocked due to a race condition in Broker.throttleTimer, which may result in a panic. Consider changing the type of Broker.throttleTimer to atomic.Value
Fixes #2823
Signed-off-by: chengsha  <shacheng@tencent.com>
=> fix: add locking around broker throttle timer to prevent race condition

.github/workflows/i386.yml, mocks/consumer.go
- add a CI check that makes use of [SA1027](https://staticcheck.io/docs/checks#SA1027) from staticcheck which correctly detects alignment bugs when compiled for GOARCH=i386 (it doesn't find it when built under x86_64/arm64)
- align suppressedHighWaterMarkOffset to fix the issue reported in #2873
Fixes #2873
=> chore(ci): add 32-bit alignment check

.github/dependabot.yml, docker-compose.yml
also use docker's tini/init for FV containers
=> fix(ci): fix dependabot docker action

config.go
Fixed JVM config name for `MaxWaitTime` config in docs.
Incorrect JVM config: `fetch.wait.max.ms` <-- docs mention this.
[Correct JVM config](https://kafka.apache.org/36/documentation.html#consumerconfigs_fetch.max.wait.ms): `fetch.max.wait.ms`
=> fix(doc): correct JVM's config name corresponding to MaxWaitTime

offset_manager.go, offset_manager_test.go
Use the Broker.lock to prevent concurrent calls to commit from potentially being re-ordered between determining which offsets to include in the offset commit request, and sending the request to Kafka. This has the benefit that the lock is only held while the OffsetCommitRequest is sent, not for the period of time that Sarama is waiting for the response from the broker, improving the rate at which commit requests can be made.
The down side is that (without further re-factoring to the Broker) this change duplicates some of the code from the Broker into the offset manager. Potentially, making the code more fragile.
=> fix(consumer): maintain ordering of offset commit requests

.github/workflows/fvt.yml, docker-compose.yml
The base actions image no longer appears to include an old version of `docker-compose` so there's no thing to replace. Switch to installing `docker-compose` in a directory alongside the `docker` binary.
Also bump docker-compose to the latest release whilst making changes here.
=> fix(ci): correct docker-compose install

examples/consumergroup/go.mod, examples/consumergroup/go.sum, examples/exactly_once/go.mod, examples/exactly_once/go.sum, examples/http_server/go.mod, examples/http_server/go.sum, examples/interceptors/go.mod, examples/interceptors/go.sum, examples/sasl_scram_client/go.mod, examples/sasl_scram_client/go.sum, examples/txn_producer/go.mod, examples/txn_producer/go.sum, go.mod
The github.com/klauspost/compress recently [deprecated go 1.19](https://github.com/klauspost/compress/pull/926) and moved to a go 1.20 directive in go.mod
=> feat: update go directive to 1.20

.github/workflows/apidiff.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/fuzz.yml, .github/workflows/fvt-main.yml, .github/workflows/fvt-pr.yml, .github/workflows/fvt.yml, .github/workflows/i386.yml, .golangci.yml, Dockerfile.kafka, docker-compose.yml, entrypoint.sh, record_test.go, utils.go
- bump Go versions used in CI to baseline of 1.20.x and latest 1.23.x
- add newer Kafka version constants to utils.go
- bring newer Kafka versions into the FVT rotation and bump default to 3.6.2 in Dockerfile and docker-compose
- use newer ZooKeeper version in docker-compose too
=> chore: add newer kafka versions and bump Go in CI

broker.go
The same code is executed when the condition "err != nil" is true or false, because the code in the if-then branch and after the if statement is identical.
=> fix(lint): resolve IDENTICAL_BRANCHES issue in broker

broker.go
I'm trying to debug an issue and the logger is only logging:
`Error while performing SASL handshake kafka-1:9093` since the
actual error is not logged, it's not clear what went wrong.
Verified that the error doesn't contain sensitive data
Fixes #2994 
Addition reference: https://github.com/IBM/sarama/pull/2234#discussion_r1782313379
=> fix: log SASL connection and handshake errors

.github/workflows/fvt-main.yml, .github/workflows/fvt-pr.yml, .pre-commit-config.yaml, Dockerfile.kafka, utils.go
Also bump the 3.8 FV to use the 3.8.1 packages.
Will add Kafka 3.9.0 to the FV once it is available from: https://s3-us-west-2.amazonaws.com/kafka-packages
=> chore: add version consts for 3.8.1+3.9.0

async_producer.go, async_producer_test.go, config.go
This commit adds an optional configuration to Sarama's retry mechanism to limit the size of the retry buffer. The change addresses issues #1358 and #1372 by preventing unbounded memory growth when retries are backlogged or brokers are unresponsive.
Key updates:
- Added `Producer.Retry.MaxBufferLength` configuration to control the maximum number of messages stored in the retry buffer.
- Implemented logic to handle overflow scenarios, ensuring non-flagged messages are either retried or sent to the errors channel, while flagged messages are re-queued.
This enhancement provides a safeguard against OOM errors in high-throughput or unstable environments while maintaining backward compatibility (unlimited buffer by default).
Additionally, as demonstrated in the graph above, the retry buffer’s …
=> feat: Prevent retry buffer in AsyncProducer to go OOM

client.go, utils.go
1. extract the same logic in Replicas, InSyncReplicas, OfflineReplicas. Improve reusability, maintainability, and consistency
2. remove unnecessary local variable and misleading annotion. see https://github.com/IBM/sarama/issues/2923(#2923)
=> fix(client): refactor duplicated replica+partition logic

examples/consumergroup/go.mod, examples/consumergroup/go.sum, examples/exactly_once/go.mod, examples/exactly_once/go.sum, examples/http_server/go.mod, examples/http_server/go.sum, examples/interceptors/go.mod, examples/interceptors/go.sum, examples/sasl_scram_client/go.mod, examples/sasl_scram_client/go.sum, examples/txn_producer/go.mod, examples/txn_producer/go.sum
CVE-2024-45338
GHSA-w32m-9786-jp63
=> chore(deps): bump golang.org/x/net to v0.33.0

admin.go, admin_test.go, broker.go, elect_leaders_request.go, elect_leaders_request_test.go, elect_leaders_response.go, elect_leaders_response_test.go, election_type.go, mockresponses.go, request.go
feat: #2744 
implement leader election api in sarama
[elect leaders API](https://kafka.apache.org/protocol.html#The_Messages_ElectLeaders)
=> feat(admin): implement leader election api

.github/workflows/fvt-main.yml, .github/workflows/fvt-pr.yml, Dockerfile.kafka, create_topics_request.go, delete_topics_request.go, functional_consumer_test.go, functional_producer_test.go, functional_test.go, server.properties, utils.go
Whilst 4.0 isn't yet released, in order to allow us to do some up-front testing, compile from src and include in FV runs
Note: we have to include a server.properties for ZooKeeper mode as the 4.0 release no longer includes it. They only ship a Kraft-mode config file and we still want to run in ZooKeeper mode for now as its more convenient for the FV setup to be consistent
=> chore(test): include kafka 4.0.0 in FV testing

.github/workflows/cache-cleanup.yml
As per the GitHub docs, keep the Actions Cache clean and tidy by explicitly purging any entries that reference the branch on close/merge of a PR
=> chore(ci): add cache cleanup job for closed PRs

Dockerfile.kafka, docker-compose.yml
Having purged the caches and re-built the FV images, it is evident that the 3.4.13 zookeeper client is incompatible with Java 17 (see ZOOKEEPER-3779). Rather than use different Java versions for those, just quietly bump the bundled zookeeper client to 3.5.9 (as used in Kafka 2.6) which is API compatible and resolves the issue with Java 17
=> fix(ci): patch zookeeper client to 3.5.9 on older Kafka

admin.go, errors.go, functional_admin_test.go
- retry admin operations that rely on talking to the group coordinator for a given ID if the coordinator has changed from the cached value, or is not available
- also fixup controller retry in ElectLeaders to use the err from response rather than sendAndReceive
- also rename isErrNotController to isRetriableControllerError for consistency
=> fix(admin): add retries for GroupCoordinator errors

.github/dependabot.yml
- use new 'directories' keys for updates across multiple directories https://github.blog/changelog/2024-04-29-dependabot-multi-directory-configuration-public-beta-now-available/
- add explicit timezone to schedules
- add group for otel dependencies
=> chore(deps): update dependabot config

.github/workflows/fvt-main.yml, .github/workflows/fvt-pr.yml
Just for consistency, use the last patch release of 2.6.x for FV testing. Also fix the scala-version entry for 3.8.1 in the fv-main build matrix.
=> chore(ci): bump 2.6.x FV to its last patch release

Dockerfile.kafka
The build is broken again because the pinned commit has dropped off the last 50 commits of branch 4.0. Bump up the depth and use a full qualified sha too.
=> chore(ci): fetch kafka 4.0 via tar.gz rather than git

.github/workflows/fvt.yml, .github/workflows/scorecard.yml
- consistently pass KAFKA_VERSION as envvar to ensure the shell performs the variable expansion
- update scorecard.yml read-only permissions to be narrower and more explicit
=> fix(ci): tighten up github workflows

broker.go
- Currently, there is no `Token` nil inspection.
- as-is: `if token.Extensions != nil && len(token.Extensions) > 0 {`
- to-be: `if token != nil && token.Extensions != nil && len(token.Extensions) > 0 {`
=> fix(sasl): add nilguard around token to prevent panic

consumer_group_test.go
There is a bug in the tests with
```go
NewMockSequence(
NewMockFetchResponse(t, 1).
SetMessage("my-topic", 0, 0, StringEncoder("foo")).
SetMessage("my-topic", 0, 1, StringEncoder("bar")),
NewMockFetchResponse(t, 1),
)
```
This sets the message on the first `NewMockFetchResponse` twice and does not set the message on the second response. This was covered up in the test because of the `break` in the for loop over `claim.Messages()`. The update now passes the messages through a channel back to the test for assertion.  
In addition, the `context.WithCancel` was not having any affect on the test. Closing the group causes the context to be Done. This is verified by utilizing the same channel.
=> fix(test): consumer group fetch request messages

async_producer.go, async_producer_test.go, config.go
This PR introduces the MaxBufferBytes configuration to Sarama’s producer, allowing users to limit the retry buffer size based on the total byte size of messages. This complements the existing MaxBufferLength configuration, which limits the number of messages in the retry buffer. The implementation ensures more robust control over memory usage and prevents potential OOM issues when dealing with large messages.
The changes are built upon the foundation laid in https://github.com/IBM/sarama/pull/3026, further enhancing the retry buffer’s configurability and usability.
- Added a new Producer.Retry.MaxBufferBytes configuration.
- The type of MaxBufferBytes is int64, as the maximum value of int32 (approximately 2 GB) is insufficient for buffers holding many messages of large average size, such …
=> feat(producer): add MaxBufferBytes to limit retry buffer size

mocks/async_producer.go
[mocks/async_producer.go](https://github.com/IBM/sarama/blob/e2fa7bf18c064719197abba64a2ce14c8227a92d/mocks/async_producer.go#L77) remove unnecessay nil check.
```
var slice []byte
if slice == nil || len(slice) == 0 {}
// is the same as
if len(slice) == 0 {}
```
because `len(slice)` where slice == nil is always equal to 0,
`staticcheck` will highlight this optimization with the following message:
```
mocks/async_producer.go:77:7: should omit nil check; len() for []*github.com/IBM/sarama/mocks.producerExpectation is defined as zero (S1009)
```
for reference: [staticcheck S1009](https://staticcheck.dev/docs/checks#S1009)
=> fix: remove redundant nil check

.github/workflows/ci.yml, .golangci.yml
Bring golangci-lint up-to-date
=> chore(ci): bump golangci-lint version to v1.63.4

.github/actions/staticcheck-matchers.json, .github/workflows/ci.yml, .golangci.yml, .pre-commit-config.yaml, balance_strategy.go, metrics_helpers_test.go, mocks/mocks.go
As we've noted that a standlone run of staticcheck can find different
issues compared with running it from golangci-lint, add a standalone run
to github actions and remove it from the golangci-lint config
=> feat(ci): add dedicated staticcheck run

produce_set.go, produce_set_test.go
Similar to other clients, set the MaxTimestamp computed from the records
in the batch.
=> produce: set MaxTimestamp

async_producer_test.go, utils.go, utils_test.go
This PR introduces a configurable **exponential backoff function** for the producer, admin client, and transaction manager, aligning with [KIP-580](https://cwiki.apache.org/confluence/display/KAFKA/KIP-580%3A+Exponential+Backoff+for+Kafka+Clients) specifications.  
- Implements `NewExponentialBackoff(initialBackoff, maxBackoff)` as a **static function**, rather than a method of `Config`.  
- **Decision:** Since `Config` contains multiple backoff settings (e.g., for the admin client, transaction manager, and producer), attaching the function to `Config` would introduce ambiguity.  
- A standalone function provides **clearer separation of concerns** and **avoids confusion** when setting different backoff strategies.  
- Uses an **exponential growth** pattern with jitter:  
```math …
```
=> feat: exponential backoff for clients (KIP-580)

describe_client_quotas_request.go, describe_client_quotas_request_test.go, functional_admin_test.go
DescribeClientQuota currently fails with the following error message logged by the Kafka broker when trying to describe default client quotas:
```
org.apache.kafka.common.errors.InvalidRequestException: Request specified MATCH_TYPE_DEFAULT, but also specified a match string
```
This is because we are currently sending an empty string (`""`) instead of a null as the match string
The Java client simply ignores the match string here to avoid this issue, so I propose we do the same https://github.com/apache/kafka/blob/3ed590288fd773902f7791959e8f081ff937c144/clients/src/main/java/org/apache/kafka/common/requests/DescribeClientQuotasRequest.java#L54-L55
=> fix: send null instead of empty string when describing default client quotas

.github/workflows/ci.yml, .golangci.yml
The golangci-lint action is refusing to use the older version of golangci-lint now, so bump to latest v2 and run `golangci-lint migrate` to convert the config file to the latest format
=> fix(ci): bump golangci-lint to v2

metrics.go, metrics_test.go
Good day,
This PR improve the performance of `getMetricNameForBroker` and `getMetricNameForTopic` by removing the usage of `fmt`.
The [benchstat](https://pkg.go.dev/golang.org/x/perf/cmd/benchstat) result are as follows. The benchmarks when run using `go test -bench '^\QBenchmark_getMetricNameFor' -run=^$ -count=10`.
```
goos: linux
goarch: amd64
pkg: github.com/IBM/sarama
cpu: AMD Ryzen 7 Pro 7735U with Radeon Graphics     
│ faec4c823ff893c7fc7b10021b66542fa77f7cb8.txt │ 07db3539fb81f1bf77d8a8a910b2b1e72b4c52c3.txt │
│                    sec/op                    │        sec/op         vs base                │
_getMetricNameForTopic-16                                    157.55n ± 0%            66.85n ± 1%  -57.57% (p=0.000 n=10)
_getMetricNameForBroker-16 …
```
=> fix: improve getMetricName performance

admin.go, create_topics_request.go, functional_test.go
Add support for using CreateTopicRequest V4 against Kafka 2.4 and newer clusters. Protocol-wise this is identical to the existing V3, but the version indicates that the server should accept `-1` as the partition and replicate-factor values to indicate "use the server side defaults" (KIP-464).
Contributes-to: IBM/sarama#3233
=> feat(protocol): support CreateTopicRequest V4

.github/renovate.json5
Configure renovate to match the existing dependabot configuration as much as possible to experiment with which is preferable
=> chore(ci): replicate existing dependabot config to renovate

.github/renovate.json5, .github/workflows/renovate-config.yml
Porting the dependabot schedules didn't quite match the "later" syntax that Renovate supports. I also note from their docs that they strongly recommend just using crontab syntax everywhere now, so switch to that instead:
https://docs.renovatebot.com/configuration-options/#schedule
Also add a simple github workflow to ensure any changes to renovate config are valid going forward
=> fix(ci): switch to crontab for renovate.json

.github/renovate.json5
Despite appearing in the docs as a valid preset [1] and passing renovate-config-validator successfully, this doesn't seem to exist on the version of renovate being used by "ibm-mend" on github.com, so replace it with the equivalent in-line config.
[1] https://docs.renovatebot.com/presets-default/#enablevulnerabilityalertswithlabelarg0
Fixes #3250
=> fix(ci): replace renovate preset with config

compress.go
Split out the gzip and lz4 case blocks similarly to the zstdCompress func
=> chore(style): refactor compress.go for readability

broker.go, client.go, consumer.go, mocks/consumer.go
**What type of PR is this?**
> Other
**What does this PR do? Why is it needed?**
This PR updates our atomic operations to use `Go 1.19's` newer typed atomic approach instead of the old function-based method. We're changing fields like `int64` to `atomic.Int64` so we can write cleaner code like `child.retries.Add(1)` instead of `atomic.AddInt32(&child.retries, 1)`. This removes the need for pointer handling and gives us better compile-time safety when multiple threads access the same variables in  operations.
**Which issues(s) does this PR fix?**
The function-based atomics allowed accidental non-atomic access to shared variables, causing race conditions in concurrent  operations. The verbose `atomic.AddInt32(&child.retries, 1)` syntax was harder to maintain. Typed atomics enforce …
=> chore: refactor to use modern atomic types

.github/workflows/ci.yml, .pre-commit-config.yaml
Bump golangci-lint version in ci to v2.4.0 to match too
=> chore: pre-commit autoupdate to latest

broker.go, broker_test.go, config.go, gssapi_kerberos.go, kerberos_client_test.go
For some reason we were still pinning the old v0 SASL when using GSSAPI and this doesn't work if an ApiVersionsRequest is sent before the auth flow.
Add support for sending the krb5 bytes in the v1 SASL SaslAuthenticate protocol wrapping.
Note: this is just a draft for now as although it is tested and working against a GSSAPI enabled cluster, the underlying code is very much a copy-and-paste of the existing v0 auth flow, just wrappering the bytes in the SaslAuthenticate rather than sending them to the broker directly. This needs more work to tidyup the implementation
=> feat: add SASLv1 support for Kerberos

admin.go, balance_strategy.go, balance_strategy_test.go, broker.go, broker_test.go, client.go, delete_records_request.go, delete_records_response.go, metrics_test.go, mockbroker.go, mocks/mocks.go, tools/kafka-console-producer/kafka-console-producer.go, zstd_test.go
Apply a selection of the gopls [modernize](https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize) fixes category-by-category:
```
go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -category=$CAT ./...
```
=> chore: apply modernize fixes from gopls

request_test.go
- refactor the existing tests for 2.0.0 and 2.1.0 to only test the api keys that changed in version
- similarly add a 2.2.0 variant so we can start to tickoff completion
- add a "max version" test that attempts to ensure we've got matching requiredVersion etc. in the request and response for all the versions we've currently implemented
=> fix: extend TestAllocateBodyProtocolVersions for more testing

Dockerfile.kafka, client.go, offset_request.go, offset_response.go, request_test.go
V5 adds a new error code, OFFSET_NOT_AVAILABLE, but is otherwise identical to V4
=> chore: support V5 ListOffsets

elect_leaders_request.go, elect_leaders_request_test.go
And clean up the misleading layout/comment of the []bytes in the test:
Test layout for V2 `[]byte` was:
```
0, 0, // empty tagged fields
0, 39, 16, 0, // timeout 10000
```
but, while the bytes were correct the comments were misleading as the encoding is really:
```
0,            // empty tagged fields
0, 0, 39, 16, // timeout 10000
0, // empty tagged fields
```
=> fix: non-flexible ElectLeadersRequest V0/V1 encode/decode

.github/workflows/ci.yml, .github/workflows/fvt.yml, Makefile
Switch to using gotestsum as a runner in the Makefile and move tparse into the .github/workflows as it is GitHub Actions specific and so that we can run it with `always()` rather than only when tests pass.
Additionally add missing coverage dump for unittest runs (we already had it for FV runs) and also output teststat information in Makefile which highlights the slowest tests and any re-run flakes.
=> chore(ci): adopt gotestsum and re-run flakes

request.go, request_test.go
It seems strange to return `bytesRead` but for it to be the wrong value when the correct value is available.
=> fix: correct decodeRequest bytesRead return value

admin.go, delete_groups_request.go, delete_groups_request_test.go, delete_groups_response.go, delete_groups_response_test.go, functional_admin_test.go, request_test.go
Version 2 is the first flexible version
=> feat: support DeleteGroups V2 protocol

Dockerfile.kafka, docker-compose.yml, entrypoint.sh, functional_admin_test.go, functional_test.go
- make use of docker compose 'fragments' (yaml anchors) to reduce a lot of duplication in the docker-compose
- remove the pinned commit we were using to test Kafka 4.0 with ZooKeeper support and start testing against the release with KRaft enabled
- use the entrypoint.sh to remove the inappropriate broker properties if in zookeeper mode or kraft mode respectively
- don't start the zookeeper containers unless `--profile zookeeper` is passed, this saves on the resource at the cost of not necessarily being obvious to a casual user. It's a shame we can't selectively start them based on KAFKA_VERSION
=> chore(fvt): refactor docker-compose and support KRaft

.github/workflows/fvt-main.yml, .github/workflows/fvt-pr.yml, .github/workflows/fvt.yml, Dockerfile.kafka, docker-compose.yml, entrypoint.sh, utils.go
- add version constants to utils.go for latest releases
- add 4.1.0 to fvt-main
- tweak fvt-pr to drop 3.8.1 and 4.0.0 and replace them with 3.9.1 and 4.1.0
- update the "default" KAFKA_VERSION when running the FVT locally from 3.6.2 to 3.9.1
=> chore: add 3.9.1 and 4.1.0 version constants and FVT

join_group_request.go
The `encode` method failure should probably be an encoding error not decoding one.
=> fix: return correct error when encoding

consumer_group.go, heartbeat_request.go, heartbeat_request_test.go, heartbeat_response.go, heartbeat_response_test.go, request_test.go
Version 4 is the first flexible version
=> feat: support Heartbeat V4 protocol

functional_consumer_group_test.go, functional_producer_test.go
- ensure ConsumeClaim returns when it should
- use require.EventuallyWithT
- add a bunch of t.Logf so it's clearer what state each consumer reaches
Contributes-to: #3310
=> chore(fvt): improve testFuncConsumerGroupMember

api_versions_response.go, api_versions_response_test.go, encoder_decoder.go
Improve the api_versions_response_test.go to be more representative of the different good and bad responses it might receive.
Subsequently fix the ApiVersionsResponse decoding so that it correctly downgrades the decoder from flexible to non-flexible after reading the ErrorCode of UnsupportedVersion
=> fix: correct ApiVersionsResponse handling of ErrUnsupportedVersion
