producer_test.go

Cleanup producer tests

---

producer.go

Producer: implement AsyncClose

---

producer.go

Drop the broker if we can't connect to it

---

producer_test.go

e.g. it goes down and comes back up again ~~immediately~~ *within our configured RetryBackoff*, still holding leadership
cc @Shopify/kafka @Sirupsen this uses `NewMockBrokerAddr` (which I just added in #283) and is a good example of a simple but useful resiliency test using mockbrokers

Add a test for the producer when a broker bounces

---

broker.go

- drop default network timeouts from 60 to 30 seconds to match JVM-land
- document the default, and the JVM-land equivalent (part of #270)
- validate `DialTimeout`
- change the semantics of `MaxOpenRequests` to actually be the maximum number of
open requests, as opposed to the size of the buffer directly (since an
unbuffered channel still permits one open request at a time). This involves
bumping the default by one, validating for >0 (not just >=0) and subtracting
one to get the actual channel buffer size.
@Shopify/kafka

A handful of cleanups to the broker configuration

---

client.go

This bugged me when looking at our logs; broken windows etc. @Shopify/kafka

Nicer fetch metadata logging

---

client_test.go
consumer_test.go
producer_test.go

@Shopify/kafka as suggested in review of #234

Cleanup tests

---

producer_test.go

Assert there are no outstanding successes in the producer tests

---

producer_test.go
sync_producer.go

Return the partition and offset of successful messages to the user as well.
As suggested by Willem in
https://github.com/Shopify/sarama/issues/302#issuecomment-76159600
@Shopify/kafka

Rename SimpleProducer to SyncProducer

---

broker_test.go
consumer_test.go
functional_test.go
partitioner_test.go
producer_test.go

Recent versions of errcheck have started checking in _test.go files as well,
revealing a handful more errors that need handling.
@Shopify/kafka

Check for errors in test code

---

.travis.yml
vagrant/install_cluster.sh
vagrant/provision.sh

Run CI against Kafka 0.8.2.0 and 0.8.1.1

---

consumer_test.go

Fix Consumer example function names to follow convention

---

consumer_test.go
producer_test.go

Add some godoc to the examples, and clean them up a bit.

Clean up and document examples

---

producer_test.go

Skip it until the bug is fixed, but at least it will keep up with the API
changes now. Before it was inline in the ticket, and was falling behind.
cc @wvanbergen

Add a test for bug #294

---

consumer_test.go

Skip it until the bug is fixed.
Also add a missing error check in the test above.
cc @wvanbergen

Add a test for bug #325

---

.travis.yml
vagrant/provision.sh

It will be released later today and the tarballs are already on the mirrors.
@Shopify/kafka

Kafka 0.8.2.1 in CI etc.

---

client.go

Retry UnknownTopicOrPartition on fetching metadata

---

config.go
consumer.go
consumer_test.go
functional_test.go
mocks/producer.go
mocks/producer_test.go
producer.go
producer_test.go
sync_producer.go

Return{Errors,Successes} -> Return.{Errors,Successes}

---

broker.go

Don't log "Error closing broker" when the only error is that it's already
disconnected. Don't defer, there's nothing else in the method that can return.
@Shopify/kafka

Reduce logging on broker close

---

sarama.go

:bike: :house: time over wording
@Shopify/kafka

Update package godoc

---

client.go
client_test.go
consumer.go
producer.go
sync_producer.go

This allows people to mock a Client more easily for testing purposes. Maybe later, we will provide a mock implementation ourselves.
@Shopify/kafka

Make Client an interface.

---

client.go
consumer.go
offset_request.go

Remove OffsetTime type, just use int64.

---

client.go

- Inline `getMetadata` it only had one caller left.
- now that `RefreshMetadata` is the only non-recursive caller of
`tryRefreshMetadata`, move the one-time checks for a closed client and invalid
topic names outside the recursion, we only need to run them once.
Should be no functional changes.
@Shopify/kafka

Cleanup some client internals

---

encoder_decoder.go
sarama.go

Make MaxRequestSize signed for consistency with MaxResponseSize

---

CHANGELOG.md

Prepping for our 1.0 release. @Shopify/kafka

Add an initial CHANGELOG

---

partitioner_test.go

Towards addressing #323 and #302. @Shopify/kafka

Add examples for random and manual partitioning

---

async_producer.go

If none of the three are set, flush as fast as possible, per normal. If *any* of
the three are set, *only* respect the ones that are set.
@Shopify/kafka

Adjust producer flushing semantics

---

mocks/README.md

README for the mocks subpackage

Add README for mocks subpackage

---

README.md

Update README for semantic versioning and gopkg.in

---

examples/README.md
examples/http_server/.gitignore
examples/http_server/README.md
examples/http_server/http_server.go
examples/http_server/http_server_test.go

This example shows you when and how to use the `SyncProducer` and `AsyncProducer`, and how to test them using mocks.
@Shopify/kafka

Add http_server example

---

consumer.go

Move all redispatch/error logic out of `handleResponse` and into a single if
statement, based on the new return value of `handleResponse`.
@Shopify/kafka

Refactor partitionConsumer a bit

---

functional_client_test.go
functional_producer_test.go
functional_test.go

@Shopify/kafka Extracted from #379

Split functional tests into different files

---

functional_producer_test.go

Use SyncProducer so the various goroutines get their own success/error back and
not somebody elses. Don't call Fatal in a goroutine, it doesn't work. Don't pass
the wait group as a parameter, it doesn't change so it's unnecessary.
@Shopify/kafka

Cleanup TestFuncMultiPartitionProduce

---

.travis.yml
Makefile
functional_test.go
vagrant/install_cluster.sh
vagrant/run_toxiproxy.sh
vagrant/server.properties

We still don't have any actual tests, but this loads the client and connects, which is step 2.
@Shopify/kafka

Connect to toxiproxy in functional tests

---

client.go

Use a none map for the toRetry topics instead of bool

---

functional_client_test.go
functional_consumer_test.go
functional_producer_test.go
vagrant/create_topics.sh

and easier to remember and more consistent.

Rename test topics to be shorter

---

client_test.go
functional_producer_test.go
functional_test.go

Add some simple producer benchmarks

---

async_producer.go

Fix async producer typo

---

consumer.go

- rename a last few references to "brokerWorker"
- use `bc` instead of `w` as the abbreviation
- extract `newBrokerConsumer` as its own function
@Shopify/kafka no functional changes, just cleanup

Refer to brokerConsumers consistently

---

broker.go
client.go

This doesn't change the behaviour, but it makes the implementation easier to follow. I also improved logging.
@Shopify/kafka

Refactor metadata retry logic and improve logging

---

functional_client_test.go
functional_consumer_test.go
functional_producer_test.go
functional_test.go
vagrant/install_cluster.sh

Bump toxiproxy to fix one potential issue, and add some framework for using it in functional tests.
@Shopify/kafka only test code changes, so if CI is happy this can go in 1.4 as well.

Toxiproxy cleanup

---

consumer_test.go

May or may not fix another flaky test (e.g.
https://travis-ci.org/Shopify/sarama/jobs/66086521)

Add a missing offset check to a test

---

config.go

Tweak tls configuration values

---

async_producer.go

@Shopify/kafka this is functionally no different but I think it's conceptually slightly simpler?

simplify goroutine constructor semantics slightly

---

mockbroker_test.go

This PR adds History() method to mockbroker. The method returns RequestResponse pairs in the order it has processed them. The method is supposed to facilitate testing of requests generated by the code. E.g. for offset manager testing. The workflow should be as follows:
* mock responses
* execute test logic
* stop mock broker
* inspect the recorded history
Note that lock on history is needed because a mockbroker can have several connections, each of them running in a goroutine of its own updating the history.

Add History() method to mockbroker

---

consumer_metadata_response.go
consumer_metadata_response_test.go
mockresponses_test.go
offset_commit_response.go
offset_commit_response_test.go
offset_fetch_response.go
offset_fetch_response_test.go
request_test.go

This PR brings mock response builders and respective additions to response structs that are used by offset manager.

Add mock responses for OffsetManager testing

---

.travis.yml
README.md

Add go 1.5 to build matrix

---

async_producer_test.go

This should fix the last remaining annoyingly-flaky test after all the work
Maxim did on the flaky consumer tests. I hope.
@Shopify/kafka

Fix the flakiest producer test

---

consumer_test.go

Somehow we never added this.
@wvanbergen @i19 
Fixes #556.

Add an example of using the consumer

---

client.go
mockresponses_test.go
offset_manager.go
prep_encoder.go
real_decoder.go
real_encoder.go
sync_producer.go

A few minor suggestions from golint

---

.travis.yml

cc @wvanbergen #582 says we fail to compile for some reason, let's see

Bump CI from 1.5.1 to 1.5.2

---

broker.go
broker_test.go

Add two other missing broker calls for kafka 0.9

---

CHANGELOG.md
Makefile
config.go

Remove the caveat from the configuration, and add the verification to the
CHANGELOG.
cc @wvanbergen

Update docs around TLS

---

.travis.yml
vagrant/provision.sh

New bugfix release for kafka 0.9

---

.travis.yml

Add go 1.6 to CI

---

config.go
config_test.go

Fixes #632.
@wvanbergen @bruth

Validate client ID

---

vagrant/install_cluster.sh

@wvanbergen @Sirupsen @xthexder hopefully this Just Works

Bump to toxiproxy 2.0

---

errors.go

Corrects a simple misspelling.

Fix typo in ErrReplicaNotAvailable

---

examples/http_server/http_server.go

in order for the Successes channel to be populated,have to set config.Producer.Return.Successes to true

add config setting

---

tools/kafka-console-producer/kafka-console-producer.go

verifyProducerConfig() will [check the config](https://github.com/Shopify/sarama/commit/f0062da5ae1a62f7841e563a244e11a5ad9b96d7#diff-9aea0c6326a7f3fb0c000fabf28b3d22R82).

Fix config for calling NewSyncProducer()

---

broker.go
client.go

Just fixing two typos in code comments.

Fixing two typos

---

async_producer.go
async_producer_test.go
consumer.go
consumer_group_members_test.go
mocks/consumer.go
mocks/consumer_test.go
sync_producer_test.go

Just runned gofmt -w -f in all files to get the simplified and formatted version of the code.

Formatting all files with gofmt -s

---

api_versions_response.go
client.go
describe_groups_response.go
heartbeat_response.go
join_group_response.go
leave_group_response.go
list_groups_response.go
mocks/sync_producer.go
produce_response.go
real_decoder.go
sasl_handshake_response.go
sync_group_response.go

Followed GoLint tip to drop else statement when if blocks ends with a return statement

Removed all else statement where if block ends with a return

---

examples/README.md

Fix tiny typo in examples README link

---

async_producer.go

this setting was renamed twice. See:
- 5411ec3676ba932f988c614650cdc314b8def468
- 4189e55a44bd4e04772171b5e7a7b6dcd12603f6

fix mention of Return.Successes

---

consumer.go

As per the discussion in https://github.com/Shopify/sarama/issues/920,
I've added some verbiage to the docstrings around Close & AsyncClose
on interface PartitionConsumer.

Docstring change only to PartitionConsumer.

---

.travis.yml
message_test.go

As discussed at https://github.com/Shopify/sarama/pull/950.

travis: update go versions

---

.travis.yml
README.md
vagrant/install_cluster.sh

Add Kafka 0.11 to CI to make sure it works.
Mention it and Go 1.9 in the README.

Bump some versions

---

.gitignore
.travis.yml
Makefile
README.md

Linking up with codecov.io to show coverage. 
Added the badge in the README.

Added coverage badge

---

client.go

We have spent two damn days debugging this... :-(

add format of an GetOffset argument to documentation

---

produce_set.go
produce_set_test.go

Fix header references during record build.

---

.travis.yml
vagrant/halt_cluster.sh

Apparently the new travis image won't stop until all your background
processes are dead, which I suppose is nice of it but took me a long
time to figure out.
Same symptoms as travis-ci/travis-ci#8898 but a different root cause it seems.

Fix CI: Shut down the cluster afterward

---

broker.go
create_topics_request.go
create_topics_request_test.go
create_topics_response.go
create_topics_response_test.go
request.go

follows on from #852 with the necessary request/response pair for creating topics.

add CreateTopicsRequest/Response

---

broker.go
delete_topics_request.go
delete_topics_request_test.go
delete_topics_response.go
delete_topics_response_test.go
request.go

went ahead and did delete topics as well while at it.

add DeleteTopicsRequest/Response

---

delete_topics_request.go
delete_topics_request_test.go

Interestingly, support for DeleteTopicsResponse v1 was there but not for the request !

Added support for v1 DeleteTopicsRequest

---

request_test.go

This keeps getting missed in code coverage, hopefully this PR covers most cases automatically.

Simple validation of required version

---

produce_set.go

@pkedy and I thought it might not be a bad idea to document the change we made for issue #1032

Document recordbatch offset changes from #1032

---

broker.go

So that you can add more partitions 😄

Add CreatePartitions to Broker

---

.travis.yml
README.md
utils.go

Add support for Kafka 1.1.0

---

async_producer.go

Fixes the part of https://github.com/Shopify/sarama/issues/1074 that was our fault.

Add version check for headers

---

admin.go
config.go
config_test.go

This is the fix for the issue reported here #1120

add Timeout config for ClusterAdmin related Requests

---

config_test.go

Fix kakfa typo

---

.travis.yml
README.md
client_tls_test.go
dev.yml

This PR adds support for Golang 1.11.

Support Go 1.11

---

consumer_group.go
consumer_group_members.go
consumer_metadata_request.go
consumer_metadata_response.go

Few more typo/vet fixes that I came across while reading the code.

fixed some typo and added some comments

---

errors.go

Add error codes 73-76

---

message.go

Fixes https://github.com/Shopify/sarama/issues/1288.

Fix previousy/previously typo

---

CHANGELOG.md

Add changelog for sarama v1.21.0

---

request.go

- Error wasn't returned on line 51, I fixed that bug.
- I also removed naked returns as they are a source of confusion and masks bugs related to error return
@bai please have a look at this before cutting next release.

fixed a bug related to error return

---

acl_types.go
config_resource_type.go
describe_configs_response.go
fetch_request.go
find_coordinator_request.go
message.go
sarama.go
utils.go

- using iota
- variable blocks

using iota for constants and some style fixes

---

Makefile

- Added phony targets that improve make performance
- added shell check before running errcheck
- added a lint command to make

added phony targets to make file

---

admin.go
admin_test.go
broker.go
client.go
config.go
consumer.go
mockresponses.go
offset_commit_request.go
offset_manager.go
produce_set.go

Suggestions by the `staticcheck` tool (https://staticcheck.io/).

Address a few staticcheck suggestions

---

examples/consumergroup/main.go

[fix] run multi consumer group instance crash

[fix] run multi consumer group instance crash

---

acl_bindings.go
acl_create_request_test.go

Am using vim, this took almost an hour to figure out why.

Refactor misspelled word Resouce to Resource

---

admin_test.go
consumer_group.go
consumer_test.go
describe_groups_response.go
describe_groups_response_test.go
errors.go
heartbeat_request.go
heartbeat_request_test.go
join_group_request.go
join_group_request_test.go
join_group_response.go
join_group_response_test.go
leave_group_request.go
leave_group_request_test.go
leave_group_response_test.go
list_groups_response.go
mockresponses.go
offset_manager.go
sync_group_request.go
sync_group_request_test.go

This is a sarama 2.0 PR, so let's not release as part of version 1 or things will break :)
There are still 300 lint errors, but want to PR them 1 by 1.

Breaking Change - Fixed Id related lint errors

---

CHANGELOG.md

Add changelog for sarama 1.23.0

---

CHANGELOG.md
dev.yml

Prepare for releasing v1.24.0.

Compile changelog for v1.24.0

---

consumer_group.go

fixed Add a new partition during the consumer group running，but the cousumer group not rebalance。

fixed  Add a new partition during the consumer group running，but the cousumer group not rebalance  #1462

---

CHANGELOG.md

Compile changelog for 1.24.1 [ci skip]

---

config.go

fix breaking API change added in
https://github.com/Shopify/sarama/pull/1164 https://github.com/Shopify/sarama/pull/1164#pullrequestreview-350270834
Fixes:
- https://github.com/bsm/sarama-cluster/pull/308
- https://github.com/bsm/sarama-cluster/issues/307
- https://github.com/lovoo/goka/issues/211

Adds back Consumer.Offsets.CommitInterval to fix API

---

.github/probots.yml
.github/stale.yml

As discussed via email, adding 90/30 day stale probot. Thanks @dnwe for the hint and snippets 🙏

Add stale probot

---

.github/workflows/ci.yml
README.md
dev.yml

Add support for Go 1.14

---

.github/workflows/ci.yml
utils.go

Add support for kafka 2.5.0

---

.github/workflows/ci.yml

Short-term workaround to address build flakiness.

Reduce build matrix

---

examples/README.md

fixes https://github.com/Shopify/sarama/issues/1779
----
#

remove example binary

---

.github/workflows/ci.yml

Run tests against Golang 1.16 on CI.

Test against Go 1.16

---

docker-compose.yml
functional_test.go

And make default in docker-compose match too.

fix(test): bump default KAFKA_VERSION to 2.7.1

---

client.go
config.go

For https://github.com/Shopify/sarama/issues/1982

allow configure AllowAutoTopicCreation argument in metadata refresh

---

.github/workflows/codeql-analysis.yml
go.mod

https://go.dev/ref/mod#go-mod-file-retract

chore: add retractions for known bad versions

---

examples/consumergroup/main.go

I refer the [consumeGroupExample](https://github.com/Shopify/sarama/blob/main/examples/consumergroup/main.go), and I meet the same problem with this issue #1192.
So I add the solution to the example.

fix: check session.Context().Done() in examples/consumergroup

---

.github/workflows/fvt.yml
Dockerfile.kafka
docker-compose.yml
entrypoint.sh
utils.go

- add version number constant
- replace 3.3.1 with 3.3.2 in Dockerfile and FVT

chore: add kafka 3.3.2

---

consumer.go

fix(comments): PauseAll and ResumeAll

---

admin.go
alter_configs_request.go
alter_configs_response.go
create_partitions_request.go
create_partitions_response.go
describe_configs_request.go
describe_configs_response.go
request_test.go

This is identical in format to V0, but just influences the broker's response behaviour

chore(proto): permit AlterConfigsRequest V1

---

async_producer_test.go
broker.go
consumer_group_test.go
metadata_request.go
metadata_request_test.go
metadata_response.go
metadata_response_test.go
mockbroker.go
mockresponses.go

In particular, this adds support for topic UUIDs

feat(proto): support for Metadata V6-V10

---

config.go
utils.go

Also put default SASLHandshake version back to V1

chore(config): make DefaultVersion V2_0_0_0

---

utils.go

chore(config): make DefaultVersion V2_1_0_0

---

broker.go

fix: data race in Broker.AsyncProduce

---

CODE_OF_CONDUCT.md

Add GitHub's Contributor Covenant Code of Conduct template

chore(doc): add CODE_OF_CONDUCT.md

---

gssapi_kerberos.go

The new pr is a custom config enhancement that allows the creation of custom spn build.
After allow custom spn build, this also will satisfy #2437
add a function type  `type BuildSpnFunc func(serviceName, host string) string`
add a field `BuildSpn BuildSpnFunc` to `type GSSAPIConfig struct`
then user can set a custom `BuildSpn`
```
?       github.com/IBM/sarama/internal/toxiproxy        [no test files]
?       github.com/IBM/sarama/tools/kafka-console-consumer      [no test files]
?       github.com/IBM/sarama/tools/kafka-console-partitionconsumer     [no test files]
?       github.com/IBM/sarama/tools/kafka-console-producer      [no test files]
?       github.com/IBM/sarama/tools/kafka-producer-performance  [no test files]
?       github.com/IBM/sarama/tools/tls [no test files]
ok …
```

feat: add BuildSpnFunc to GSSAPIConfig for allow custom spn

---

async_producer.go

This is retriable according to the spec: https://kafka.apache.org/protocol.html

fix(producer): treat ErrKafkaStorageError as retriable

---

utils.go

https://downloads.apache.org/kafka/3.7.2/RELEASE_NOTES.html

chore: add version constant for kafka 3.7.2

---

.github/workflows/codeql-analysis.yml

Ref: https://github.blog/changelog/2024-12-17-find-and-fix-actions-workflows-vulnerabilities-with-codeql-public-preview/

chore(ci): analyse actions in codeql

---

admin.go

Results in fewer allocs and simpler copying to returned value

refactor: use struct rather than map with one entry

---

create_topics_response.go

fix: add V4 as valid CreateTopicsResponse

---

functional_admin_test.go

Experiment with using testify to make this assertion block cleaner and more reliable. Also allow up to 10 seconds wait time.

fix(fvt): simplify retry using testify's EventuallyWithT

---

real_decoder.go

Couple of issues spotted while debugging protocol message updates.

fix: decoder issues

---

broker.go
consumer_group.go
join_group_request.go
join_group_request_test.go
join_group_response.go
join_group_response_test.go
real_decoder.go
request_test.go

Version 6 is the first flexible version
The other commits are a fix for a bug that broken the FVTs for this protocol bump and a very minor refactor that I spotted while debugging.

feat: support JoinGroup V6 protocol
